--[[
Универсальный скрипт больших битв с монстрами/неписями
Поддерживаются:
Спавн по таймеру каждой волны монстров
Передышки между волнами
Спавн неподалеку от гг рюкзака с патронами/аптечками по время передышки с выдачей информации через СМС
Монстры спавнятся не вокруг ГГ, а в определенном секторе справа, слева или сзади ГГ рандомно, на указанном удалении. Спереди не спавнятся.
"Быстрый" уборщик, который во избежание тормозов убирает скопления трупов монстров при удалении гг от них на определенное расстояние

начало битвы запускается так: 
amk.start_timer("battle", 0, {"level", num, 1})
где
level - уровень, на котором битва;
num - номер битвы на уровне;
1 - начинаем с первой волны

Замечания:
Вместо монстров можно прописывать секции неписей (монолита, например). Только уборщик не будет убирать их трупы.
Если в одной из волн прописать секции дружественных неписей - то они также заспавнятся и будут воевать на стороне гг.
]]

local cleanup_distance = 50				-- расстояние от ГГ в м, на котором уборщик убирает трупы
local rest_timeout = 120				-- время передышки в секундах (добавляется ко времени следущей волны +-20%)
local min_good_distance = 40			-- минимальная дистанция, на которой можно спавнить волну. если подходящий вертекс на указанном расстоянии или дальше не находится (гг заныкался в закутке - не находится в открытом месте) то спавн волны откладывается
local min_good_distance_timeout = 10	-- время в реальных с, на которое откладывается спавн след волны, если гг заныкался

local monster_cnt = 0					-- общее количество заспавненных монстров с момента последней передышки

-- лекарства для рюкзака
local medkits = {"medkit", "medkit_army", "medkit_scientic", "bandage"}

-- таблица настроек битв
-- Оптимизаторам: про цифры в квадратных скобках я знаю, что они лишние - написал специально, чтобы было понятнее - не убирать!
local battles = {
	marsh = {							-- территория

	--[=[ Типичный пример настройки битвы на Болотах, где используются все параметры - можно раскомментить и попробовать, будет работать)
		[1] = {							-- номер битвы на территории (для нескольких битв)
			[1]	= {						-- номер волны монстров
				dist = 70,				-- расстояние от ГГ в метрах. не задавать меньше min_good_distance
				timeout = 30,			-- время до следующей волны в секундах (радномно выбирается в интервале +-20%)
				enemy = {				-- сколько и каких монстров/неписей в волне
					["bloodsucker_normal_horror"] = 1,	-- секция, количество
					["fracture_normal_horror"] = 2,
					["dog_normal_horror"] = 2
				}
			},
			[2]	= {
				dist = 50,
				timeout = 20,
				enemy = {
					["fracture_strong_horror"] = 2,
					["zombie_immortal_horror"] = 2,
					["zombie_hell_horror"] = 2
				},
				rest = true,			-- если задано - передышка, ко времени след волны добавляется время передышки
				rukzak = true,			-- если задано - спавним тайник. должен обязательно быть задан rest иначе не сработает
				ruk_sms = 					-- если задано - после спавна рюкзака выдается смс с указанным текстом
					"%c[255,160,160,160]".."АРИАДНА:".."\\n".."%c[255,255,128,128]Вроде затихло. Где-то неподалеку должен быть резервный тайник с патронами и аптечками. Поищи его, пока затишье!",
				ruk_snd = [[sms\ariadna\ariadna_1]]	-- если задано - озвучка СМС выше
				medkit = 5,				-- если задано - количество аптечек или бинтов в тайнике (рандом от 0 до указанного)
				ammo = 1/2,				-- если задано - количество пачек патронов для оружия в активных слотах по отношению к общему количеству заспавненных монстров с момента последней передышки
				podstvol = 1/3,			-- если задано - количество снарядов для подствольника (если он есть в активных слотах) по отношению к общему количеству заспавненных монстров с момента последней передышки
				items = {				-- если задано, спавним эти предметы
					["grenade_f1_double"] = 2,		-- секция, количество
					["grenade_f1"] = 3,
					["grenade_rgd5"] = 1
				}
			},
			[3]	= {
				dist = 20,
				timeout = 30,
				enemy = {
					["bloodsucker_normal_horror"] = 1,
					["fracture_normal_horror"] = 2,
					["dog_normal_horror"] = 2,
					["peshera_xabaruch"] = 1,			-- здесь для примера прописаны друзья из пещеры)
					["peshera_stahanov"] = 1
				}
			},
			[4]	= {
				dist = 30,
				timeout = 10,			
				enemy = {
					["fracture_strong_horror"] = 2,
					["zombie_immortal_horror"] = 2,
					["zombie_hell_horror"] = 2
				}
			},
			[5]	= {
				info = "info_artmod_globus",			-- если задано - выдается этот поршень
				func = "kostya_dialog.give_ammo(2)",	-- если задано - выполняется эта функция с указанными параметрами
				tip = "Битва закончена"					-- если задано - выдается это сообщение
				tip_snd = [[sms\battle\final]]			-- если задано - озвучка СМС выше
				-- Эти параметры можно задавать в любой волне. Если написать так, как написано здесь - то эта последняя, завершающая волна не выполнит никакого спавна, а просто через время, указанное в предыдущей волне, выдастся финальный поршень и выполнится финальная функция.
			}
		},
]=]
		[2] = {
			[1] = {
                dist = 70,
                timeout = 150,
                enemy = {
					["fracture_strong"] = 1,
					["zombie_trup2"] = 1,
					["tushkano_normal"] = 3,
					["tushkano_strong"] = 3,
					["winger"] = 5,
					["zombie_hell8"] = 1
				}
			},
			[2]	= {
				dist = 60,
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 3,
					["boar_kachok"] = 1,
					["flesh_swamp"] = 1,
					["stinger"] = 5,
					["flesh_strong"] = 1
				}
			},
			[3]	= {
				dist = 70,
				enemy = {
					["zombie_babka_weak"] = 2,
					["zombie_babka_normal"] = 2,
 					["zombie_babka_strong"] = 2,
                   			["gigant_virus_strong"] = 1,
					["tushkano_normal"] = 3,
					["tushkano_strong"] = 3,
					["winger"] = 4,
					["stinger"] = 4,
 					["zombie_hell3"] = 1,
 					["zombie_hell4"] = 1,
 					["zombie_hell5"] = 1,
 					["zombie_hell6"] = 1,
 					["zombie_hell2"] = 1
				}
			}
		},
-- Akill begin
-- Охота на библиотекарей
		[31] = {
			[1]	= {
				timeout = 180
			},
			[2]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."ДЬЯК:".."\\n".."%c[255,255,128,128]Так, Меченый, мутанты прут в твою сторону. Заканчивай с минированием и бегом оттуда. Смотри, только сам не подорвись!",
				tip_snd = [[sms\diak\battle_boloto_31_2]],
			},
			[3]	= {
				dist = 70,
				timeout = 150,
				enemy = {
					["bibliotekar"] = 4
				}
			},
			[4]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["bibliotekar"] = 4,
					["bibliotekar_black"] = 1
				},
				tip = "%c[255,160,160,160]".."ДЬЯК:".."\\n".."%c[255,255,128,128]Ещё прут! Вали их из всего, что есть.",
				tip_snd = [[sms\diak\battle_boloto_31_4]],
			},
			[5]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["bibliotekar"] = 4,
					["bibliotekar_black"] = 1
				},
				tip = "%c[255,160,160,160]".."ДЬЯК:".."\\n".."%c[255,255,128,128]У тебя патроны ещё остались? Если нет, то попробуй мутантов привести к бандитам у церкви. Двух зайцев убьём сразу.",
				tip_snd = [[sms\diak\battle_boloto_31_5]],
			},
			[6]	= {
				dist = 90,
				enemy = {
					["bibliotekar"] = 1,
					["ohota_biblik1"] = 1,
					["ohota_biblik2"] = 1
				}
			}
		},
-- Ловец мутантов
		[33] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."АРНИ:".."\\n".."%c[255,255,128,128]Меченый, Коршун сообщил, что у него есть мини-ампулы, так что тащи свой особый игломёт, он его доработает.",
				tip_snd = [[sms\arni\battle_33_2]],
			},
			[3]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Я разузнал, где надыбать бутылочки со снотворным. Сколько охотникам нужно?"
			},
			[4]	= {
				tip = "%c[255,160,160,160]".."АРНИ:".."\\n".."%c[255,255,128,128]Принеси десять штук. Этого должно хватить.",
				tip_snd = [[sms\arni\battle_33_4]],
			}
		},
-- Незваные гости
		[34] = {
			[1]	= {
				timeout = 10
			},
			[2]	= {
				timeout = 60,
				tip = "%c[255,160,160,160]".."СВИБЛОВ:".."\\n".."%c[255,255,128,128]Меченый, помоги ребятам отбить атаку на наш дом. Затем выдвигайтесь в сторону хутора, постарайтесь его удержать."
			},
			[3]	= {
				timeout = 100,
				func = "akill.volna_reid_spawn()"
			},
			[4]	= {
				func = "akill.volna_reid_desant()"
			}
		},
		[35] = {
			[1]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]С севера приближаются два ударных вертолёта. Всем в укрытие!",
				tip_snd = [[sms\net\battle_boloto_35_1]],
			},
			[2]	= {
				timeout = 60,
				tip = "%c[255,160,160,160]".."СВИБЛОВ:".."\\n".."%c[255,255,128,128]Меченый, где-то в доме или возле лодки есть рюкзак с винтовкой М95. Найди его и попробуй сбить чёртовы вертушки."
			},
			[3]	= {
				func = "akill.volna_reid_heli()"
			}
		},
-- Сбежавшие, Хорь
		[36] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Кто здесь?!",
				func = "akill.hor_mistery1()"
			},
			[3]	= {
				timeout = 15,
				func = "akill.hor_mistery2()"
			},
			[4]	= {
				func = "akill.hor_mistery3()"
			}
		},
-- В обличье зверя
		[37] = {
			[1]	= {
				timeout = 6
			},
			[2]	= {
				timeout = 5,
				func = "akill.venom_dream_drink()"
			},
			[3]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Фу-у-у! Ну и гадость же! Что за дрянь мне подсунул Калмык?!"
			},
			[4]	= {
				timeout = 12,
				func = "akill.venom_dream_effect()"
			},
			[5]	= {
				info = "venom_dream_spawn"
			}
		}
	},
-- Охота на псевдособак
	l02_garbage = {	
		[30] = {
			[1]	= {
				timeout = 60
			},
			[2]	= {
				dist = 60,
				timeout = 60,
				enemy = {
					["pseudodog_strong"] = 5,
					["dog_normal"] = 5,
					["dog_zombie"] = 1,
					["dog_strong"] = 7
		 		}
			},
			[3]	= {
				dist = 50,
				enemy = {
					["ohota_dog1"] = 1,
					["ohota_dog2"] = 1,
					["dog_strong"] = 10
				}
			}
		},
-- Оборона ангара
		[31] = {
			[1]	= {
				timeout = 10
			},
			[2]	= {
				func = "akill.angar_oborona_end()"
			}
		},
-- Чужой среди своих, разговор с Прапором
		[32] = {
			[1]	= {
				timeout = 25
			},
			[2]	= {
				dist = 60,
				timeout = 40,
				enemy = {
					["dog_habaruch"] = 3,
					["dog_sil_hill"] = 2,
					["dog_skeleton"] = 5,
					["dog_strong"] = 4,
					["dog_zombie"] = 1,
					["pseudodog_big"] = 1,
					["pseudodog_strong"] = 2
		 		}
			},
			[3]	= {
				tip = "%c[255,160,160,160]".."ГРАЧ:".."\\n".."%c[255,255,128,128]Ну вот! Нам ещё кабанов с кикиморами не хватало!",
				tip_snd = [[sms\grach\battle_garbage_32_3]],
				timeout = 30,
				dist = 60,
				enemy = {
					["boar_strong"] = 4,
					["molerat"] = 4,
					["kikimora"] = 4,
					["stinger"] = 5,
					["volkodav"] = 1
				}
			},
			[4]	= {
				func = "akill.borov_peremirie()"
			}
		}
	},
-- Резервный схрон
	l11_pripyat = {
		[31] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				func = "akill.golem_npc_spawn()",
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Сталкеры, выручайте! Контролёр прижал меня в доме с гастрономом, что возле автовокзала. Пси-излучение долго не выдержу. Прошу, помогите!",
				tip_snd = [[sms\net\golem_npc_spawn]]    			
			}
		},
-- Тайник Ноя
		[32] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 70,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Опять эта чертовщина!"
			},
			[3]	= {
				timeout = 30,
				func = "akill.noi_teleport2_tp()"
			},
			[4]	= {
				timeout = 3,
				func = "akill.noi_teleport3_tp()"
			},
			[5]	= {
				timeout = 70,
				info = "volna_sak_test",
				func = "akill.sak_zvuk()"
			},
			[6]	= {
				timeout = 2,
				func = "akill.noi_teleport_end()"
			},
			[7]	= {
				timeout = 7,
				func = "akill.sak_effect()"
			},
			[8]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]И в этот раз пронесло!"
			},
			[9]	= {
				timeout = 25,
				func = "akill.taynik_noi_have()"
			},
			[10]	= {
				timeout = 17,
				tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Сталкеры, приветствую вас! Это Ной. Вы все в курсе событий, недавно произошедших на Затоне. Много наших братьев отдало жизни ради спасения всех нас. И я хотел бы увековечить их имена на памятной стеле, которую сделают по заказу и установят на Шевченко.",
				tip_snd = [[sms\noy\battle_pripyat_32_10]],
			},
			[11]	= {
				timeout = 17,
				tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]В свете всего этого я взял на себя смелость и договорился с оператором о взимании со счетов всех сталкеров небольшой суммы. Это лишь малая доля того, что мы можем сделать, чтобы почтить память павших. Надеюсь, вы не воспримите мой жест, как попытку ограбить вас. С уважением, Ной!",
				tip_snd = [[sms\noy\battle_pripyat_32_11]],
			},
			[12]	= {
				timeout = 4,
				tip = "%c[255,160,160,160]".."ОПЕРАТОР СВЯЗИ:".."\\n".."%c[255,255,128,128]С вашего счёта снята денежная сумма в размере 5 тысяч рублей.",
				tip_snd = [[sms\net\battle_pripyat_32_12]],
				},
			[13]	= {
				timeout = 10,
				func = "akill.taynik_noi_done()"
			},
			[14]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."ОБЩАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Какого хрена?! Что за байду нёс этот мужик?",
				tip_snd = [[sms\net\battle_pripyat_32_14]],
			},
			[15]	= {
				timeout = 6,
				tip = "%c[255,160,160,160]".."ОБЩАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]А ну заткнись, урод! Я друга потерял в этой бойне.",
				tip_snd = [[sms\net\battle_pripyat_32_15]],
			},
			[16]	= {
				timeout = 6,
				tip = "%c[255,160,160,160]".."ОБЩАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Пошёл ты! Попадись мне только в Зоне!",
				tip_snd = [[sms\net\battle_pripyat_32_16]],
				},
			[17]	= {
				timeout = 6,
				tip = "%c[255,160,160,160]".."ОБЩАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Буду ждать, придурок!",
				tip_snd = [[sms\net\battle_pripyat_32_17]],
			},
			[18]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."ОБЩАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Блин, последние кровные содрали! Хотел новую бритву заказать. Придётся бороду отращивать.",
				tip_snd = [[sms\net\battle_pripyat_32_18]],
				},
			[19]	= {
				tip = "%c[255,160,160,160]".."ОБЩАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Молодец, мужик! Доброе дело сделал."
			}
		},
-- Засада BW в Припяти
		[33] = {
			[1]	= {
				timeout = 4
			},
			[2]	= {
				timeout = 2,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Абсолютно! Стреляй в него!",
				tip_snd = [[sms\net\battle_pripyat_33_2]],
			},
			[3]	= {
				timeout = 2,
				func = "akill.zasada_bw_shoot()"
			},
			[4]	= {
				timeout = 1,
				func = "akill.zasada_bw_shoot_mimo()"
			},
			[5]	= {
				timeout = 2,
				func = "akill.zasada_bw_shoot_mimo()"
			},
			[6]	= {
				timeout = 2,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Чёрт подери! Ты промазал! ... Эхо-2, ликвидируйте цель!",
				tip_snd = [[sms\net\battle_pripyat_33_6]],
			},
			[7]	= {
				func = "akill.zasada_bw_spawn()"
			}
		}
	},
-- Фото Гаусс-установки
	l05_bar = {
		[30] = {
			[1]	= {
				timeout = 25
			},
			[2]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."ХРЕБЕТ:".."\\n".."%c[255,255,128,128]Меченый, твои дела с Крюком меня не волнуют, но информация о нём будет стоить тебе одной услуги.",
				tip_snd = [[sms\hrebet\battle_bar_30_2]],   			
			},
			[3]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Я почему-то в этом не сомневался."
			},
			[4]	= {
				timeout = 25,
				tip = "%c[255,160,160,160]".."ХРЕБЕТ:".."\\n".."%c[255,255,128,128]Кое-кому нужны фото секретной Гаусс-установки, что находится в бункере на Затоне. Для объёмного изображения снимки должны быть сделаны с 4-х ракурсов. Фото отдашь Долговязому, он сообщит мне о выполнении. Фотик, я думаю, ты сможешь раздобыть. Поторопись, Крюк не будет тебя долго ждать.",
				tip_snd = [[sms\hrebet\battle_bar_30_4]], 
			},
			[5]	= {
				info = "volna_foto_start"
			}
		},
-- Отдали снимки Гаусс-установки
		[31] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."ХРЕБЕТ:".."\\n".."%c[255,255,128,128]Меченый, учти, если снимки левые, то ты сильно об этом пожалеешь!",
				tip_snd = [[sms\hrebet\battle_bar_31_2]],
			},
			[3]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Не ссы, всё в ажуре! Где мне найти Крюка?"
			},
			[4]	= {
				tip = "%c[255,160,160,160]".."ХРЕБЕТ:".."\\n".."%c[255,255,128,128]Сейчас он и несколько наёмников находятся в Восточной Припяти, в КБО Юбилейный. Если отправишься сейчас же, то успеешь застать их там. Но на радушный приём не надейся!",
				tip_snd = [[sms\hrebet\battle_bar_31_4]],
			}
		},
-- Окончание расследования убийства
		[33] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				timeout = 15,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Генерал, те наёмники, что напали на ваших бойцов, причастны и к убийству Костоправа. Об этом никто не знает. По легенде дока убил Крюк, пусть так и останется, он принимал непосредственное участие."
			},
			[3]	= {
				timeout = 13,
				tip = "%c[255,160,160,160]".."ВОРОНИН:".."\\n".."%c[255,255,128,128]Сволочи! Хорошо, сделаем его козлом отпущения. Спасибо, что не проговорился о взрывчатке.",
				tip_snd = [[sms\voronin\battle_bar_33_3]],
			},
			[4]	= {
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]О чём речь! Я всё понимаю."
			}
		},
-- Опасные связи
		[35] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 12,
				func = "akill.kontrik_vodka_sms()"
			},
			[3]	= {
				timeout = 12,
				func = "akill.kontrik_vodka_zvuk()"
			},
			[4]	= {
				timeout = 15,
				func = "akill.kontrik_vodka_start()"
			},
			[5]	= {
				timeout = 6,
				info = "kontrik_vodka_start"
			},
			[6]	= {
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Что это было со мной? Будто кто-то в голову залез! Надо скорей выполнить просьбу и отвалить. Ну его на фиг, связываться с этой тайной Зоны..."
			}
		},
-- Опасные связи, продолжение
		[36] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 12,
				func = "akill.kontrik_vodka_sms2()"
			},
			[3]	= {
				timeout = 12,
				func = "akill.kontrik_vodka_zvuk()"
			},
			[4]	= {
				timeout = 17,
				func = "akill.kontrik_vodka_start()"
			},
			[5]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Интересно, кто это был? И ведь отказать не смог, как-будто он в голову залез. Жуть какая-то! Надо тоже срочно водки выпить."
			},
			[6]	= {
				func = "akill.kontrik_vodka_have()"
			}
		}
	},
-- После рейда бандитов
	l04_darkvalley = {
		[30] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				timeout = 18,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Скиталец, бандиты списали твой долг. Так ты знаешь, где раздобыть модуль-дешифратор?"
			},
			[3]	= {
				tip = "%c[255,160,160,160]".."СКИТАЛЕЦ:".."\\n".."%c[255,255,128,128]Доберись до центра фабрики Янтарь. Там получишь дальнейшие указания."
			}
		},
-- Помутнение
		[31] = {
			[1]	= {
				timeout = 7
			},
			[2]	= {
				timeout = 2,
				func = "akill.kontrik_zasada_soldier()"
			},
			[3]	= {
				timeout = 4,
				func = "akill.kontrik_vodka_zvuk()"
			},
			[4]	= {
				func = "akill.kontrik_zasada_zombied()",
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]А-а-а-а-а!!! Уйди из моей головы!!! Я больше не выдержу!!!"
			}
		},
-- Ночной дозор, комплекс
		[32] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Началось! Повыползали твари! Мочите их!",
				tip_snd = [[sms\net\battle_darkvalley_32_2]],
				func = "akill.night_watch_komplex_polter()"
			},
			[3]	= {
				timeout = 90,
				func = "akill.night_watch_komplex_polter()"
			},
			[4]	= {
				func = "akill.night_watch_borov_polter1()"
			}
		},
-- Ночной дозор, заправка
		[33] = {
			[1]	= {
				timeout = 2
			},
			[2]	= {
				timeout = 50,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Смотрите! Ползут отродья!",
				tip_snd = [[sms\net\battle_darkvalley_33_2]],
			},
			[3]	= {
				func = "akill.night_watch_borov_polter2()"
			}
		},
-- Ночной дозор, база бандитов
		[34] = {
			[1]	= {
				timeout = 4
			},
			[2]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Всем внимание! Монстры уже здесь!",
				tip_snd = [[sms\net\battle_darkvalley_34_2]],
				func = "akill.night_watch_baza_polter()"
			},
			[3]	= {
				timeout = 120,
				func = "akill.night_watch_baza_polter()"
			},
			[4]	= {
				func = "akill.night_watch_borov_polter3()"
			}
		},
-- Телохранитель
		[35] = {
			[1]	= {
				timeout = 15
			},
			[2]	= {
				timeout = 15,
				func = "akill.trofim_song()"
			},
			[3]	= {
				timeout = 30,
				dist = 41,
				enemy = {
					["molerat"] = 2
				}
			},
			[4]	= {
				timeout = 35,
				dist = 41,
				enemy = {
					["molerat"] = 2
				}
			},
			[5]	= {
				timeout = 35,
				dist = 41,
				enemy = {
					["boar_strong"] = 3
				}
			},
			[6]	= {
				timeout = 35,
				dist = 41,
				enemy = {
					["pseudodog_strong"] = 3
				}
			},
			[7]	= {
				timeout = 40,
				dist = 41,
				enemy = {
					["boar_kachok"] = 1
				}
			},
			[8]	= {
				dist = 41,
				enemy = {
					["volkodav"] = 2
				}
			}
		}
	},
-- Преследуем вояк с журналом полётов
	l03u_agr_underground = {
		[30] = {
			[1]	= {
				timeout = 8
			},
			[2]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Похоже, беглецы выбрались из подземки через другой выход. Нужно следовать за ними."
			},
			[3]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Адреналин, я в туннелях Агропрома. Как обстановка наверху, всё спокойно?"
			},
			[4]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."АДРЕНАЛИН:".."\\n".."%c[255,255,128,128]Покой нам только снится. Тут творится какая-то вакханалия! Сталкеры схлестнулись с бандитами, а потом из подземелья повылазили спецназовцы и такое началось! Советую не лезть сюда, здесь сущий ад!",
				tip_snd = [[sms\adrenalin\battle_agr_underground_30_4]],
			},
			[5]	= {
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ты же меня знаешь. Я не могу пропустить такое!"
			}
		}
	},
-- Охотник и добыча
	puzir = {
		[30] = {
			[1]	= {
				timeout = 13
			},
			[2]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ну на хер эту охоту! Самому бы не стать добычей! Пора уносить ноги!"
			},
			[3]	= {
				timeout = 7,
				func = "akill.predator_vizor()"
			},
			[4]	= {
				timeout = 2,
				func = "akill.predator_target()"
			},
			[5]	= {
				timeout = 5,
				func = "akill.predator_hit()"
			},
			[6]	= {
				timeout = 30,
				func = "akill.predator_god_spawn()"
			},
			[7]	= {
				timeout = 5,
				func = "akill.predator_god_delete()"
			},
			[8]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Вот ведь вляпался! Куда делась эта тварь?!"
			},
			[9]	= {
				timeout = 7,
				func = "akill.predator_vizor()"
			},
			[10]	= {
				timeout = 2,
				func = "akill.predator_target()"
			},
			[11]	= {
				timeout = 5,
				func = "akill.predator_hit()"
			},
			[12]	= {
				timeout = 30,
				func = "akill.predator_god_spawn()"
			},
			[13]	= {
				timeout = 6,
				func = "akill.predator_god_delete()"
			},
			[14]	= {
				timeout = 11,
				func = "akill.predator_zvuk()"
			},
			[15]	= {
				timeout = 3,
				func = "akill.predator_npc_spawn()"
			},
			[16]	= {
				timeout = 7,
				func = "akill.predator_vizor()"
			},
			[17]	= {
				timeout = 2,
				func = "akill.predator_target()"
			},
			[18]	= {
				func = "akill.predator_gauss()"
			}
		},
		[31] = {
			[1]	= {
				timeout = 18
			},
			[2]	= {
				timeout = 3,
				func = "akill.predator_bum()"
			},
			[3]	= {
				func = "akill.predator_npc_delete()"
			}
		},
-- Засада военных в ЗЛ
		[32] = {
			[1]	= {
				timeout = 4
			},
			[2]	= {
				timeout = 6,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Надо бы подслушать разговоры военных.",
				func = "akill.stop_actor()"
			},
			[3]	= {
				timeout = 15,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Сержант, испугался что ли? Ты разве не хочешь купить квартирку для своей семьи? Или твоей жене с ребёнком нравится жить в общаге? ... Молчишь? Я так и думал! Так что все заткнулись и продолжаем искать арты.",
				tip_snd = [[sms\net\battle_puzir_32_3]],
			},
			[4]	= {
				timeout = 8,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Капитан, мы здесь не одни. За нами наблюдает какой-то сталкер. Направление 315, северо-запад.",
				tip_snd = [[sms\net\battle_puzir_32_4]],
			},
			[5]	= {
				timeout = 8,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Вы, идиоты, когда научитесь пользоваться внутренним каналом связи? Под трибунал всех отдам! Окружайте его!",
				tip_snd = [[sms\net\battle_puzir_32_5]],
			},
			[6]	= {
				timeout = 2,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Вот это поворот! Пора сматываться!"
			},
			[7]	= {
				func = "akill.zasada_puzir_spawn()"
			}
		}
	},
-- Ответный удар
	l12_stancia = {
		[30] = {
			[1]	= {
				timeout = 4
			},
			[2]	= {
				timeout = 4,
				func = "akill.strike_back_bum1()",
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Что за..."
			},
			[3]	= {
				timeout = 4,
				func = "akill.strike_back_bum2()"
			},
			[4]	= {
				timeout = 4,
				func = "akill.strike_back_bum3()"
			},
			[5]	= {
				timeout = 4,
				func = "akill.strike_back_bum4()"
			},
			[6]	= {
				timeout = 4,
				func = "akill.strike_back_bum5()"
			},
			[7]	= {
				timeout = 4,
				func = "akill.strike_back_bum6()"
			},
			[8]	= {
				timeout = 15,
				func = "akill.strike_back_bum7()"
			},
			[9]	= {
				timeout = 15,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Корсар, похоже, меня ждали, это была ловушка. Нужно срочно убираться отсюда!",
				func = "akill.strike_back_zasada()"
			},
			[10]	= {
				timeout = 16,
				tip = "%c[255,160,160,160]".."КОРСАР:".."\\n".."%c[255,255,128,128]Главное, завали Цербера, но не трогай его телохранителей. Тропа на Генераторы под охраной фанатиков, так что тебе придётся выбираться через Припять.",
				tip_snd = [[sms\korsar\battle_stancia_30_10]],
				func = "akill.strike_back_end()"
			},
			[11]	= {
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Понял. Постарайся обрубить мои хвосты."
			}
		}
	},
-- Остаться в живых
	l08_yantar = {
		[30] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 13,
				func = "akill.survival_quest_sms()"
			},
			[3]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Кто это? Что это значит?"
			},
			[4]	= {
				timeout = 25,
				info = "survival_quest_start",
				func = "akill.survival_quest_start()"
			},
			[5]	= {
				timeout = 40,
				func = "akill.survival_quest_start()"
			},
			[6]	= {
				timeout = 40,
				dist = 55,
				enemy = {
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["rad_zombied_respawn_1"] = 1,
					["rad_zombied_respawn_2"] = 1,
					["rad_zombied_respawn_3"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["girl_zombied"] = 1
		 		}
			},
			[7]	= {
				timeout = 40,
				dist = 55,
				enemy = {
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["rad_zombied_respawn_1"] = 1,
					["rad_zombied_respawn_2"] = 1,
					["rad_zombied_respawn_3"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["girl_zombied1"] = 1
		 		}
			},
			[8]	= {
				timeout = 40,
				dist = 55,
				enemy = {
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["rad_zombied_respawn_1"] = 1,
					["rad_zombied_respawn_2"] = 1,
					["rad_zombied_respawn_3"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["girl_zombied2"] = 1
		 		}
			},
			[9]	= {
				timeout = 40,
				dist = 55,
				enemy = {
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["rad_zombied_respawn_1"] = 1,
					["rad_zombied_respawn_2"] = 1,
					["rad_zombied_respawn_3"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["girl_zombied3"] = 1
		 		}
			},
			[10]	= {
				timeout = 100,
				func = "akill.zombie_module_spawn()",
				dist = 55,
				enemy = {
					["yan_zombied_respawn_1"] = 1,
					["yan_zombied_respawn_2"] = 1,
					["yan_zombied_respawn_3"] = 1,
					["rad_zombied_respawn_1"] = 1,
					["rad_zombied_respawn_2"] = 1,
					["rad_zombied_respawn_3"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["zombie_plague_komar"] = 1,
					["psyonik"] = 1,
					["girl_zombied3"] = 1
		 		}
			},
			[11]	= {
				timeout = 15,
				func = "akill.survival_quest_sms2()"
			},
			[12]	= {
				timeout = 15,
				info = "survival_quest_done",
				func = "akill.survival_quest_present()"
			},
			[13]	= {
				timeout = 4,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Скиталец, когда я тебя найду, то оторву твою чёртову голову! Как всё это понимать?!"
			},
			[14]	= {
				tip = "%c[255,160,160,160]".."ОПЕРАТОР СВЯЗИ:".."\\n".."%c[255,255,128,128]ОШИБКА! Сообщение невозможно отправить. Данный аккаунт не существует.",
				tip_snd = [[sms\net\battle_yantar_30_14]], 
			}
		}
	},
-- Akill end
    jupiter = {
        [1] = {
            [1]    = {
                dist = 60,
                timeout = 75,
                enemy = {
                    ["flesh_swamp"] = 4
				}
			},
			[2]	= {
				dist = 60,
				timeout = 120,
				enemy = {
					["zombie_babka_weak"] = 2,
					["zombie_babka_normal"] = 2,
 					["zombie_babka_strong"] = 2,
 					["m_gigant_jumper_e"] = 2, 
 					["zombie_hell15"] = 1,
 					["zombie_hell3"] = 1,
 					["zombie_hell4"] = 1,
 					["zombie_hell5"] = 1,
 					["zombie_hell"] = 1,
 					["zombie_hell6"] = 1,
 					["zombie_hell2"] = 2
				}
			},
			[3]	= {
				dist = 80,
				timeout = 90,
				enemy = {
					["snork_stronger"] = 1,
					["snork_strong"] = 2,
					["snork_jumper"] = 1,
					["snork_nosach"] = 2,
					["vypolzen"] = 2,
 					["vypolzen_red"] = 2,
 					["gigant_virus_strong"] = 1,
 					["gigant_super_jumper"] = 2
				}
			},
			[4]	= {
				dist = 90,
				enemy = {
					["electro_chimera"] = 1,
					["chimera_x_ray"] = 2,
 					["chimera_wolf"] = 2,
					["chimera_weak"] = 2,
					["new_electro_chimera"] = 1,
 					["fire_chimera"] = 1,
 					["bear"] = 1,
 					["lican"] = 1,
 					["bloodsucker_hell"] = 2,
 					["gigant_super_jumper"] = 2                                                   
				}
			}
		},
-- Akill begin
-- Охота на оборотней
		[30] = {
			[1]	= {
				timeout = 100
			},
			[2]	= {
				timeout = 140,
				dist = 70,
				enemy = {
					["chimera_wolf"] = 10
		 		}
			},
			[3]	= {
				dist = 70,
				enemy = {
					["ohota_wolf1"] = 1,
					["ohota_wolf2"] = 1
				}
			}
		},
-- Сделка с наёмниками
		[31] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Акилл, едрить твою за ногу, это ты в меня стрелял?"
			},
			[3]	= {
				timeout = 30,
				tip = "%c[255,160,160,160]".."АКИЛЛ:".."\\n".."%c[255,255,128,128]С ума сошёл? Похоже, они выставили своего снайпера. Я заметил, откуда был выстрел, займусь им. А ты постарайся найти Фантома на заводе.",
				tip_snd = [[sms\akill\battle_jupiter_31_3]],
			},
			[4]	= {
				info = "mercenary_dogovor_have",
				func = "akill.mercenary_dogovor_spawn()",
				tip = "%c[255,160,160,160]".."АКИЛЛ:".."\\n".."%c[255,255,128,128]Меня серьёзно зацепило, их снайпер оказался хитрее. Дальше прикрывать не смогу. Я возвращаюсь в прачечную, встретимся там. Надеюсь, Фантом ещё жив."
			}
		},
-- Живые мертвецы
		[33] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				dist = 60,
				timeout = 60,
				enemy = {
					["zombie_immortal"] = 2,
					["zombie_hell10"] = 2,
					["zombie_hell11"] = 2,
					["zombie_hell12"] = 2,
					["zombie_hell13"] = 1,
					["zombie_hell15"] = 1,
					["zombie_hell"] = 1,
					["zombie_plague_komar"] = 1,
					["zombie_plague"] = 1,
					["zombie_ghost"] = 2
		 		}
			},
			[3]	= {
				dist = 60,
				timeout = 15,
				enemy = {
					["vodjanoj"] = 1,
					["ghoul_strong"] = 2,
					["zombie_trup2"] = 2,
					["zombie_strong"] = 2,
					["zombie_weak"] = 2,
					["girl_zombied1"] = 1,
					["girl_zombied2"] = 1,
					["pri_under_zombied1"] = 1,
					["zombie_blow"] = 1,
					["zombie_hell1"] = 1,
					["zombie_hell2"] = 2,
					["zombie_hell3"] = 2,
					["zombie_hell4"] = 2,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["rad_zombied_respawn_2"] = 1
				}
			},
			[4]	= {
				tip = "%c[255,160,160,160]".."ВАНЬКА РЫЖИЙ:".."\\n".."%c[255,255,128,128]Да у вас тут вечеринка! Не будете против, если мы присоединимся?",
				tip_snd = [[sms\battle\battle_jupiter_33_4]],
				dist = 41,
				timeout = 60,
				enemy = {
					["bar_stalker_respawn_2"] = 1,
					["gar_stalker_respawn_2"] = 1,
					["agr_stalker_regular"] = 1,
					["agr_stalker_veteran"] = 1,
					["gar_stalker_respawn_1"] =1,
					["gar_dolg_respawn_1"] = 1,
					["gar_dolg_respawn_2"] = 1,
					["bar_stalker_respawn_1"] = 1
				}
			},
			[5]	= {
				dist = 60,
				timeout = 100,
				enemy = {
					["vodjanoj"] = 1,
					["zombie_hell1"] = 2,
					["zombie_hell2"] = 2,
					["zombie_hell3"] = 2,
					["zombie_hell4"] = 2,
					["zombie_hell5"] = 2,
					["zombie_hell6"] = 2,
					["zombie_hell7"] = 2,
					["zombie_hell8"] = 2,
					["zombie_hell9"] = 1,
					["zombie_beee"] = 1,
					["zombie_hell15"] = 1,
					["zombie_plague_komar"] = 1,
					["upi_eco_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["rad_zombied_respawn_3"] = 1
				}
			},
			[6]	= {
				dist = 60,
				timeout = 20,
				enemy = {
					["zombie_hell5"] = 2,
					["zombie_hell6"] = 2,
					["zombie_hell7"] = 2,
					["zombie_hell8"] = 2,
					["zombie_hell9"] = 2,
					["zombie_weak"] = 2,
					["zombie_plague"] = 1,
					["zombie_hell13"] = 2,
					["zombie_hell12"] = 2,
					["zombie_strong"] = 2,
					["zombie_ghost"] = 2,
					["zombie_immortal"] = 1,
					["girl_zombied2"] = 1,
					["zombie_hell"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 2,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["upi_eco_zombied2"] = 1,
					["pri_under_zombied2"] = 1
				}
			},
			[7]	= {
				tip = "%c[255,160,160,160]".."СЕНЯ ХИТРЫЙ:".."\\n".."%c[255,255,128,128]Пацаны, давайте поможем сталкерам. Рассредоточьтесь по периметру.",
				tip_snd = [[sms\battle\battle_jupiter_33_7]],
				dist = 41,
				timeout = 100,
				enemy = {
					["mil_freedom_respawn_sniper"] = 1,
					["gar_stalker_respawn_2"] = 1,
					["agr_stalker_regular"] = 1,
					["agr_stalker_veteran"] = 1,
					["gar_stalker_respawn_1"] = 1,
					["mil_freedom_respawn_1"] = 1,
					["mil_freedom_respawn_2"] = 1,
					["mil_freedom_respawn_3"] = 1
				}
			},
			[8]	= {
				dist = 60,
				timeout = 100,
				enemy = {
					["vodjanoj"] = 2,
					["zombie_hell13"] = 2,
					["zombie_hell12"] = 2,
					["zombie_strong"] = 2,
					["rad_zombied_respawn_2"] = 1,
					["zombie_ghost"] = 2,
					["zombie_immortal"] = 2,
					["zombie_hell1"] = 1,
					["zombie_hell2"] = 2,
					["zombie_hell3"] = 2,
					["zombie_hell4"] = 2,
					["zombie_hell5"] = 2,
					["girl_zombied3"] = 1,
					["girl_zombied"] = 1,
					["zombie_hell15"] = 1,
					["zombie_blow"] = 1,
					["zombie_plague_komar"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["upi_eco_zombied3"] = 1,
					["pri_under_zombied3"] = 1
				}
			},
			[9]	= {
				dist = 60,
				timeout = 20,
				enemy = {
					["zombie_hell1"] = 2,
					["zombie_hell2"] = 2,
					["zombie_hell3"] = 2,
					["zombie_hell4"] = 2,
					["zombie_hell5"] = 2,
					["zombie_hell6"] = 2,
					["zombie_hell7"] = 2,
					["zombie_hell8"] = 2,
					["zombie_hell9"] = 2,
					["zombie_hell10"] = 2,
					["zombie_hell11"] = 2,
					["zombie_hell12"] = 2,
					["zombie_hell13"] = 1,
					["zombie_plague"] = 1,
					["zombie_beee"] = 1,
					["zombie_ghost"] = 2,
					["girl_zombied"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["rad_zombied_respawn_1"] = 1,
					["pri_under_zombied3"] = 1
				}
			},
			[10]	= {
				tip = "%c[255,160,160,160]".."РОМА БУЛЬДОГ:".."\\n".."%c[255,255,128,128]Лишние стволы не помешают? Ребята, доставайте свои пушки.",
				tip_snd = [[sms\battle\battle_jupiter_33_10]],
				dist = 41,
				timeout = 100,
				enemy = {
					["bar_ohotnik_respawn_1"] = 1,
					["gar_stalker_respawn_2"] = 1,
					["agr_stalker_regular"] = 1,
					["agr_stalker_veteran"] = 1,
					["gar_stalker_respawn_1"] = 1,
					["forest_nebo_regular"] = 1,
					["forest_nebo_veteran"] = 1,
					["forest_nebo_master"] = 1
				}
			},
			[11]	= {
				dist = 60,
				timeout = 100,
				enemy = {
					["zombie_hell10"] = 2,
					["zombie_hell11"] = 2,
					["zombie_hell12"] = 2,
					["zombie_hell13"] = 2,
					["zombie_ghost"] = 2,
					["zombie_immortal"] = 2,
					["zombie_strong"] = 2,
					["ghoul_strong"] = 2,
					["zombie_trup2"] = 1,
					["zombie_hell1"] = 2,
					["zombie_hell2"] = 2,
					["zombie_hell3"] = 2,
					["zombie_hell4"] = 2,
					["zombie_hell5"] = 2,
					["zombie_hell15"] = 1,
					["zombie_hell"] = 1,
					["zombie_plague_komar"] = 1,
					["upi_eco_zombied1"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["esc_arhara_stalker_zombied"] = 1,
					["esc_arhara_stalker_zombied1"] = 1,
					["rad_zombied_respawn_2"] = 2,
					["pri_under_zombied1"] = 1
				}
			},
			[12]	= {
				dist = 60,
				enemy = {
					["zombie_hell1"] = 1,
					["zombie_hell2"] = 1,
					["zombie_hell3"] = 1,
					["zombie_hell4"] = 1,
					["zombie_hell5"] = 1,
					["zombie_hell6"] = 1,
					["zombie_hell7"] = 1,
					["zombie_hell8"] = 1,
					["zombie_plague"] = 1,
					["zombie_blow"] = 1,
					["controller_senator"] = 1,
					["m_controller_act"] = 1,
					["controller_flame"] = 1,
					["ohota_zombi1"] = 1,
					["ohota_zombi2"] = 1
				}
			}
		},
-- Аномальные гранаты
		[34] = {
			[1]	= {
				timeout = 10
			},
			[2]	= {
				func = "akill.anomaly_grenade_help()"
			}
		},
-- С небес на землю
		[35] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				timeout = 30,
				func = "akill.volna_bpla_help()"
			},
			[3]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Сидорович, за разведданными идёт настоящая охота. Наёмники и монолитовцы в качестве охотников."
			},
			[4]	= {
				tip = "%c[255,160,160,160]".."СИДОРОВИЧ:".."\\n".."%c[255,255,128,128]Избавься от них. Никто не должен узнать, у кого информация с беспилотника.",
				tip_snd = [[sms\sidor\battle_jupiter_35_4]],
			}
		},
-- Кротовая нора
		[36] = {
			[1]	= {
				timeout = 90
			},
			[2]	= {
				timeout = 70,
				func = "akill.sak_tunnels_tp()"
			},
			[3]	= {
				timeout = 60,
				func = "akill.sak_monolit_tp()"
			},
			[4]	= {
				timeout = 80,
				func = "akill.sak_zvuk()",
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Что происходит? Что со мной?"
			},
			[5]	= {
				timeout = 60,
				func = "akill.sak_gigant_tp()"
			},
			[6]	= {
				timeout = 60,
				func = "akill.sak_zvuk()"
			},
			[7]	= {
				timeout = 40,
				func = "akill.sak_bolota_tp()"
			},
			[8]	= {
				timeout = 50,
				func = "akill.sak_zvuk()"
			},
			[9]	= {
				timeout = 40,
				func = "akill.sak_new_hell_tp()",
				info = "volna_sak_test"
			},
			[10]	= {
				timeout = 40,
				func = "akill.sak_zvuk()"
			},
			[11]	= {
				timeout = 100,
				func = "akill.sak_zombie_tp()"
			},
			[12]	= {
				timeout = 70,
				func = "akill.sak_biblik_tp()"
			},
			[13]	= {
				timeout = 70,
				func = "akill.sak_zvuk()"
			},
			[14]	= {
				timeout = 4,
				func = "akill.sak_polet_tp()",
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]А-а-а-а-а-а-а-а-а-а-а!"
			},
			[15]	= {
				timeout = 2,
				func = "akill.sak_kopachi_tp()"
			},
			[16]	= {
				timeout = 10,
				func = "akill.sak_effect()"
			},
			[17]	= {
				timeout = 15,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ух! Видимо, энергия у артефакта иссякла."
			},
			[18]	= {
				func = "akill.volna_sak_have()"
			}
		},
-- Перевёртыши, битва с ротанами на болоте
		[37] = {
			[1]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Что-то аномалии никакой не видать..."
			},
			[2]	= {
				timeout = 7,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Не могу сдвинуться с места... Офигеть! Вляпался как какой-нибудь неопытный новичок."
			},
			[3]	= {
				timeout = 7,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Пипец! Только рыб-мутантов и не хватало для счастья...",
				func = "akill.rotan_spawn()"
			},
			[4]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Срочно нужна помощь! Застрял на северных болотах Юпитера. Ротаны не прочь мною полакомиться. Без поддержки не выберусь. Выручайте, братцы!"
			},
			[5]	= {
				timeout = 40,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Держись, братан! Скоро будем!",
				tip_snd = [[sms\net\battle_jupiter_37_5]],
			},
			[6]	= {
				timeout = 10,
				func = "akill.rotan_spawn()"
			},
			[7]	= {
				timeout = 7,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Сталкер, ты чего это в воду к ротанам залез? Жить надоело? А ну вылазь оттуда!",
				tip_snd = [[sms\net\battle_jupiter_37_7]],
				func = "akill.rotan_help_spawn()"
			},
			[8]	= {
				timeout = 30,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Если бы я только мог... Здесь какое-то аномальное образование - ноги не двигаются. Лучше помогите отстрелять мутантов."
			},
			[9]	= {
				timeout = 60,
				func = "akill.rotan_spawn()"
			},
			[10]	= {
				timeout = 60,
				func = "akill.rotan_spawn()"
			},
			[11]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ух, кажется, пронесло! Спасибо вам, мужики! Жизнь спасли! Скиньте номера ваших счетов, перечислю немного деньжат в качестве награды."
			},
			[12]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Принимай...",
				tip_snd = [[sms\net\battle_jupiter_37_12]],
			},
			[13]	= {
				timeout = 10,
				func = "akill.ballast_delete()",
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Готово! Ещё раз спасибо... Оу! Отпустило, мужики, отпустило!"
			},
			[14]	= {
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Ага, отпустило... Накурятся всякой дряни, потом лезут купаться в воду к опасным тварям... Отпустило его! Вот, блин, даёт!",
				tip_snd = [[sms\net\battle_jupiter_37_14]],			
			}
		}
	},
-- Охота на псевдогигантов
	atp_for_test22 = {
		[30] = {
			[1]	= {
				timeout = 100
			},
			[2]	= {
				dist = 90,
				timeout = 100,
				enemy = {
					["gigant_big_strong"] = 5,
					["gigant_strong"] = 7,
					["gigant_jumper_strong"] = 2
		 		}
			},
			[3]	= {
				dist = 100,
				timeout = 120,
				enemy = {
					["gigant_big_strong"] = 5,
					["gigant_strong"] = 7,
					["gigant_red_strong"] = 2,
					["gigant_jumper_strong"] = 2
		 		}
			},
			[4]	= {
				dist = 100,
				enemy = {
					["ohota_gigant1"] = 1,
					["ohota_gigant2"] = 1
				}
			}
		}
	},
-- Трудная мишень
	red_forest = {
		[30] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				dist = 41,
				timeout = 50,
				func = "akill.volna_zahar_start()",
				enemy = {
					["ohota_snork1"] = 1
		 		}
			},
			[3]	= {
				dist = 41,
				timeout = 60,
				func = "akill.volna_zahar_start()",
				enemy = {
					["snork_weak"] = 1,
					["ohota_snork2"] = 1
		 		}
			},
			[4]	= {
				dist = 41,
				timeout = 40,
				func = "akill.volna_zahar_start()",
				info = "no_pnv",
				enemy = {
					["snork_weak"] = 1
				}
			},
			[5]	= {
				dist = 41,
				enemy = {
					["ohota_snork3"] = 1
				}
			}
		},
-- Охота на выползней
		[31] = {
			[1]	= {
				timeout = 2
			},
			[2]	= {
				timeout = 2,
				func = "akill.ohota_vypolzen_bum1()"
			},
			[3]	= {
				timeout = 6,
				func = "akill.ohota_vypolzen_bum2()"
			},
			[4]	= {
				timeout = 11,
				tip = "%c[255,160,160,160]".."СТРЕЛОК:".."\\n".."%c[255,255,128,128]Лесник, пластида оказалось недостаточно, опоры шахты выдержали взрыв. К тому же, он очень нестабилен. Меня спасло лишь то, что детонация произошла раньше."
			},
			[5]	= {
				tip = "%c[255,160,160,160]".."ЛЕСНИК:".."\\n".."%c[255,255,128,128]Это очень скверно! Э-э-э... ну в том смысле, что шахта не обрушилась... Взрывчатки у нас больше нет, так что, Стрелок, придётся тебе решить проблему по старинке - с помощью верного дробовика. Размаж по стенам эти бесовы отродья!",
				tip_snd = [[sms\lesnik\battle_red_forest_31_5]],
				info = "ohota_vypolzen_spawn"
			}
		}
	},
-- Оборона комплекса
	l03_agroprom = {
		[30] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				timeout = 80,
				func = "akill.btr_elite_spawn()"
			},
			[3]	= {
				dist = 50,
				timeout = 30,
				enemy = {
					["zasada_tonnel_agro_1"] = 1,
					["zasada_tonnel_agro_2"] = 1,
					["zasada_tonnel_agro_3"] = 1,
					["zasada_blockpost_1"] = 1,
					["zasada_blockpost_2"] = 1,
					["zasada_blockpost_3"] = 1,
					["agro_elite_soldier"] = 1
		 		}
			},
			[4]	= {
				dist = 41,
				enemy = {
					["major_lisicyn"] = 1,
					["agro_elite_sniper1"] = 1
				}
			}
		},
-- Охота на грызунов
		[31] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				dist = 60,
				timeout = 55,
				enemy = {
					["winger"] = 5,
					["tushkano_normal"] = 10,
					["tushkano_strong"] = 8
		 		}
			},
			[3]	= {
				dist = 60,
				timeout = 55,
				enemy = {
					["ohota_tushkan2"] = 1,
					["winger"] = 5,
					["tushkano_normal"] = 10,
					["tushkano_strong"] = 8
		 		}
			},
			[4]	= {
				dist = 60,
				timeout = 60,
				enemy = {
					["winger"] = 5,
					["tushkano_normal"] = 10,
					["tushkano_strong"] = 8
		 		}
			},
			[5]	= {
				dist = 60,
				timeout = 60,
				enemy = {
					["winger"] = 5,
					["tushkano_normal"] = 10,
					["tushkano_strong"] = 8
		 		}
			},
			[6]	= {
				dist = 60,
				enemy = {
					["ohota_tushkan3"] = 1,
					["tushkano_normal"] = 1
		 		}
			}
		},
-- Огневая поддержка, ликвидация цели
		[32] = {
			[1]	= {
				timeout = 7
			},
			[2]	= {
				timeout = 9,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]И как часто твой \"приятель\" выходит покурить?"
			},
			[3]	= {
				timeout = 9,
				tip = "%c[255,160,160,160]".."ВАРГ:".."\\n".."%c[255,255,128,128]Примерно каждый час, но бывает и реже.",
				tip_snd = [[sms\varg\battle_agroprom_32_3]],
			},
			[4]	= {
				timeout = 6,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Так, внимание! Солдат в зоне видимости..."
			},
			[5]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."ВАРГ:".."\\n".."%c[255,255,128,128]Это наш \"клиент\"! Работаем!",
				tip_snd = [[sms\varg\battle_agroprom_32_5]],
			},
			[6]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]С чего ты взял? И почему он в форме?"
			},
			[7]	= {
				timeout = 11,
				tip = "%c[255,160,160,160]".."ВАРГ:".."\\n".."%c[255,255,128,128]Человек на крыше, как и наша цель, левша! К тому же, этот крендель носит берет с наклоном не в ту сторону, как принято в спецназе. Маскировка дилетанта!",
				tip_snd = [[sms\varg\battle_agroprom_32_7]],
			},
			[8]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."ВАРГ:".."\\n".."%c[255,255,128,128]Вот гадёныш! Решил устроить сюрприз - в этой части крыши он никогда не курил... Дистанция?",
				tip_snd = [[sms\varg\battle_agroprom_32_8]],
			},
			[9]	= {
				timeout = 8,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]210 метров... Стреляй по готовности..."
			},
			[10]	= {
				timeout = 4,
				func = "akill.varg_target_hit()"
			},
			[11]	= {
				timeout = 4,
				tip = "%c[255,160,160,160]".."ВАРГ:".."\\n".."%c[255,255,128,128]Цель нейтрализована?",
				tip_snd = [[sms\varg\battle_agroprom_32_11]],
			},
			[12]	= {
				timeout = 6,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Подтверждаю. Предатель ликвидирован, дело сделано!"
			},
			[13]	= {
				timeout = 15,
				func = "akill.varg_patrol1()",
				tip = "%c[255,160,160,160]".."ВАРГ:".."\\n".."%c[255,255,128,128]Рано радоваться... Сюда приближается патруль, видимо, они слышали выстрел. Спустись в мансарду и прикрывай меня.",
				tip_snd = [[sms\varg\battle_agroprom_32_13]],
			},
			[14]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."ВАРГ:".."\\n".."%c[255,255,128,128]Проклятье! Похоже, мы разворошили осиное гнездо! Спецназ собирается взять комплекс в кольцо... Переходим к плану \"Б\"... Как только избавишься от солдат, взорви БТР с помощью \"Шмеля\" и дуй на вышку. Я тем временем постараюсь повредить остальные БТРы и уменьшу число преследователей, иначе живыми мы отсюда не выберемся.",
				tip_snd = [[sms\varg\battle_agroprom_32_14]],
			},
			[15]	= {
				func = "akill.varg_patrol2()"
			}
		},
-- Не находим журнал полётов
		[33] = {
			[1]	= {
				timeout = 3
			},
			[2]	= {
				timeout = 11,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Аким, я на военной базе. Здесь нет никакого журнала, сейф вскрыт и пуст."
			},
			[3]	= {
				timeout = 11,
				tip = "%c[255,160,160,160]".."АКИМ:".."\\n".."%c[255,255,128,128]А ты никого не упустил? С базы нельзя выбраться скрытным путём?"
			},
			[4]	= {
				timeout = 11,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Под комплексом находятся старые туннели. Возможно, солдаты спустились туда, прихватив с собой секретные документы."
			},
			[5]	= {
				tip = "%c[255,160,160,160]".."АКИМ:".."\\n".."%c[255,255,128,128]Значит твой путь лежит в катакомбы. Ты должен заполучить журнал любым способом. Действуй!"
			}
		},
-- Огневая поддержка, прикрываем Варга
		[34] = {
			[1]	= {
				timeout = 9
			},
			[2]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Уф! ... Я на позиции... Солдаты уже близко, ещё немного и ты окажешься в ловушке. Беги оттуда со всех ног, скорее!"
			},
			[3]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."ВАРГ:".."\\n".."%c[255,255,128,128]Принято, выдвигаюсь! Целься в голову и как можно точнее, этих спецов, похоже, пули боятся.",
				tip_snd = [[sms\varg\battle_agroprom_34_3]],
			},
			[4]	= {
				timeout = 80,
				func = "akill.varg_soldier1()"
			},
			[5]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Да скорей же! Бабка бюрера и та бегает быстрее!"
			},
			[6]	= {
				timeout = 15,
				tip = "%c[255,160,160,160]".."ВАРГ:".."\\n".."%c[255,255,128,128]Уф-уф-уф! Охотно верю! ... Ты не отвлекайся! Лучше сосредоточь огонь на тех, кто за моей спиной.",
				tip_snd = [[sms\varg\battle_agroprom_34_6]],
			},
			[7]	= {
				func = "akill.varg_soldier2()"
			}
		}
	},
-- В западне
	pripyat = {
		[30] = {
			[1]	= {
				timeout = 70
			},
			[2]	= {
				dist = 50,
				timeout = 40,
				enemy = {
					["bw_killers1"] = 2,
					["bw_killers2"] = 1
		 		}
			},
			[3]	= {
				dist = 60,
				enemy = {
					["bw_killers6"] = 1
				}
			}
		},
-- Находим Крюка
		[31] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 1,
				func = "akill.kruk_vystrel()"
			},
			[3]	= {
				timeout = 3,
				func = "akill.kruk_ranen()"
			},
			[4]	= {
				timeout = 3,
				func = "akill.kruk_vystrel()"
			},
			[5]	= {
				timeout = 15,
				func = "akill.kruk_vystrel()"
			},
			[6]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Бармен, убийца Костоправа поплатился за содеянное. Детали расскажу позже... Если выберусь отсюда!"
			},
			[7]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."БАРМЕН:".."\\n".."%c[255,255,128,128]Значит вопрос решён! Постарайся остаться в живых, я хочу знать подробности."
			},
			[8]	= {
				func = "akill.kruk_merki()",
				info = "volna_barmen_have"
			}
		},
-- Старая икона
		[32] = {
			[1]	= {
				timeout = 10
			},
			[2]	= {
				timeout = 70,
				func = "akill.volna_petrenko_spawn()"
			},
			[3]	= {
				dist = 65,
				enemy = {
					["zombie_hell3"] = 1,
					["zombie_hell4"] = 1,
					["zombie_hell5"] = 1,
					["zombie_hell6"] = 1,
					["zombie_hell15"] = 1,
					["girl_zombied1"] = 1,
					["girl_zombied2"] = 1,
					["zombie_babka_strong"] = 1,
					["zombie_hell"] = 1,
					["zombie_beee"] = 1,
					["zombie_hell12"] = 1
		 		}
			}
		},
-- Печатная машинка
		[33] = {
			[1]	= {
				timeout = 15
			},
			[2]	= {
				timeout = 150,
				func = "akill.ziklop_mashinka_mutant()"
			},
			[3]	= {
				timeout = 13,
				func = "akill.ziklop_mashinka_end()"
			},
			[4]	= {
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ох, ну и сильные же контролёры попались! Чуть мозги не вскипели!"
			}
		}
	},
-- Тайна Скряги
	l07_military = {
		[30] = {
			[1]	= {
				timeout = 40
			},
			[2]	= {
				func = "arhara_dialog.vrag_zombie(actor, npc)"
			}
		},
-- Подготовка на Затоне завершена
		[31] = {
			[1]	= {
				timeout = 13
			},
			[2]	= {
				timeout = 19,
				tip = "%c[255,160,160,160]".."ВАСИЛИЙ:".."\\n".."%c[255,255,128,128]Меченый, я понял, как военная разведка нашла базу Чистого Неба. При ремонте прототипа армейского бронекостюма я выкинул из него кое-какие лишние детали. В частности, подсумок для документов и карт. В нём был спрятан работающий маячок. Я наткнулся на него только сейчас, когда разгребал свою мастерскую после визита десанта, и всё это время он пеленговал. Маячок я уничтожил.",
				tip_snd = [[sms\vasiliy\battle_military_31_2]],
			},
			[3]	= {
				timeout = 20,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Болван ты, Василий! Сдать бы тебя Свиблову, только получается, что и я причастен к нападению вояк. Держи рот на замке, это в твоих же интересах."
			},
			[4]	= {
				timeout = 16,
				tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Профессор Круглов сообщил, что в двух километрах от нас засёк огромное количество мутантов. Ты должен срочно прибыть на Шевченко.",
				tip_snd = [[sms\noy\battle_military_31_4]],
			},
			[5]	= {
				timeout = 16,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Оружие и боеприпасы подвезли?"
			},
			[6]	= {
				tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Да, вертолёты прибыли час назад. Мы разгрузили ящики, отряд Свободы помог нам. Бочки и баллоны расставлены вокруг Шевченко. Будешь приближаться - не стреляй в ту сторону. Поторопись!",
				tip_snd = [[sms\noy\battle_military_31_6]],
			}
		},
-- Дом духов
		[32] = {
			[1]	= {
				timeout = 85
			},
			[2]	= {
				timeout = 90,
				func = "akill.ohota_polter_battle1()"
			},
			[3]	= {
				timeout = 90,
				func = "akill.ohota_polter_battle2()"
			},
			[4]	= {
				timeout = 90,
				func = "akill.ohota_polter_battle3()"
			},
			[5]	= {
				func = "akill.ohota_polter_battle4()"
			}
		},
-- Из огня да в полымя
		[33] = {
			[1]	= {
				timeout = 40
			},
			[2]	= {
				timeout = 4,
				tip = "%c[255,160,160,160]".."СЛЕДОПЫТ:".."\\n".."%c[255,255,128,128]Ой!",
				tip_snd = [[sms\sledopyt\battle_military_33_2]],
			},
			[3]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Что-то мне не нравится это \"Ой!\"."
			},
			[4]	= {
				timeout = 6,
				tip = "%c[255,160,160,160]".."СЛЕДОПЫТ:".."\\n".."%c[255,255,128,128]Я случайно замкнул один из проводов, и на бомбе запустился таймер.",
				tip_snd = [[sms\sledopyt\battle_military_33_4]],
			},
			[5]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Вот дурья башка! И сколько у нас времени?"
			},
			[6]	= {
				timeout = 6,
				tip = "%c[255,160,160,160]".."СЛЕДОПЫТ:".."\\n".."%c[255,255,128,128]Меньше трёх минут! Боюсь, мне не успеть обезвредить её!",
				tip_snd = [[sms\sledopyt\battle_military_33_6]],
			},
			[7]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Не трать время на болтовню! Сосредоточься на бомбе! У тебя всё получится!"
			},
			[8]	= {
				timeout = 50,
				func = "akill.sledopyt_bomba_bw1()"
			},
			[9]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Скорей же! Наймы жмут со всех сторон!"
			},
			[10]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."СЛЕДОПЫТ:".."\\n".."%c[255,255,128,128]Секунду... Какой твой любимый цвет?",
				tip_snd = [[sms\sledopyt\battle_military_33_10]],
			},
			[11]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Что? Ты о чём?"
			},
			[12]	= {
				timeout = 7,
				tip = "%c[255,160,160,160]".."СЛЕДОПЫТ:".."\\n".."%c[255,255,128,128]К таймеру подведены два провода - красный и синий. Какой из них резать?",
				tip_snd = [[sms\sledopyt\battle_military_33_12]],
			},
			[13]	= {
				timeout = 4,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Режь синий!"
			},
			[14]	= {
				timeout = 4,
				tip = "%c[255,160,160,160]".."СЛЕДОПЫТ:".."\\n".."%c[255,255,128,128]А может красный?",
				tip_snd = [[sms\sledopyt\battle_military_33_14]],
			},
			[15]	= {
				timeout = 4,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ну режь красный!"
			},
			[16]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."СЛЕДОПЫТ:".."\\n".."%c[255,255,128,128]Осталось 30 секунд. Так какой всё-таки резать?",
				tip_snd = [[sms\sledopyt\battle_military_33_16]],
			},
			[17]	= {
				timeout = 4,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Режь оба!!!"
			},
			[18]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."СЛЕДОПЫТ:".."\\n".."%c[255,255,128,128]Сдурел?! Это приведёт к детонации!",
				tip_snd = [[sms\sledopyt\battle_military_33_18]],
			},
			[19]	= {
				timeout = 7,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Поверь моему чутью! Оно меня никогда не подводит! Режь оба провода!"
			},
			[20]	= {
				timeout = 6,
				tip = "%c[255,160,160,160]".."СЛЕДОПЫТ:".."\\n".."%c[255,255,128,128]Твоему чутью? Ты только что два раза поменял своё мнение!",
				tip_snd = [[sms\sledopyt\battle_military_33_20]],
			},
			[21]	= {
				timeout = 6,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Млять! Отрежь уже что-нибудь!"
			},
			[22]	= {
				timeout = 7,
				func = "akill.sledopyt_bomba_bw2()",
				tip = "%c[255,160,160,160]".."СЛЕДОПЫТ:".."\\n".."%c[255,255,128,128]Фуууух! Отрезал! ... Таймер остановился, датчик движения отключён!",
				tip_snd = [[sms\sledopyt\battle_military_33_22]],
			},
			[23]	= {
				timeout = 7,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Пора выбираться отсюда! Беги на стоянку сталкеров, я прикрою."
			},
			[24]	= {
				info = "sledopyt_bomba_have"
			}
		}
	},
-- Берём Хостел-телепорт
	zaton = {
		[30] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				dist = 60,
				timeout = 50,
				enemy = {
					["zombie_immortal"] = 1,
					["new_electro_chimera"] = 1,
					["fire_chimera"] = 1,
					["chimera_x_ray"] = 1,
					["chimera_black"] = 1,
 					["bear"] = 1,
					["zombie_babka_strong"] = 1,
					["zombie_ghost"] = 1,
					["girl_zombied"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["zombie_hell1"] = 1,
					["zombie_hell2"] = 1,
					["zombie_hell10"] = 1,
					["zombie_plague"] = 1,
					["zombie_plague_komar"] = 1,
					["zombie_beee"] = 1,
					["m_poltergeist_dd"] = 1,
					["electro_polter"] = 1,
					["polter_xray"] = 1,
					["poltergeist_build"] = 1,
					["psyonik"] = 1,
					["zombie_strong"] = 1
		 		}
			},
			[3]	= {
				dist = 60,
				timeout = 50,
				enemy = {
					["vodjanoj"] = 1,
					["zombie_hell3"] = 1,
					["zombie_hell4"] = 1,
					["zombie_hell5"] = 1,
					["zombie_hell6"] = 1,
					["zombie_hell7"] = 1,
					["zombie_hell15"] = 1,
					["girl_zombied1"] = 1,
					["girl_zombied2"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["zombie_babka_strong"] = 1,
					["zombie_ghost"] = 1,
					["zombie_hell"] = 1,
					["zombie_blow"] = 1,
					["zombie_beee"] = 1,
					["zombie_immortal"] = 1,
					["m_poltergeist_dd"] = 1,
					["electro_polter"] = 1,
					["polter_xray"] = 1,
					["poltergeist_build"] = 1,
					["psyonik"] = 1,
					["zombie_hell12"] = 1
				}
			},
			[4]	= {
				dist = 60,
				timeout = 70,
				enemy = {
					["vodjanoj"] = 1,
					["zombie_hell8"] = 1,
					["zombie_hell9"] = 1,
					["zombie_immortal"] = 1,
					["zombie_ghost"] = 1,
					["zombie_hell10"] = 1,
					["zombie_hell11"] = 1,
					["zombie_hell7"] = 1,
					["zombie_hell15"] = 1,
					["zombie_plague"] = 1,
					["zombie_blow"] = 1,
					["zombie_beee"] = 1,
					["zombie_hell"] = 1,
					["zombie_plague_komar"] = 1,
					["girl_zombied2"] = 1,
					["girl_zombied3"] = 1,
					["voen_zombied1"] = 1,
					["voen_zombied2"] = 1,
					["m_poltergeist_dd"] = 1,
					["electro_polter"] = 1,
					["polter_xray"] = 1,
					["psyonik"] = 1,
					["zombie_hell13"] = 1
				}
			},
			[5]	= {
				func = "akill.chertez_inferno_spawn()"
			}
		},
-- Доводы Ноя
		[32] = {
			[1]	= {
				timeout = 30
			},
			[2]	= {
				dist = 70,
				timeout = 90,
				enemy = {
					["boar_strong"] = 2,
					["boar_kachok"] = 2,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 2,
					["molerat"] = 3,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 1,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[3]	= {
				dist = 70,
				timeout = 90,
				enemy = {
					["dog_habaruch"] = 3,
					["dog_sil_hill"] = 3,
					["dog_skeleton"] = 4,
					["dog_green"] = 3,
					["dog_strong"] = 3,
					["dog_zombie"] = 3,
					["volkodav"] = 2,
					["pseudodog_big"] = 2,
					["pseudodog_strong"] = 3
				}
			},
			[4]	= {
				dist = 70,
				timeout = 90,
				enemy = {
					["cat_strong"] = 2,
					["cat_normal"] = 2,
					["cat_weak"] = 2,
					["psy_dog"] = 1,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["vypolzen_red"] = 2,
					["vypolzen"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["volkodav"] = 1,
					["pseudodog_big"] = 1,
					["pseudodog_strong"] = 2
				}
			},
			[5]	= {
				dist = 70,
				timeout = 80,
				enemy = {
					["bloodsucker_effector"] = 1,
					["oboroten"] = 2,
					["stinger"] = 5,
					["gigant_jumper_strong"] = 2,
					["gigant_big_strong"] = 2
				}
			},
			[6]	= {
				dist = 70,
				timeout = 80,
				enemy = {
					["deathclaw_normal"] = 1,
					["deathclaw_weak"] = 1,
					["deathclaw_strong"] = 1,
					["new_hell"] = 1,
 					["bear"] = 1,
 					["lican"] = 2,
					["chimera_normal"] = 2
				}
			},
			[7]	= {
				dist = 70,
				timeout = 90,
				enemy = {
					["electro_chimera"] = 1,
					["chimera_x_ray"] = 1,
					["chimera_wolf"] = 1,
					["new_electro_chimera"] = 1,
					["fire_chimera"] = 1,
					["chimera_black"] = 1,
					["chimera_strong"] = 1
				}
			},
			[8]	= {
				dist = 70,
				timeout = 90,
				enemy = {
					["fracture_normal"] = 3,
					["karlito"] = 2,
					["psyonik"] = 1,
					["bibliotekar"] = 2,
					["bibliotekar_black"] = 2,
					["snork_stronger"] = 2
				}
			},
			[9]	= {
				dist = 70,
				enemy = {
					["kontrik_yantar1"] = 1,
					["kontrik_yantar2"] = 1,
					["poltergeist_build"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["m_controller_act"] = 1,
					["controller_flame"] = 1,
					["kontrik_labx16"] = 1
				}
			}
		},
-- Подготовка к волне
		[33] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 17,
				tip = "%c[255,160,160,160]".."ОБЩАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Сталкеры, это Ной. Я нашёл человека, способного повести нас за собой. Ему, как и мне, предначертано спасти всех нас от волны мутантов. Запомните это имя - Меченый.",
				tip_snd = [[sms\noy\battle_zaton_33_2]],
			},
			[3]	= {
				timeout = 12,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Арни, разыщи Коршуна. Передай ему, что у него есть уникальная возможность открыть свой зоопарк из редких мутантов, но придётся изрядно пострелять. Спроси его, что он хочет за свою помощь."
			},
			[4]	= {
				timeout = 17,
				tip = "%c[255,160,160,160]".."АРНИ:".."\\n".."%c[255,255,128,128]Понял, сейчас же отправлю ему сообщение. За ответом приходи ко мне, потолкуем.",
				tip_snd = [[sms\arni\battle_zaton_33_4]], 			
			},
			[5]	= {
				timeout = 12,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Адреналин, ты можешь связаться с Седым, торговцем на вертушке? Нужен его транспорт для перевозки боеприпасов на Затон и вывоза сталкеров оттуда. Узнай, сколько он хочет за свои услуги."
			},
			[6]	= {
				timeout = 12,
				tip = "%c[255,160,160,160]".."АДРЕНАЛИН:".."\\n".."%c[255,255,128,128]Хорошо. Ты что там задумал? Очередную маленькую войну?",
				tip_snd = [[sms\adrenalin\battle_zaton_33_6]],
			},
			[7]	= {
				timeout = 30,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Узнаешь при встрече. Я к тебе ещё загляну."
			},
			[8]	= {
				tip = "%c[255,160,160,160]".."БАСТИ:".."\\n".."%c[255,255,128,128]Эй, Меченый, подойди-ка. А то промчался как метеор, ни тебе здрасьте, ни до свиданья!",
				tip_snd = [[sms\buusty\battle_zaton_33_8]],
			}
		},
-- Секунды до смерти
		[34] = {
			[1]	= {
				timeout = 400
			},
			[2]	= {
				func = "akill.saper_code_fail()"
			}
		},
-- Встреча с Blackwater
		[35] = {
			[1]	= {
				timeout = 20
			},
			[2]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Акилл, угадай, кого я сегодня встретил. Наших старых друзей из Блэквотер. Эти черти никак не угомонятся."
			},
			[3]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."АКИЛЛ:".."\\n".."%c[255,255,128,128]У тебя талант находить неприятности. Тебе никто об этом не говорил? Что им нужно?",
				tip_snd = [[sms\akill\battle_zaton_35_3]],
			},
			[4]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Как всегда, прототипы ЭМ-оружия. На ближайшее время отмени прогулки по Затону."
			},
			[5]	= {
				tip = "%c[255,160,160,160]".."АКИЛЛ:".."\\n".."%c[255,255,128,128]Учту это. До встречи!",
				tip_snd = [[sms\akill\battle_zaton_35_5]],
			}
		},
-- Волна: день нулевой
		[36] = {
			[1]	= {
				timeout = 6
			},
			[2]	= {
				timeout = 45,
				func = "akill.volna_day0_spawn()",
				tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]Меченый, на юго-западе, в 70 метрах от Шевченко обнаружено около двух дюжин химер. Быстро приближаются.",
				tip_snd = [[sms\kruglov\battle_zaton_36_2]],
			},
			[3]	= {
				func = "akill.volna_day0_spawn()"
			}
		},
-- Волна: день первый
		[37] = {
			[1]	= {
				info = "volna_goodwill",
				timeout = 9
			},
			[2]	= {
				timeout = 17,
				func = "akill.volna_day1_sound()",
				tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]Меченый, с юга движется большое число мутантов. Впервые регистрирую такое количество! На мониторе одно сплошное пятно из меток. Будут у вас через восемь минут. Что бы там не происходило, желаю вам выбраться оттуда живым!",
				tip_snd = [[sms\kruglov\battle_zaton_37_2]],
			},
			[3]	= {
				timeout = 15,
				tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Сталкеры, братья, я не обладаю талантом произносить ободряющие речи, но хочу сказать вот что.",
				tip_snd = [[sms\noy\battle_zaton_37_3]],
			},
			[4]	= {
				timeout = 15,
				tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Мне неизвестно, как закончится сегодняшний день, и увидим ли мы закат солнца... Нас не так уж много, а наши шансы выжить ещё меньше."
			},
			[5]	= {
				timeout = 450,
				tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Но я знаю одно! То, что вы находитесь сейчас здесь, рядом со мной, говорит о том, что люди не утратили веры в будущее, веры в друг друга, веры в самих себя! Это даёт нам преимущество над любым врагом! Запомните это!"
			},
			[6]	= {
				timeout = 15,
				func = "akill.volna_day1_dogs()"
			},
			[7]	= {
				timeout = 80,
				func = "akill.volna_day1_dogs()"
			},
			[8]	= {
				timeout = 80,
				info = "noi_defenders_otboi",
				func = "akill.volna_day1_boars()"
			},
			[9]	= {
				timeout = 80,
				func = "akill.volna_day1_boars()"
			},
			[10]	= {
				timeout = 80,
				func = "akill.volna_day1_dogs()"
			},
			[11]	= {
				timeout = 80,
				func = "akill.volna_day1_dogs()"
			},
			[12]	= {
				dist = 95,
				timeout = 140,
				enemy = {
					["boar_strong"] = 5,
					["boar_kachok"] = 5,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["rotan"] = 4,
					["kikimora"] = 3,
					["molerat"] = 3,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[13]	= {
				dist = 95,
				timeout = 140,
				enemy = {
					["boar_strong"] = 4,
					["boar_kachok"] = 4,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["rotan"] = 4,
					["kikimora"] = 4,
					["molerat"] = 4,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[14]	= {
				dist = 95,
				timeout = 90,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["volkodav"] = 2,
					["psy_dog"] = 1,
					["pseudodog_strong"] = 5
				}
			},
			[15]	= {
				dist = 95,
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 3,
					["stinger"] = 5,
					["volkodav"] = 2,
					["pseudodog_big"] = 3,
					["pseudodog_strong"] = 3
				}
			},
			[16]	= {
				ruk_sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Я скинул рюкзак с припасами, рядом с тобой.",
				ruk_snd = [[sms\lovkach\battle_zaton_16_1]],
				rest = true,
				rukzak = true,
				timeout = 50,
				items = {
					["medkit"] = 4,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 3
				}
			},
			[17]	= {
				dist = 90,
				timeout = 30,
				enemy = {
					["cat_strong"] = 3,
					["cat_normal"] = 3,
					["cat_weak"] = 4,
					["snork_strong"] = 4,
					["snork_stronger"] = 1,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["fracture_karlik"] = 5
				}
			},
			[18]	= {
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Это Свобода. Почему без нас начали?",
				tip_snd = [[sms\net\battle_zaton_37_18]],
				dist = 60,
				timeout = 10,
				enemy = {
					["freedom_volna"] = 3
				}
			},
			[19]	= {
				dist = 60,
				timeout = 50,
				enemy = {
					["freedom_volna"] = 3
				}
			},
			[20]	= {
				dist = 100,
				timeout = 160,
				enemy = {
					["cat_strong"] = 3,
					["cat_normal"] = 4,
					["cat_weak"] = 3,
					["snork_strong"] = 2,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["gigant_strong"] = 2
				}
			},
			[21]	= {
				dist = 100,
				timeout = 120,
				enemy = {
					["cat_strong"] = 5,
					["cat_normal"] = 4,
					["cat_weak"] = 4,
					["snork_strong"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["vypolzen"] = 4,
					["vypolzen_red"] = 4,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["fracture_karlik"] = 6
				}
			},
			[22]	= {
				dist = 95,
				timeout = 140,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 3,
					["chimera_wolf"] = 3,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 2,
					["bloodsucker_effector"] = 1,
					["oboroten"] = 1,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1
				}
			},
			[23]	= {
				dist = 100,
				timeout = 160,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 3,
					["bloodsucker_mil"] = 1,
					["oboroten"] = 1,
 					["bear"] = 2,
 					["lican"] = 2,
					["bloodsucker_strong"] = 3,
					["bloodsucker_child"] = 2
				}
			},
			[24]	= {
				dist = 100,
				timeout = 160,
				enemy = {
					["electro_chimera"] = 6,
					["chimera_x_ray"] = 6,
					["chimera_wolf"] = 6,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 4,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["chimera_strong"] = 4
				}
			},
			[25]	= {
				dist = 100,
				timeout = 160,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 5,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 3,
 					["bear"] = 2,
 					["lican"] = 2,
					["bloodsucker_hell"] = 1
				}
			},
			[26]	= {
				ruk_sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Оглядись, патроны в рюкзаке.",
				ruk_snd = [[sms\lovkach\battle_zaton_26_1]],
				rest = true,
				rukzak = true,
				timeout = 70,
				items = {
					["medkit_army"] = 4,
					["ammo_23x76_shrap"] = 2,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 4
				}
			},
			[27]	= {
				dist = 90,
				timeout = 30,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 3,
					["gigant_red_strong"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[28]	= {
				dist = 60,
				timeout = 15,
				enemy = {
					["freedom_volna"] = 3
				}
			},
			[29]	= {
				dist = 60,
				timeout = 80,
				enemy = {
					["freedom_volna"] = 3
				}
			},
			[30]	= {
				dist = 90,
				timeout = 150,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 10,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 2
				}
			},
			[31]	= {
				dist = 95,
				timeout = 150,
				enemy = {
					["electro_chimera"] = 4,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 3,
 					["bear"] = 2,
 					["lican"] = 4,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["bloodsucker_hell"] = 2
				}
			},
			[32]	= {
				dist = 90,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 10,
					["gigant_jumper_strong"] = 3,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["deathclaw_weak"] = 3,
					["deathclaw_normal"] = 3
				}
			},
			[33]	= {
				dist = 100,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 3,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["deathclaw_strong"] = 3
				}
			},
			[34]	= {
				dist = 100,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["fracture_karlik"] = 4,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["new_hell"] = 1
				}
			},
			[35]	= {
				ruk_sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Смотри под ноги, маслята принёс.",
				ruk_snd = [[sms\lovkach\battle_zaton_35_1]],
				rest = true,
				rukzak = true,
				timeout = 70,
				items = {
					["medkit_scientic"] = 5,
					["ammo_balon"] = 4,
					["ammo_23x76_shrap"] = 3,
					["ammo_12.7x108r"] = 4,
					["ammo_minigun"] = 6
				}
			},
			[36]	= {
				dist = 100,
				timeout = 30,
				enemy = {
					["bloodsucker_hell"] = 3,
					["bibliotekar"] = 2,
					["bibliotekar_black"] = 2,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 3,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 3
				}
			},
			[37]	= {
				dist = 60,
				timeout = 200,
				enemy = {
					["freedom_volna"] = 5
				}
			},
			[38]	= {
				dist = 100,
				timeout = 200,
				enemy = {
					["bloodsucker_hell"] = 2,
					["oboroten"] = 2,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 2,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[39]	= {
				dist = 100,
				timeout = 200,
				enemy = {
					["kontrik_yantar1"] = 1,
					["bibliotekar"] = 2,
					["bibliotekar_black"] = 1,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 3,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 2
				}
			},
			[40]	= {
				dist = 90,
				timeout = 180,
				enemy = {
					["deathclaw_strong"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_weak"] = 2,
					["new_hell"] = 2,
					["vypolzen"] = 8,
					["vypolzen_red"] = 8,
					["snork_stronger"] = 4,
					["snork_jumper"] = 5,
					["snork_nosach"] = 4,
					["snork_strong"] = 5
				}
			},
			[41]	= {
				dist = 100,
				timeout = 200,
				enemy = {
					["new_hell"] = 5,
					["deathclaw_normal"] = 2,
					["deathclaw_weak"] = 2,
					["deathclaw_strong"] = 2,
					["bloodsucker_hell"] = 5,
					["oboroten"] = 3,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 4,
					["bloodsucker_effector"] = 5,
					["bloodsucker_strong"] = 5
				}
			},
			[42]	= {
				dist = 90,
				timeout = 30,
				enemy = {
					["bibliotekar"] = 2,
					["bibliotekar_black"] = 1,
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1,
					["gigant_strong"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["karlito"] = 1,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["new_electro_chimera"] = 1,
					["fire_chimera"] = 1,
					["chimera_normal"] = 2,
					["chimera_strong"] = 1,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 1,
 					["lican"] = 1,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 2
				}
			},
			[43]	= {
				dist = 60,
				timeout = 200,
				enemy = {
					["freedom_volna"] = 5
				}
			},
			[44]	= {
				dist = 90,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 1,
					["bibliotekar_black"] = 1,
					["gigant_big_strong"] = 1,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 2,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2
				}
			},
			[45]	= {
				dist = 90,
				timeout = 220,
				enemy = {
					["bibliotekar"] = 4,
					["bibliotekar_black"] = 2,
					["kontrik_yantar2"] = 1,
					["kontrik_labx16"] = 1,
					["controller_babka"] = 1,
					["m_controller_act"] = 1,
					["controller_flame"] = 1,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_big_strong"] = 1,
					["fracture_master"] = 4,
					["fracture_karlik"] = 4,
					["deathclaw_strong"] = 1,
					["deathclaw_weak"] = 1,
					["deathclaw_normal"] = 1,
					["vypolzen"] = 5,
					["vypolzen_red"] = 5,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 2
				}
			},
			[46]	= {
				dist = 70,
				enemy = {
					["kontrik_senator"] = 1
				}
	    	}
		},
-- Волна: день первый окончен
		[38] = {
			[1]	= {
				timeout = 7
			},
			[2]	= {
				timeout = 16,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Седой, снова нужна твоя птичка. Сможешь отвезти раненых сталкеров на Неразведанную Землю? Местный доктор присмотрит за ними. Я сообщу ему о твоём прилёте... Спасибо за игрушки!"
			},
			[3]	= {
				timeout = 16,
				tip = "%c[255,160,160,160]".."СЕДОЙ:".."\\n".."%c[255,255,128,128]Сделаем, не волнуйся... Всегда пожалуйста!",
				tip_snd = [[sms\sedoy\battle_zaton_38_3]],
			},
			[4]	= {
				timeout = 16,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Шура, в скором времени к вам подлетит вертолёт с ранеными бойцами. Очень прошу, позаботься о них как следует. О медикаментах не беспокойся. Если ещё что-то понадобится, обращайся, всем обеспечу."
			},
			[5]	= {
				tip = "%c[255,160,160,160]".."ШУРА ГИНЕКОЛОГ:".."\\n".."%c[255,255,128,128]Не вопрос. Нуждающимся в моей помощи я никогда не откажу.",
				tip_snd = [[sms\ginekolog\battle_zaton_38_5]],
			}
		},
-- Волна: день второй начался
		[39] = {
			[1]	= {
				timeout = 15
			},
			[2]	= {
				timeout = 20,
				tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]Сталкеры, внимание! С юго-востока в вашем направлении бегут мутанты. Судя по форме меток на экране, они разделены на две большие группы. Первая пройдёт рядом с Лесничеством, другая - по руслу реки. Будут примерно через полчаса.",
				tip_snd = [[sms\kruglov\battle_zaton_39_2]],
			},
			[3]	= {
				tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Меченый, в суматохе я забыл сказать тебе кое-что важное. У нас ещё есть время. Срочно вернись ко мне!",
				tip_snd = [[sms\noy\battle_zaton_39_3]],
			}
		},
-- Волна: день второй
		[40] = {
			[1]	= {
				info = "volna_goodwill",
				timeout = 15
			},
			[2]	= {
				timeout = 430,
				tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]До подхода мутантов осталось семь минут.",
				tip_snd = [[sms\kruglov\battle_zaton_40_2]],
			},
			[3]	= {
				timeout = 20,
				func = "akill.volna_day2_dogs()"
			},
			[4]	= {
				timeout = 60,
				func = "akill.volna_day2_dogs()"
			},
			[5]	= {
				timeout = 60,
				func = "akill.volna_day2_boars()"
			},
			[6]	= {
				timeout = 70,
				func = "akill.volna_day2_boars()"
			},
			[7]	= {
				timeout = 70,
				func = "akill.volna_day2_dogs()"
			},
			[8]	= {
				timeout = 70,
				func = "akill.volna_day2_dogs()"
			},
			[9]	= {
				timeout = 70,
				func = "akill.volna_day2_boars()"
			},
			[10]	= {
				dist = 80,
				info = "kogot_defenders_otboi",
				timeout = 80,
				enemy = {
					["cat_strong"] = 4,
					["cat_normal"] = 4,
					["cat_weak"] = 4,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_strong"] = 3,
					["snork_jumper"] = 2,
					["snork_nosach"] = 3,
					["snork_stronger"] = 1,
					["fracture_strong"] = 6,
					["fracture_master"] = 6,
					["fracture_karlik"] = 6
				}
			},
			[11]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["bloodsucker_effector"] = 1,
					["oboroten"] = 2,
					["electro_chimera"] = 4,
					["chimera_x_ray"] = 5,
					["chimera_wolf"] = 5,
					["chimera_black"] = 2,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_normal"] = 4,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["chimera_strong"] = 3
				}
			},
			[12]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["vypolzen"] = 8,
					["vypolzen_red"] = 8,
					["snork_stronger"] = 3,
					["snork_jumper"] = 5,
					["snork_nosach"] = 3,
					["snork_strong"] = 8
				}
			},
			[13]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 4,
					["fracture_master"] = 4,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 4,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["deathclaw_normal"] = 1
				}
			},
			[14]	= {
				ruk_sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Эй, я здесь. Бросил рюкзак возле тебя.",
				ruk_snd = [[sms\lovkach\battle_zaton_14_1]],
				rest = true,
				rukzak = true,
				timeout = 60,
				items = {
					["medkit"] = 4,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 3
				}
			},
			[15]	= {
				dist = 80,
				timeout = 30,
				enemy = {
					["boar_strong"] = 5,
					["boar_kachok"] = 5,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 3,
					["molerat"] = 3,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[16]	= {
				tip = "%c[255,160,160,160]".."ЛОКАЛЬНАЯ СЕТЬ:".."\\n".."%c[255,255,128,128]Долг спешит на помощь. Мы подорвали взрывчатку, но мутантов оказалось слишком много. Часть из них рванула в сторону Шевченко.",
				tip_snd = [[sms\net\battle_zaton_40_16]],
				dist = 60,
				timeout = 16,
				enemy = {
					["dolg_volna1"] = 1,
					["dolg_volna2"] = 1,
					["dolg_volna3"] = 1,
					["dolg_volna4"] = 1,
					["ohotnik_volna"] = 1
				}
			},
			[17]	= {
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ничего, мы справимся. Не снижайте темп стрельбы.",
				timeout = 12
			},
			[18]	= {
				dist = 80,
				timeout = 110,
				enemy = {
					["boar_strong"] = 4,
					["boar_kachok"] = 4,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 4,
					["molerat"] = 4,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[19]	= {
				dist = 80,
				timeout = 110,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["psy_dog"] = 1,
					["volkodav"] = 2,
					["pseudodog_strong"] = 5
				}
			},
			[20]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["cat_strong"] = 3,
					["cat_normal"] = 3,
					["cat_weak"] = 4,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2,
					["snork_strong"] = 3,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["gigant_strong"] = 2
				}
			},
			[21]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 3,
					["gigant_red_strong"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[22]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 2,
					["bloodsucker_strong"] = 1,
					["oboroten"] = 1,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["bloodsucker_hell"] = 1
				}
			},
			[23]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 4,
					["fracture_master"] = 5,
					["fracture_karlik"] = 4,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["new_hell"] = 1
				}
			},
			[24]	= {
				ruk_sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Ты пустой? Тогда подбирай очередной боекомплект.",
				ruk_snd = [[sms\lovkach\battle_zaton_24_1]],
				rest = true,
				rukzak = true,
				timeout = 100,
				items = {
					["medkit_army"] = 4,
					["ammo_23x76_shrap"] = 2,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 4
				}
			},
			[25]	= {
				dist = 80,
				timeout = 40,
				enemy = {
					["electro_chimera"] = 2,
					["chimera_x_ray"] = 3,
					["chimera_wolf"] = 3,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 2,
					["bloodsucker_effector"] = 1,
					["oboroten"] = 1,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["bloodsucker_strong"] = 4,
					["bloodsucker_child"] = 1
				}
			},
			[26]	= {
				dist = 60,
				timeout = 120,
				enemy = {
					["dolg_volna1"] = 1,
					["dolg_volna2"] = 1,
					["dolg_volna3"] = 1,
					["dolg_volna4"] = 1,
					["ohotnik_volna"] = 1
				}
			},
			[27]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 3,
					["gigant_red_strong"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[28]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["electro_chimera"] = 4,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
 					["bear"] = 3,
 					["lican"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 4,
					["chimera_strong"] = 4
				}
			},
			[29]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 10,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[30]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 3,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["bloodsucker_hell"] = 1
				}
			},
			[31]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 3,
					["fracture_strong"] = 4,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["deathclaw_strong"] = 1,
					["deathclaw_weak"] = 1,
					["deathclaw_normal"] = 2
				}
			},
			[32]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["electro_chimera"] = 4,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 3,
 					["bear"] = 2,
 					["lican"] = 2,
					["bloodsucker_hell"] = 2
				}
			},
			[33]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 5,
					["fracture_master"] = 4,
					["fracture_karlik"] = 4,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["new_hell"] = 2
				}
			},
			[34]	= {
				ruk_sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Скинул рюкзачок полный всякого добра. Осмотрись внимательно.",
				rest = true,
				rukzak = true,
				timeout = 80,
				items = {
					["medkit_scientic"] = 5,
					["ammo_balon"] = 4,
					["ammo_23x76_shrap"] = 3,
					["ammo_12.7x108r"] = 4,
					["ammo_minigun"] = 6
				}
			},
			[35]	= {
				dist = 100,
				timeout = 40,
				enemy = {
					["bloodsucker_hell"] = 3,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 1,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 2,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 4
				}
			},
			[36]	= {
				dist = 60,
				timeout = 180,
				enemy = {
					["dolg_volna1"] = 1,
					["dolg_volna2"] = 1,
					["dolg_volna3"] = 1,
					["dolg_volna4"] = 1,
					["ohotnik_volna"] = 1
				}
			},
			[37]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bloodsucker_hell"] = 1,
					["oboroten"] = 1,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 2,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 3,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[38]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["kontrik_yantar1"] = 1,
					["bibliotekar"] = 2,
					["bibliotekar_black"] = 2,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 3,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[39]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["new_hell"] = 5,
					["deathclaw_strong"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_weak"] = 2,
					["bloodsucker_hell"] = 5,
					["bloodsucker_child"] = 4,
					["oboroten"] = 3,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_effector"] = 5,
					["bloodsucker_strong"] = 5
				}
			},
			[40]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 1,
					["bibliotekar_black"] = 1,
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1,
					["gigant_strong"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["chimera_black"] = 2,
					["new_electro_chimera"] = 1,
					["fire_chimera"] = 1,
					["chimera_normal"] = 2,
					["chimera_strong"] = 1,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 2
				}
			},
			[41]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 1,
					["bibliotekar_black"] = 1,
					["gigant_big_strong"] = 1,
					["gigant_strong"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["chimera_black"] = 2,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 2,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2
				}
			},
			[42]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 4,
					["bibliotekar_black"] = 2,
					["kontrik_yantar2"] = 1,
					["kontrik_labx16"] = 1,
					["controller_babka"] = 1,
					["m_controller_act"] = 1,
					["controller_flame"] = 1,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_big_strong"] = 1,
					["fracture_master"] = 4,
					["fracture_karlik"] = 4,
					["deathclaw_weak"] = 1,
					["deathclaw_normal"] = 1,
					["deathclaw_strong"] = 1,
					["vypolzen"] = 5,
					["vypolzen_red"] = 5,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[43]	= {
				dist = 70,
				enemy = {
					["kontrik_senator"] = 1
				}
		    	}
		},
-- Штурм станции
		[41] = {
			[1]	= {
				timeout = 17,
				tip = "%c[255,160,160,160]".."ФЕНИКС:".."\\n".."%c[255,255,128,128]Меченый, появилась небольшая проблема. Наш отряд рядом со станцией переработки отходов. Бандиты решили устроить там свою базу. Мы готовы штурмовать её в любой момент. Ждём лишь твоего приказа."
			},
			[2]	= {
				timeout = 17,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]До моего прихода не предпринимайте никаких действий. Я скоро буду."
			},
			[3]	= {
				tip = "%c[255,160,160,160]".."ФЕНИКС:".."\\n".."%c[255,255,128,128]Так точно. Найдёшь нас к западу от станции."
			}
		},
-- Волна: день третий
		[42] = {
			[1]	= {
				info = "volna_goodwill",
				timeout = 25
			},
			[2]	= {
				timeout = 500,
				tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]Мутанты вот-вот нагрянут, у вас в запасе девять минут.",
				tip_snd = [[sms\kruglov\battle_zaton_42_2]],
			},
			[3]	= {
				timeout = 40,
				func = "akill.volna_day3_boars()"
			},
			[4]	= {
				timeout = 120,
				func = "akill.volna_day3_chimera()"
			},
			[5]	= {
				timeout = 50,
				func = "akill.volna_day3_boars()"
			},
			[6]	= {
				timeout = 140,
				func = "akill.volna_day3_chimera()"
			},
			[7]	= {
				dist = 80,
				timeout = 100,
				enemy = {
					["boar_strong"] = 5,
					["boar_kachok"] = 5,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 4,
					["molerat"] = 4,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[8]	= {
				dist = 80,
				info = "fenix_defenders_otboi",
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["psy_dog"] = 1,
					["volkodav"] = 2,
					["pseudodog_strong"] = 5
				}
			},
			[9]	= {
				dist = 80,
				timeout = 90,
				enemy = {
					["cat_strong"] = 4,
					["cat_normal"] = 4,
					["cat_weak"] = 4,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_strong"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["fracture_strong"] = 6,
					["fracture_master"] = 6,
					["fracture_karlik"] = 6
				}
			},
			[10]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["vypolzen"] = 9,
					["vypolzen_red"] = 9,
					["snork_stronger"] = 4,
					["snork_jumper"] = 5,
					["snork_nosach"] = 3,
					["snork_strong"] = 8
				}
			},
			[11]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["bloodsucker_effector"] = 1,
					["oboroten"] = 1,
					["electro_chimera"] = 4,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 4,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["chimera_strong"] = 3
				}
			},
			[12]	= {
				dist = 80,
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["psy_dog"] = 1,
					["volkodav"] = 2,
					["pseudodog_strong"] = 5
				}
			},
			[13]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 1,
					["fracture_strong"] = 4,
					["fracture_master"] = 4,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["deathclaw_weak"] = 1,
					["deathclaw_strong"] = 1,
					["deathclaw_normal"] = 1
				}
			},
			[14]	= {
				ruk_sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Поищи рюкзак на земле.",
				ruk_snd = [[sms\lovkach\battle_zaton_14_2]],
				rest = true,
				rukzak = true,
				timeout = 60,
				items = {
					["medkit"] = 4,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 3
				}
			},
			[15]	= {
				dist = 80,
				timeout = 30,
				enemy = {
					["boar_strong"] = 5,
					["boar_kachok"] = 5,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 4,
					["molerat"] = 4,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[16]	= {
				dist = 60,
				timeout = 40,
				enemy = {
					["stalker_volna1"] = 1,
					["stalker_volna2"] = 1,
					["stalker_volna3"] = 1,
					["stalker_volna4"] = 1
				}
			},
			[17]	= {
				dist = 80,
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["psy_dog"] = 1,
					["volkodav"] = 2,
					["pseudodog_strong"] = 5
				}
			},
			[18]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["cat_strong"] = 3,
					["cat_normal"] = 4,
					["cat_weak"] = 3,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2,
					["snork_strong"] = 3,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["gigant_strong"] = 2
				}
			},
			[19]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 3,
					["gigant_strong"] = 3,
					["gigant_red_strong"] = 2,
					["gigant_jumper_strong"] = 4,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 2,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 2
				}
			},
			[20]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["bloodsucker_mil"] = 1,
					["bloodsucker_hell"] = 2
				}
			},
			[21]	= {
				dist = 80,
				timeout = 100,
				enemy = {
					["boar_strong"] = 5,
					["boar_kachok"] = 5,
					["spider"] = 2,
					["arahnid"] = 2,
					["arahnid_strong"] = 2,
					["kikimora"] = 3,
					["molerat"] = 3,
					["tushkano_normal"] = 4,
					["tushkano_strong"] = 4,
					["winger"] = 4,
					["nosales"] = 4,
					["zanoza"] = 2,
					["flesh_weak"] = 2,
					["flesh_normal"] = 2,
					["flesh_swamp"] = 2,
					["flesh_strong"] = 2
		 		}
			},
			[22]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 5,
					["fracture_master"] = 4,
					["fracture_karlik"] = 4,
					["poltergeist_build"] = 2,
					["karlito"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["new_hell"] = 1
				}
			},
			[23]	= {
				dist = 80,
				timeout = 100,
				enemy = {
					["dog_habaruch"] = 6,
					["dog_sil_hill"] = 5,
					["dog_skeleton"] = 6,
					["dog_green"] = 6,
					["dog_strong"] = 6,
					["dog_zombie"] = 4,
					["stinger"] = 5,
					["pseudodog_big"] = 3,
					["psy_dog"] = 1,
					["volkodav"] = 2,
					["pseudodog_strong"] = 5
				}
			},
			[24]	= {
				ruk_sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Около тебя лежит рюкзак. Не пробегай мимо.",
				ruk_snd = [[sms\lovkach\battle_zaton_24_2]],
				rest = true,
				rukzak = true,
				timeout = 100,
				items = {
					["medkit_army"] = 4,
					["ammo_23x76_shrap"] = 2,
					["ammo_balon"] = 3,
					["ammo_12.7x108r"] = 3,
					["ammo_minigun"] = 4
				}
			},
			[25]	= {
				dist = 80,
				timeout = 90,
				enemy = {
					["cat_strong"] = 4,
					["cat_normal"] = 4,
					["cat_weak"] = 4,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_strong"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["fracture_strong"] = 5,
					["fracture_master"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 3,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["fracture_karlik"] = 6
				}
			},
			[26]	= {
				dist = 60,
				timeout = 100,
				enemy = {
					["stalker_volna1"] = 1,
					["stalker_volna2"] = 1,
					["stalker_volna3"] = 1,
					["stalker_volna4"] = 1
				}
			},
			[27]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 3,
					["gigant_red_strong"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[28]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["electro_chimera"] = 5,
					["chimera_x_ray"] = 5,
					["chimera_wolf"] = 5,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
 					["bear"] = 3,
 					["lican"] = 3,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["chimera_strong"] = 3
				}
			},
			[29]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["gigant_big_strong"] = 2,
					["gigant_strong"] = 10,
					["gigant_jumper_strong"] = 2,
					["gigant_virus_strong"] = 1,
					["oboroten"] = 1,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_child"] = 1
				}
			},
			[30]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 3,
					["chimera_wolf"] = 3,
					["new_electro_chimera"] = 3,
					["fire_chimera"] = 3,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 3,
 					["bear"] = 2,
 					["lican"] = 2,
					["bloodsucker_hell"] = 1
				}
			},
			[31]	= {
				dist = 80,
				timeout = 180,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 3,
					["fracture_strong"] = 4,
					["fracture_master"] = 5,
					["fracture_karlik"] = 5,
					["poltergeist_build"] = 2,
					["karlito"] = 3,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["deathclaw_weak"] = 1,
					["deathclaw_strong"] = 1,
					["deathclaw_normal"] = 1
				}
			},
			[32]	= {
				dist = 80,
				timeout = 190,
				enemy = {
					["electro_chimera"] = 3,
					["chimera_x_ray"] = 4,
					["chimera_wolf"] = 4,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_black"] = 2,
					["chimera_normal"] = 3,
					["chimera_strong"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["bloodsucker_effector"] = 1,
					["bloodsucker_strong"] = 4,
					["bloodsucker_child"] = 1
				}
			},
			[33]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 5,
					["bibliotekar_black"] = 2,
					["fracture_strong"] = 5,
					["fracture_master"] = 4,
					["fracture_karlik"] = 4,
					["poltergeist_build"] = 2,
					["karlito"] = 3,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["new_hell"] = 2
				}
			},
			[34]	= {
				ruk_sms = "%c[255,160,160,160]".."ЛОВКАЧ:".."\\n".."%c[255,255,128,128]Глянь-ка вниз, найдёшь там рюкзачок.",
				ruk_snd = [[sms\lovkach\battle_zaton_34_1]],
				rest = true,
				rukzak = true,
				timeout = 80,
				items = {
					["medkit_scientic"] = 5,
					["ammo_balon"] = 4,
					["ammo_23x76_shrap"] = 3,
					["ammo_12.7x108r"] = 4,
					["ammo_minigun"] = 6
				}
			},
			[35]	= {
				dist = 100,
				timeout = 40,
				enemy = {
					["bloodsucker_hell"] = 3,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 1,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["new_hell"] = 2,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 3,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 4
				}
			},
			[36]	= {
				tip = "%c[255,160,160,160]".."СЛАВКА АНТИЗОМБИ:".."\\n".."%c[255,255,128,128]Меченый, это Славка, племянник Скряги. Спешу к вам на помощь.",
				tip_snd = [[sms\antizombi\battle_zaton_42_36]],
				dist = 60,
				timeout = 180,
				enemy = {
					["slavka_volna"] = 1,
					["stalker_volna1"] = 1,
					["stalker_volna2"] = 1,
					["stalker_volna3"] = 1,
					["stalker_volna4"] = 1
				}
			},
			[37]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bloodsucker_hell"] = 1,
					["oboroten"] = 1,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 3,
					["deathclaw_weak"] = 3,
					["deathclaw_normal"] = 3,
					["deathclaw_strong"] = 3,
					["new_hell"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] = 3,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 4
				}
			},
			[38]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["kontrik_yantar1"] = 1,
					["bibliotekar"] = 3,
					["bibliotekar_black"] = 3,
					["deathclaw_weak"] = 3,
					["deathclaw_normal"] = 3,
					["deathclaw_strong"] = 3,
					["new_hell"] = 3,
					["vypolzen"] = 3,
					["vypolzen_red"] =3,
					["snork_stronger"] = 3,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[39]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["new_hell"] = 5,
					["deathclaw_strong"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_weak"] = 2,
					["bloodsucker_hell"] = 5,
					["bloodsucker_child"] = 4,
					["oboroten"] = 3,
					["burer_normal"] = 1,
					["burer_strong"] = 1,
					["burer_build"] = 1,
					["burer_electro"] = 1,
					["bloodsucker_effector"] = 5,
					["bloodsucker_strong"] = 4
				}
			},
			[40]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 1,
					["bibliotekar_black"] = 1,
					["gigant_jumper_strong"] = 1,
					["gigant_big_strong"] = 1,
					["gigant_strong"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["chimera_black"] = 2,
					["new_electro_chimera"] = 1,
					["fire_chimera"] = 1,
					["chimera_normal"] = 2,
					["chimera_strong"] = 1,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["snork_stronger"] = 2,
					["snork_jumper"] = 2,
					["snork_nosach"] = 2,
					["snork_strong"] = 2
				}
			},
			[41]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 1,
					["bibliotekar_black"] = 1,
					["gigant_big_strong"] = 1,
					["gigant_strong"] = 2,
					["fracture_master"] = 2,
					["fracture_karlik"] = 2,
					["fracture_strong"] = 2,
					["poltergeist_build"] = 2,
					["karlito"] = 1,
					["m_poltergeist_dd"] = 2,
					["electro_polter"] = 2,
					["polter_xray"] = 2,
					["electro_chimera"] = 2,
					["chimera_x_ray"] = 2,
					["chimera_wolf"] = 2,
					["chimera_black"] = 2,
					["new_electro_chimera"] = 2,
					["fire_chimera"] = 2,
					["chimera_normal"] = 2,
					["chimera_strong"] = 2,
					["new_hell"] = 1,
					["kikimora"] = 2,
					["molerat"] = 2,
					["volkodav"] = 2,
 					["bear"] = 2,
 					["lican"] = 2,
					["vypolzen"] = 2,
					["vypolzen_red"] = 2
				}
			},
			[42]	= {
				dist = 80,
				timeout = 200,
				enemy = {
					["bibliotekar"] = 4,
					["bibliotekar_black"] = 2,
					["kontrik_yantar2"] = 1,
					["kontrik_labx16"] = 1,
					["controller_babka"] = 1,
					["m_controller_act"] = 1,
					["controller_flame"] = 1,
					["controller_electro"] = 1,
					["psyonik"] = 1,
					["gigant_jumper_strong"] = 2,
					["gigant_big_strong"] = 1,
					["fracture_master"] = 3,
					["fracture_karlik"] = 3,
					["deathclaw_weak"] = 2,
					["deathclaw_normal"] = 2,
					["deathclaw_strong"] = 2,
					["vypolzen"] = 5,
					["vypolzen_red"] = 5,
					["snork_stronger"] = 2,
					["snork_jumper"] = 3,
					["snork_nosach"] = 3,
					["snork_strong"] = 3
				}
			},
			[43]	= {
				dist = 70,
				enemy = {
					["kontrik_senator"] = 1
				}
	    	}
		},
-- Волна: последняя битва началась
		[43] = {
			[1]	= {
				timeout = 7
			},
			[2]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Кавалерия прибыла! Бронетехника к вашим услугам. Как вы тут, ещё держитесь?"
			},
			[3]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Никогда не думал, что скажу это военному, но как же я рад вам, ребята!"
			},
			[4]	= {
				timeout = 16,
				tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Словесности оставим на потом. Я смог связаться с учёными, монстры совсем рядом. Мы привезли с собой ящики с патронами. Где нам их выгрузить и где лучше всего занять позиции? Надо бы создать сплошную линию обороны."
			},
			[5]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Наши лагеря на Шевченко, в Лесничестве и на станции переработки. Между ними большие незащищённые пространства."
			},
			[6]	= {
				timeout = 18,
				tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Вас понял. Прикажу своим укрепиться у портовых кранов, у лагеря Изумрудное и возле заправки... Меченый, у тебя будет особое задание. Ты должен отвлекать мутантов на себя, пока мои хлопцы утюжат их изо всех орудий. Иначе никак, нашу броню просто-напросто сметут. Беги, встречай коробочку в первой точке."
			},
			[7]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Значит, я буду в качестве приманки? Спасибо тебе, капитан, удружил!"
			},
			[8]	= {
				timeout = 15,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ной, наше положение кардинально изменилось. По моей просьбе прибыла военная делегация на БТРах, вместе с боеприпасами, между прочим. Совсем забыл тебе о ней рассказать."
			},
			[9]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."НОЙ:".."\\n".."%c[255,255,128,128]Ха, ну ты и сволочь! Из-за тебя я усомнился в самом себе, в намерениях Создателя! Но всё же я рад это услышать. Я передам остальным радостную весть... Желаю нам всем пережить сегодняшний день!",
				tip_snd = [[sms\noy\battle_zaton_43_9]],
			},
			[10]	= {
				info = "volna_goodwill",
				info = "volna_day4_start"
			}
		},
-- Волна: последняя битва, портовые краны
		[44] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 20,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Мужики, я на месте. Вы только по мне не палите, хорошо? Цельтесь как следует."
			},
			[3]	= {
				dist = 70,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["bloodsucker_volna"] = 2
		 		}
			},
			[4]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["deathclaw_volna"] = 2
				}
			},
			[5]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 3,
					["deathclaw_volna"] = 2
				}
			},
			[6]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 4,
					["chimera_wolf_volna"] = 3,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 1
				}
			},
			[7]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 3
				}
			},
			[8]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 2
				}
			},
			[9]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 4,
					["bloodsucker_volna"] = 5,
					["deathclaw_volna"] = 3
				}
			},
			[10]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 1
		 		}
			},
			[11]	= {
				dist = 50,
				timeout = 20,
				enemy = {
					["volna_biblik"] = 1
		 		}
			},
			[12]	= {
				timeout = 10,
				func = "akill.volna_day1_dogs()",
				tip = "%c[255,160,160,160]".."ЖНЕЦ-21:".."\\n".."%c[255,255,128,128]К нашим позициям приближается волна мутантов."
				},
			[13]	= {
				func = "spawn_restrictor.volna_btr2_sr1()",
				tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Меченый, срочно беги к лагерю Изумрудное. Мои ребята тебя прикроют."
	    			}
		},
-- Волна: последняя битва, лагерь Изумрудное
		[45] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 12,
				tip = "%c[255,160,160,160]".."КОРШУН:".."\\n".."%c[255,255,128,128]Меченый, нас тут сильно прижали. Медведь и Пёс тяжело ранены, шестеро долговцев мертвы. Пришли сюда хотя бы один БТР.",
				tip_snd = [[sms\korshun\battle_zaton_45_2]],
			},
			[3]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Капитан, охотников в Лесничестве изрядно потрепали. Прикажи своим бойцам выдвинутся им на помощь."
			},
			[4]	= {
				timeout = 13,
				tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Хорошо... Жнец-11 удерживайте свою позицию, Жнец-12 срочно выдвигайтесь в сторону Лесничества и окажите поддержку сталкерам."
			},
			[5]	= {
				dist = 70,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["bloodsucker_volna"] = 2
		 		}
			},
			[6]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["deathclaw_volna"] = 2
				}
			},
			[7]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 3,
					["deathclaw_volna"] = 2
				}
			},
			[8]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 4,
					["chimera_wolf_volna"] = 3,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 1
				}
			},
			[9]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 3
				}
			},
			[10]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 2
				}
			},
			[11]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 4,
					["bloodsucker_volna"] = 5,
					["deathclaw_volna"] = 3
				}
			},
			[12]	= {
				dist = 80,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 1
		 		}
			},
			[13]	= {
				dist = 50,
				timeout = 20,
				enemy = {
					["volna_deathclaw"] = 1
		 		}
			},
			[14]	= {
				timeout = 12,
				tip = "%c[255,160,160,160]".."КРУГЛОВ:".."\\n".."%c[255,255,128,128]Внимание всем! Треть мутантов отделилась от основной волны и движется по южной части Затона, в обход ваших позиций.",
				tip_snd = [[sms\kruglov\battle_zaton_45_14]],
		},
			[15]	= {
				func = "spawn_restrictor.volna_btr3_sr1()",
				tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Меченый, мы перехватим их возле заправки. Дуй сюда как можно быстрее."
	    	}
		},
-- Волна: последняя битва, заправка
		[46] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Капитан, мы не должны пропустить эту волну. Если не справимся, то все защитники будут окружены."
			},
			[3]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Сам знаю. Ты, главное, выведи монстров на открытую местность, а дальше мы сами."
			},
			[4]	= {
				dist = 70,
				timeout = 150,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["bloodsucker_volna"] = 2
		 		}
			},
			[5]	= {
				dist = 80,
				timeout = 160,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["deathclaw_volna"] = 2
				}
			},
			[6]	= {
				dist = 80,
				timeout = 160,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 3,
					["deathclaw_volna"] = 2
				}
			},
			[7]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 4,
					["chimera_wolf_volna"] = 3,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 1
				}
			},
			[8]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 2,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 3
				}
			},
			[9]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 1,
					["deathclaw_volna"] = 2
				}
			},
			[10]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 4,
					["bloodsucker_volna"] = 5,
					["deathclaw_volna"] = 3
				}
			},
			[11]	= {
				dist = 80,
				timeout = 170,
				enemy = {
					["chimera_xray_volna"] = 5,
					["chimera_wolf_volna"] = 5,
					["bibliotekar_volna"] = 5,
					["bibliotekar_black_volna"] = 5,
					["new_hell_volna"] = 1,
					["bloodsucker_volna"] = 2,
					["deathclaw_volna"] = 1
		 		}
			},
			[12]	= {
				dist = 50,
				timeout = 100,
				enemy = {
					["volna_new_hell"] = 1
		 		}
			},
			[13]	= {
				timeout = 10,
				tip = "%c[255,160,160,160]".."КАПИТАН ФИЛАТОВ:".."\\n".."%c[255,255,128,128]Вроде бы, всё чисто, никого не упустили... Погоди-ка, сейчас я вылезу из этой жестянки..."
	    		},
			[14]	= {
				func = "akill.cap_filatov_spawn()"
	    		}
		},
-- Подарок Оружейника
		[47] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 8,
				func = "akill.taynik_podarok_bum()"
			},
			[3]	= {
				func = "akill.taynik_podarok_mutant()"
			}
		},
-- Паучья сеть, взрываем бомбы
		[49] = {
			[1]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Назар, взрывчатка заложена, я выбрался из пещер, произвожу детонацию. Взгляни-ка на юг..."
			},
			[2]	= {
				timeout = 6,
				func = "akill.nazar_spider_timer()"
			},
			[3]	= {
				timeout = 18,
				func = "akill.nazar_spider_bum()"
			},
			[4]	= {
				tip = "%c[255,160,160,160]".."НАЗАР:".."\\n".."%c[255,255,128,128]Красота! Дело сделано, возвращайся на корабль.",
				tip_snd = [[sms\nazar\battle_zaton_49_4]],
				info = "nazar_spider_end"
			}
		},
-- Немецкий орден, немцы из тп
		[50] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 6,
				func = "akill.nazar_orden_flash()"
			},
			[3]	= {
				timeout = 15,
				tip = "%c[255,160,160,160]".."НАЗАР:".."\\n".."%c[255,255,128,128]Видел белую вспышку? Наверняка скоро снова откроются временные порталы. Если нашёл генерала и забрал орден, поспеши на корабль. Фрицы не заставят себя долго ждать.",
				tip_snd = [[sms\nazar\battle_zaton_50_3]],
			},
			[4]	= {
				timeout = 15,
				func = "akill.orden_tp1()"
			},
			[5]	= {
				timeout = 20,
				func = "akill.orden_tp2()"
			},
			[6]	= {
				timeout = 20,
				func = "akill.orden_tp3()"
			},
			[7]	= {
				func = "akill.orden_tp2()"
			}
		},
-- Немецкий орден, немцы у Шевченко
		[51] = {
			[1]	= {
				timeout = 5
			},
			[2]	= {
				timeout = 6,
				func = "akill.nazar_orden_flash()"
			},
			[3]	= {
				timeout = 8,
				tip = "%c[255,160,160,160]".."НАЗАР:".."\\n".."%c[255,255,128,128]Ну вот опять! Всем - будьте начеку! Солдаты могут появиться откуда угодно.",
				tip_snd = [[sms\nazar\battle_zaton_51_3]],
			},
			[4]	= {
				timeout = 8,
				tip = "%c[255,160,160,160]".."МЕРЦАЮЩИЙ:".."\\n".."%c[255,255,128,128]Лучше бы к нам из прошлого цистерну с самогоном перекинуло."
			},
			[5]	= {
				timeout = 20,
				func = "akill.orden_tp4()"
			},
			[6]	= {
				timeout = 25,
				func = "akill.orden_tp5()"
			},
			[7]	= {
				timeout = 25,
				func = "akill.orden_tp6()"
			},
			[8]	= {
				timeout = 25,
				func = "akill.orden_tp4()"
			},
			[9]	= {
				timeout = 25,
				func = "akill.orden_tp5()"
			},
			[10]	= {
				func = "akill.orden_tp6()"
			}
		},
-- Засада немцев у Изумрудного
		[52] = {
			[1]	= {
				timeout = 2
			},
			[2]	= {
				timeout = 5,
				func = "akill.nazar_orden_flash()"
			},
			[3]	= {
				timeout = 3,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Это ещё что такое?"
			},
			[4]	= {
				func = "akill.zasada_vermaht_spawn()"
			}
		},
-- Защита госпиталя
		[53] = {
			[1]	= {
				timeout = 3,
			},
			[2]	= {
				timeout = 90,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Ной, я на вышке. Вижу неколько зомбарей. Думаю, справлюсь в одиночку.",
				func = "akill.defend_hospital_spawn1()"
			},
			[3]	= {
				timeout = 100,
				func = "akill.defend_hospital_spawn2()"
			},
			[4]	= {
				timeout = 100,
				func = "akill.defend_hospital_spawn3()"
			},
			[5]	= {
				timeout = 100,
				func = "akill.defend_hospital_spawn1()"
			},
			[6]	= {
				timeout = 10,
				func = "akill.defend_hospital_spawn4()"
			},
			[7]	= {
				func = "akill.volna_day1_dogs()"
			}
		},
-- Подрыв гиганта
		[54] = {
			[1]	= {
				timeout = 17,
			},
			[2]	= {
				timeout = 5,
				tip = "%c[255,160,160,160]".."БАСТИ:".."\\n".."%c[255,255,128,128]Обернись-ка назад... Взрываю!",
				tip_snd = [[sms\buusty\battle_zaton_54_2]], 
			},
			[3]	= {
				timeout = 1,
				func = "akill.gigant_swamp_bum()"
			},
			[4]	= {
				timeout = 5,
				func = "akill.gigant_swamp_kill()"
			},
			[5]	= {
				timeout = 7,
				info = "buusty_gigant_have"
			},
			[6]	= {
				dist = 65,
				tip = "%c[255,160,160,160]".."МЕЧЕНЫЙ:".."\\n".."%c[255,255,128,128]Вот, блин! На грохот другие мутанты сбежались...",
				enemy = {
					["molerat"] = 5,
					["nosales"] = 4,
					["kikimora"] = 5
				}
			}
		}
	}
-- Akill end
}

-- Основной обработчик. Вызывает сам себя через таймер. И первый запуск нужно делать тоже через таймер.
function show_must_go_on(params_string)
	local data = amk.unpack_array_from_string(params_string)
	local lvl, btl, wave = data[1], tonumber(data[2]), tonumber(data[3])
	local cur_wave = battles[lvl][btl][wave]
	local pos, lv, sector
	--console:execute("load ~~~ lvl: "..lvl..", btl: "..tostring(btl)..", wave: "..tostring(wave))
	
	-- сменили локу - битва закончена
    if level.name() ~= lvl then 
		show_off()
		return
	end

	sector = get_sector()
	give_info("battle")

	-- проверяем, не заныкался ли где гг в закутке - можно ли заспавнить на нормальном расстоянии от него
	if cur_wave.dist then
		pos, lv = get_pos(cur_wave.dist, sector)
		if pos:distance_to(db.actor:position()) < min_good_distance then
			-- заныкался - откладываем спавн, пока гг не выйдет из укрытия
			amk.start_timer("battle", min_good_distance_timeout, {lvl, btl, wave})
			return
		end
	end
	
	-- спавн монстров/неписей
	if cur_wave["enemy"] then
		for s,p in pairs(cur_wave["enemy"]) do
			for i=1,p do
				pos, lv = get_pos(cur_wave.dist, sector)
				create(s, pos, lv, db.actor:game_vertex_id())
				monster_cnt = monster_cnt+1
			end
		end
	end

	if cur_wave.rest then
		-- есть перерыв

		if cur_wave.rukzak then
			-- есть тайник - спавним
			amk.start_timer("battle_rest", math.random(cur_wave.timeout*0.8, cur_wave.timeout*1.2), {lvl, btl, wave, monster_cnt})
		end

		-- даем передышку
		cur_wave.timeout = cur_wave.timeout+rest_timeout
		monster_cnt = 0
	end

	if cur_wave.info then
		-- выдаем поршень
		give_info(cur_wave.info)
	end
	if cur_wave.func then
		-- выполняем функцию
		loadstring(cur_wave.func)()
	end
	if cur_wave.tip then
		-- выдаем смс
		sms(cur_wave.tip, nil, nil, 15000, nil, cur_wave.tip_snd)
	end

	-- следующая волна
	wave = wave+1
	if battles[lvl][btl][wave] then
		-- есть следующая волна - запускаем
		--console:execute("load ~~~ lvl: "..lvl..", btl: "..tostring(btl)..", wave: "..tostring(wave))
		amk.start_timer("battle", math.random(cur_wave.timeout*0.8, cur_wave.timeout*1.2), {lvl, btl, wave})
	else
		-- конец битвы
		show_off()
	end
end

-- подкрепление в виде рюкзака
-- текущая волна должна идти параметром приватно, т.к. наверху уже следующая волна на очереди
function reinforcement(params_string)
	local data = amk.unpack_array_from_string(params_string)
	local lvl, btl, wave, last_monster_cnt = data[1], tonumber(data[2]), tonumber(data[3]), tonumber(data[4])
	local cur_wave = battles[lvl][btl][wave]
	local pos, lv

	-- сменили локу - битва закончена
    if level.name() ~= lvl then 
		show_off()
		return
	end
	
	-- рюкзак спавним с меткой и не далее 10 м от гг, чтобы нашел
	pos, lv = get_pos(math.random(3,10))
	local ruk = create("m_inventory_box_battle", pos, lv, db.actor:game_vertex_id())
	level.map_add_object_spot_ser(ruk.id, "treasure", "Рюкзак с припасами")
	--console:execute("load ~~~ ruk.id: "..tostring(ruk.id))

	-- аптечки
	if cur_wave.medkit then
		--console:execute("load ~~~ medkit")
		for i=1,math.random(0, cur_wave.medkit) do
			create(medkits[math.random(#medkits)], xyz(0,0,0), 0, 0, ruk.id)
		end
	end

	-- патроны/подствол
	local wpn, section, list
	if cur_wave.ammo or cur_wave.podstvol then
		for i=1,2 do
			if db.actor:item_in_slot(i) then
				wpn = db.actor:item_in_slot(i)
				
				if cur_wave.ammo then
					--console:execute("load ~~~ ammo")
					for j=1,math.floor(last_monster_cnt*cur_wave.ammo) do
						list = rx_utils.parse_list(nil, wpn:section(), "ammo_class")
						section = list[math.random(#list)]
						ai:create_ammo(section, xyz(0,0,0), 0, 0, ruk.id, rx_utils.read_from_ini(nil, section, "box_size", 1, 3))
					end
				end
				
				if cur_wave.podstvol and rx_utils.addon_attached(wpn, "gl") then
					--console:execute("load ~~~ podstvol")
					for j=1,math.floor(last_monster_cnt*cur_wave.podstvol) do
						list = rx_utils.parse_list(nil, wpn:section(), "grenade_class")
						section = list[math.random(#list)]
						create(section, xyz(0,0,0), 0, 0, ruk.id)
					end
				end
			end
		end
	end
	
	-- разный допхабар
	if cur_wave["items"] then
		for s,p in pairs(cur_wave["items"]) do
			for i=1,p do
				create(s, xyz(0,0,0), 0, 0, ruk.id)
			end
		end
	end

	-- выдаем смс
	if cur_wave.ruk_sms then
		sms(cur_wave.ruk_sms, nil, nil, 15000, nil, cur_wave.ruk_snd)
	end
end

-- выбор сектора для спавна
function get_sector()
	return math.random(1,3)*90
end

-- определение места спавна. параметры:
-- dist - расстояние от ГГ
-- sector - в каком секторе спавнить (сзади, справа, или слева) от ГГ. Сектор получать функцией get_sector(). Если не указан - выполняется рандомный спавн вокруг гг (не нужно указывать для рюкзаков)
-- Возвращает 2 значения: позицию спавна и левел_вертекс
function get_pos(dist, sector)
	local not_random_spawn = sector ~= nil
	if not sector then sector = math.random(360) end
	local pi2 = math.pi*2
	local math_pi_180 = 180/math.pi
	local dir = screen.cam_dir
	local actor_dir														-- вектор взгляда актора, выравненный горизонтально
	local actor_pos = db.actor:position()
	local actor_lv = db.actor:level_vertex_id()
	local pos															-- нужная нам позиция
	local dist_ok = 1.4													-- двойной шаг АИ сетки
	local vert_ok														-- ближайший подходящий вертекс, предложенный движком
	local pos_ok														-- позиция ближайшего подходящего вертекса
	local rotate_angle = math.asin(dist_ok/dist)						-- итератор вращения направления
	local actor_fov = math.rad(screen.fov/2)							-- угол обзора гг, если sector задан - то в видимой зоне не спавним
	local cur_angle = 0
	local cur_pos, cur_vert, cur_dist 
	local best_pos, best_dist											-- наилучшая найденная позиция

	-- выравниваем вектора по горизонтали
	dir = vector():set(dir.x,0,dir.z):normalize()
	actor_dir = dir
	
	-- ищем вертекс по сектору
	dir = vector_rotate_y(dir, sector)
	pos = vector():mad(actor_pos, dir, dist)
	vert_ok = level.vertex_in_direction(actor_lv, dir, dist)
	pos_ok = level.vertex_position(vert_ok)
	
	if not_random_spawn then 
		-- Не рандомый спавн вокруг - нужно искать поточнее в указанном секторе
	
		-- для начала исключаем очевидные случаи
		if pos:distance_to(pos_ok) < dist_ok or
			-- сплошная АИ сетка без препятствий - все нашлось само,
			actor_pos:distance_to(pos_ok) > dist then
			-- либо актор далеко за аи сеткой - спавним в ближайшем подходящем вертексе.
		else
			-- несплошная АИ сетка или препятствия - ищем вариант получше

			-- выставляем направление вращения
			if math.random() < 0.5 then
				rotate_angle = -rotate_angle
			end
			
			-- продолжим искать от ближайшего предложенного движком вертекса в нужном нам направлении
			best_pos = pos
			best_dist = dist
			repeat
				-- поворачиваем направление поиска
				cur_angle = cur_angle+rotate_angle
				dir = vector_rotate_y(dir, rotate_angle*math_pi_180)

				if math.acos(actor_dir:dotproduct(dir)) > actor_fov then
					-- подходящий угол, ищем вертекс
					pos = vector():mad(actor_pos, dir, dist)
					cur_vert = level.vertex_in_direction(actor_lv, dir, dist)
					cur_pos = level.vertex_position(cur_vert)
					cur_dist = pos:distance_to(cur_pos)
					if cur_dist < dist_ok and no_anomaly_in(cur_pos) then
						-- нашли вертекс - выходим
						pos_ok = cur_pos
						vert_ok = cur_vert
						break
					end
					-- точного попадания пока нет - выбираем ближайший по расстоянию вертекс
					if cur_dist < best_dist and no_anomaly_in(cur_pos) then
						best_pos = cur_pos
						best_dist = cur_dist
						pos_ok = cur_pos
						vert_ok = cur_vert
					end
				end
			until math.abs(cur_angle) > pi2
			-- обернулись вокруг - точного попадания нет, используем ближайший к точке
		end
	end

	return pos_ok, vert_ok
end

function show_off()
	monster_cnt = 0
	disable_info("battle")
end

-- "быстрый" уборщик
-- ускоренное удаление трупов при очень больших битвах. вызывается из апдейта монстров
function cleanup(obj)
    if has_info("battle") and (not obj:alive()) and db.actor:position():distance_to(obj:position()) > cleanup_distance then
		release(server_object(obj:id()), true)
	end
end

-- проверка попадания точки спавна в аномалию
function no_anomaly_in(pos)
	local anom_id,anom_pos,anom_radius,dist = amk_anoms.get_nearest_anomaly_for_pos(pos)
	return not anom_id or dist-anom_radius > 5
end
