-- Получение предмета
function checking_taken_item(obj)
	checking_taken_item59(obj)
	checking_taken_item61(obj)
	checking_taken_item62(obj)
	checking_taken_item63(obj)
	checking_taken_item64(obj)
	checking_taken_item_vzn(obj)
	peshera_go(obj)
end

-- stealth
function stealth_start()
	amk.start_timer("run",1.0,"kostya_dialog.stealth_start2()")
end
function stealth_start2()
	level.add_pp_effector ("teleport.ppe", 2006, false)
	say([[anomaly\teleport_work_1]])
	create("tm_brother_labirint",xyz(-313.31903076172,62.234169006348,202.46311950684),38734,2987)
end
function stealth1_have()
	local obj = snp.object_by_section_offline("arhara_seif")
	if obj then
		release(obj)
	end
	news_manager.relocate_item("out", "arhara_seif")
end
function stealth1_done()
	amk.start_timer("run",0.5,"kostya_dialog.stealth1_done2()")
end
function stealth1_done2()
	level.add_pp_effector ("teleport.ppe", 2006, false)
	say([[anomaly\teleport_work_1]])
	release(server_object(snp.object_by_section("tm_brother_labirint"):id()))
	tm_brother_2chaes_spawn()
end
function tm_brother_2chaes_spawn()
	local se_obj = create("tm_brother_2chaes",xyz(84.960639953613,8.7271690368652,113.30625152588),56965,2566)
	snp.set_stalker_story_id(se_obj,9969)
end
function stealth2_done()
	create("s_inventory_box_stealth1",xyz(157.05128479004,12.03516960144,82.391082763672),39526,1229)
	create("s_inventory_box_stealth2",xyz(-73.545913696289,15.663717269897,2.5357427597046),129042,319)
	create("s_inventory_box_stealth3",xyz(-136.37683105469,9.9986381530762,-196.55345275879),102496,629)
	create("s_inventory_box_stealth4",xyz(3.6388249874115,-7.1780724525452,-17.246803207397),312192,1585)
	create("s_inventory_box_stealth5",xyz(23.35853767395,0.18157379329205,-24.917425918579),209456,1046)
end
function stealth5_done()
	got("arhara_seif",1)
	local obj = snp.object_by_section_offline("tm_brother_2chaes")
	if obj then
		release(obj)
	end
end
-- проверка на провал при убийстве, сняти амулета или одевании маскхалата
function stealth_fail_task(victim, who)
	if has_info("stealth2_done") and not has_info("stealth_find_pda_done") and (not who or who:id() == db.actor:id()) then
		give_info("stealth_find_pda_fail")
	end
end
-- подъем рюкзака
function stealth_on_take(box)
	local section = box:section()
	if string.find(section, "s_inventory_box_stealth") then
		give_info("stealth_find_pda_have"..string.sub(section,24,24))
	end
end
-- сдача ПДА
function stealth_find_pda_done()
	lost_all("stealth_pda")
end
function stealth_blow_sidor_done()
	got("wpn_aks74_kalibr_ves_otdaca",1)
	got("wpn_gp100",1)
	braad_test.lab_sar()
end

function krest_topor()
local b = {
	{position={x=-90.577209472656,y=4.2523427009583,z=89.188056945801},gv=2881,lv=115499},
	{position={x=116.68508911133,y=-0.00091594457626343,z=103.09552001953},gv=2885,lv=282454},
	{position={x=44.239944458008,y=-0.0053302049636841,z=16.853719711304},gv=2885,lv=224518}
}
    local a = b[math.random(#b)]
    create("skelet_ded", xyz(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
end

local peshera_table
local function init_peshera_table()
	if peshera_table == nil then
		peshera_table = xr_logic.pstor_get_custom(db.actor, "peshera_clear", "peshera_clear")
	end
end

function peshera_drink(obj)
	if obj:section() == "snotvornoe_tele" then
		peshera_start()
	elseif obj:section() == "shaxter_tele" then
		peshera_end()
	end
end

function peshera_go_pre(section,id)
	if has_info("peshera_go") and section ~= "separator" then
		init_peshera_table()
		peshera_table[id] = true
	end
end

function peshera_go(obj)
	peshera_go_pre(obj:section(),obj:id())
end

function peshera_start()
	local box = obj_by_name("level_prefix_inventory_box_0003")
	if box then
		give_info("biznes_remove_special_item")
		db.actor:iterate_inventory(
			function(dummy,item)
				if not protected_items.actor_items_keep(item:section()) then
					db.actor:transfer_item(level_object(item:id()), box)
				end
			end
		,db.actor)
		create("zamok", xyz(0,0,0), 0, 0, box:id())
		disable_info("biznes_remove_special_item")
	end
	
	create_teleport("peshera_blok_tp",xyz(-112.609199523926,-9.9281539916992,-34.9218902587891),12288,2868)

	give_info("peshera_go")
	init_peshera_table()
	if level.get_game_difficulty() < 2 then
		snp.invul_on()
	end
end

function peshera_end()
	snp.invul_off()
	give_info("biznes_remove_special_item")
	db.actor:iterate_inventory(
		function(dummy,item)
			if not protected_items.actor_items_keep(item:section()) then
				release(server_object(item:id()))
			end
		end
	,db.actor)
	
	local obj
	init_peshera_table()
	for k,v in pairs(peshera_table) do
		obj = server_object(k)
		if obj and obj.parent_id ~= db.actor:id() and not protected_items.actor_items_keep(obj:section_name()) then
			release(obj)
		end
	end
	disable_info("biznes_remove_special_item")
	xr_logic.pstor_clear_custom(db.actor, "peshera_clear")

	for id,obj in pairs(db.creatures) do
		if obj and IAmAMonster[obj:clsid()] then
			release(server_object(id))
		end
	end

	for i=1,65535 do
		obj = server_object(i)
		if obj then
			if obj:section_name() == "af_part_monolit" or obj:section_name() == "m_inventory_box16" then
				release(obj)
			end
		end
	end

	delete_teleport("peshera_blok_tp")
	disable_info("peshera_go")
end

-- Поиск онлайнового объекта по его name в all.spawn
function obj_by_name(name)
	local obj
	for id=1, 65534 do
		obj = level_object(id)
		if obj and obj:name() == name then
--			console:execute("load ~~~ id:"..obj:id())
			return obj
		end
	end
end

function kuv_hit(who)
	if not db.actor:active_item() or not who or who:id() ~= db.actor:id() then return end

	local wpn = db.actor:active_item()
	local active_slot = db.actor:active_slot()
	
	-- Падение выносливости от кувалды
	if wpn:section() == "wpn_kuvalda" then
		db.actor.power = -level.get_game_difficulty()/10
	end

	-- Износ холодного оружия
	if active_slot == 0 then
		wpn:set_condition(wpn:condition()-level.get_game_difficulty()*0.001)
	end

	-- Поломка холодного оружия
	if active_slot == 0 then
		if wpn:condition() < 0.05 then
			amk.start_timer("run", 0.2, "kostya_dialog.remove_wpn("..tostring(wpn:id())..")")
		end
	
	-- Взрыв убитого ствола
	elseif wpn:condition() < 0.1 and math.random() < 0.2-wpn:condition()*2 and wpn:section() ~= "wpn_shmel" then
		amk_particle.amk_particle({
			particle="explosions\\explosion_fuelcan",
			pos=db.actor:position(),
			sound=[[weapons\t_rgd5_explosion]]
		})
		level.add_pp_effector("amk_shoot.ppe", 2011, false)

		local h = hit()
		h.draftsman = db.actor
		h.direction = vector_rotate_y(db.actor:direction(), 180) 
		h:bone("bip01_spine")
		h.type = hit.explosion
		h.power = 60
		h.impulse = 500
		db.actor:hit(h)

		amk.start_timer("run", 0.2, "kostya_dialog.remove_wpn("..tostring(wpn:id())..")")
	end
end
function remove_wpn(id)
	local obj = server_object(id)
	if obj then
		release(obj, true)
	end
end

-- Взносы
function vzn_begin()
	return db.actor:money()>=2000000 and
		has_info("sar_monolith_destroy")
end
function vzn()
	return
		db.actor:money()>=2000000 and
		has_info("vzn_begin") and 
		not	has_info("vzn_start") and 
		not	has_info("acv_vzn3") and 
		not (
			has_info("vzn1") and 
			has_info("vzn2") and 
			has_info("vzn3") and 
			has_info("vzn4") and 
			has_info("vzn5") and 
			has_info("vzn6") and 
			has_info("vzn7") and 
			has_info("vzn8") and 
			has_info("vzn9") and 
			has_info("vzn10") and 
			has_info("vzn11") and 
			has_info("vzn12") and 
			has_info("vzn13") and 
			has_info("vzn14") and 
			has_info("vzn15") and 
			has_info("vzn16")
		)
end
function vzn_end()
	return
		has_info("vzn1_done") and 
		has_info("vzn2_done") and 
		has_info("vzn3_done") and 
		has_info("vzn4_done") and 
		has_info("vzn5_done") and 
		has_info("vzn6_done") and 
		has_info("vzn7_done") and 
		has_info("vzn8_done") and 
		has_info("vzn9_done") and 
		has_info("vzn10_done") and 
		has_info("vzn11_done") and 
		has_info("vzn12_done") and 
		has_info("vzn13_done") and 
		has_info("vzn14_done") and 
		has_info("vzn15_done") and 
		has_info("vzn16_done")
end

function checking_taken_item_vzn(obj) -- взятие тайника
	local section = obj:section()
	if	section == "vzn_mogila" or
		section == "vzn_platok" or
		section == "vzn_vodka" or
		section == "vzn_prez_zapis" or
		section == "vzn_voen_zapis" or
		section == "vzn_ganteli" or
		section == "vzn_grob" or
		section == "vzn_rover" or
		section == "vzn_pesok" or
		section == "vzn_darwin" or
		section == "vzn_treasure_item" or
		section == "vzn_mladen" or
		section == "vzn_pensia" or
		section == "vzn_noty" or
		section == "vzn_kuvalda" then
			give_info("vzn_have")
	end
		
	if section == "vzn_treasure_item" then
		-- лотерея
		amk.remove_item_from_inventory_by_name("vzn_treasure_item",db.actor)
		amk.spawn_item_in_inv("treasure_item", db.actor)
		amk.spawn_item_in_inv("vzn_medal", db.actor)
		amk.spawn_item_in_inv(vzn_taynik_stvol(), db.actor)
	end
	if section == "vzn_mladen" then
		-- младенец
		local snd = voice([[characters_voice\scenario\trader\plach]])
		snd:stop()
		snd:play_no_feedback(db.actor, sound_object.s2d, 1.0, vector(), 1.0)
	end
end
function vzn_fill(vzn) -- создание тайника
	if     vzn == 11 then
		-- контрик
		create("vzn_stalker_kontrik",xyz(-209.23837280273,-20.614948272705,-149.44313049316),43943,61)
		lost_money(450000)
	elseif vzn == 12 then
		-- лотерея
		spawn_restrictor.vzn12_restr()
		lost_money(100000)
	else
		-- спавним тайник и получаем ссылку на него
		local obj = taynik_spawn.vzn_taynik()
		
		-- Наполняем тайник
		vzn_fill_taynik(vzn_taynik_stvol(), 1, obj)
		
		if     vzn == 1 then
			vzn_fill_taynik("vzn_venok", 10, obj)
			vzn_fill_taynik("vzn_lopata", 2, obj)
			vzn_fill_taynik("vzn_mogila", 1, obj)
			lost_money(200000)
		elseif vzn == 2 then
			vzn_fill_taynik("vzn_platok", 100, obj)
			lost_money(300000)
		elseif vzn == 3 then
			vzn_fill_taynik("vodka", 100, obj)
			vzn_fill_taynik("vzn_vodka", 1, obj)
			lost_money(400000)
		elseif vzn == 4 then
			if     has_info("vzn_temp1") then
				vzn_fill_taynik("vzn_prez", 1, obj)
				vzn_fill_taynik("vzn_stirka", 1, obj)
				vzn_fill_taynik("vzn_vivarka", 1, obj)
				vzn_fill_taynik("vzn_polovnik", 1, obj)
			elseif has_info("vzn_temp2") then
				vzn_fill_taynik("vzn_prez", 2, obj)
				vzn_fill_taynik("vzn_stirka", 2, obj)
				vzn_fill_taynik("vzn_vivarka", 2, obj)
				vzn_fill_taynik("vzn_polovnik", 2, obj)
			elseif has_info("vzn_temp3") then
				vzn_fill_taynik("vzn_prez", 3, obj)
				vzn_fill_taynik("vzn_stirka", 3, obj)
				vzn_fill_taynik("vzn_vivarka", 3, obj)
				vzn_fill_taynik("vzn_polovnik", 3, obj)
			end
			vzn_fill_taynik("vzn_prez_zapis", 1, obj)
			lost_money(650000)
		elseif vzn == 5 then
			vzn_fill_taynik("voen_exo_outfit", 12, obj)
			vzn_fill_taynik("vzn_voen_zapis", 1, obj)
			lost_money(350000)
		elseif vzn == 6 then
			vzn_fill_taynik("vzn_ganteli", 1, obj)
			vzn_fill_taynik("vzn_gira", 2, obj)
			lost_money(200000)
		elseif vzn == 7 then
			vzn_fill_taynik("vzn_grob", 1, obj)
			lost_money(300000)
		elseif vzn == 8 then
			vzn_fill_taynik("vzn_rover", 1, obj)
			lost_money(800000)
		elseif vzn == 9 then
			vzn_fill_taynik("vzn_pesok", 3, obj)
			lost_money(500000)
		elseif vzn == 10 then
			vzn_fill_taynik("vzn_darwin", 1, obj)
			vzn_fill_taynik("vzn_darwin_zapis", 1, obj)
			lost_money(250000)
		elseif vzn == 13 then
			vzn_fill_taynik("vzn_mladen", 3, obj)
			lost_money(300000)
			voice([[characters_voice\scenario\trader\plach]]):play_at_pos(db.actor, obj.position, 0, sound_object.s3d+sound_object.looped)
		elseif vzn == 14 then
			vzn_fill_taynik("vzn_pensia", 1, obj)
			vzn_fill_taynik("vzn_polis", 1, obj)
			lost_money(250000)
		elseif vzn == 15 then
			vzn_fill_taynik("balalaika_a", 1, obj)
			vzn_fill_taynik("guitar_a", 1, obj)
			vzn_fill_taynik("harmonica_a", 1, obj)
			vzn_fill_taynik("vzn_torch", 1, obj)
			vzn_fill_taynik("vzn_noty", 1, obj)
			lost_money(400000)
		elseif vzn == 16 then
			vzn_fill_taynik("vzn_kuvalda", 1, obj)
			vzn_fill_taynik("vzn_krovosos_cocoon", 1, obj)
			lost_money(50000)
		end
	end

	give_info("vzn"..tostring(vzn))
	give_info("vzn_start")
end
function vzn_fill_taynik(section, cnt, obj)
	for i = 1,cnt do
		spawn_item_in_taynik(section, obj)
	end
end
function spawn_item_in_taynik(section, box)
	local item = create(section, xyz(0,0,0), 0, 0, box.id)
	level.client_spawn_manager():add(item.id, -1, fix_spawn_item_in_taynik, box)
end
function fix_spawn_item_in_taynik(box, id, item)
	local online_box = level_object(box.id) -- к моменту выхода предмета в онлайн box уже в онлайне
    online_box:transfer_item(item, online_box)
end

function vzn_done(vzn) -- удаление уникального хабара
	if     vzn == 1 then
		lost_all("vzn_venok")
		lost_all("vzn_lopata")
		lost_all("vzn_mogila")
	elseif vzn == 2 then
		lost_all("vzn_platok")
	elseif vzn == 3 then
		lost_all("vzn_vodka")
	elseif vzn == 4 then
		lost_all("vzn_prez")
		lost_all("vzn_prez_zapis")
		lost_all("vzn_stirka")
		lost_all("vzn_vivarka")
		lost_all("vzn_polovnik")
	elseif vzn == 5 then
		lost_all("vzn_voen_zapis")
	elseif vzn == 6 then
		lost_all("vzn_ganteli")
		lost_all("vzn_gira")
	elseif vzn == 7 then
		lost_all("vzn_grob")
	elseif vzn == 8 then
		lost_all("vzn_rover")
	elseif vzn == 9 then
		lost_all("vzn_pesok")
	elseif vzn == 10 then
		play_tush()
		lost_all("vzn_darwin")
		lost_all("vzn_darwin_zapis")
		got_money(300000)
	elseif vzn == 12 then
		lost_all("vzn_medal")
	elseif vzn == 13 then
		lost_all("vzn_mladen")
	elseif vzn == 14 then
		lost_all("vzn_pensia")
		lost_all("vzn_polis")
	elseif vzn == 15 then
		lost_all("vzn_torch")
		lost_all("vzn_noty")
		got_money(200000)
	elseif vzn == 16 then
		lost_all("vzn_kuvalda")
		lost_all("vzn_krovosos_cocoon")
	end

	give_info("vzn"..tostring(vzn).."_done")
	disable_info("vzn_start")
	disable_info("vzn_have")
	disable_info("vzn_temp1")
	disable_info("vzn_temp2")
	disable_info("vzn_temp3")
	disable_info("vzn_temp4")
end
function vzn_taynik_stvol()
	local vzn_stvol = {
		"wpn_benelli_m3_tactik",
		"wpn_akms_m1",
		"wpn_fn_fal_c1",
		"wpn_kord_m1",
		"wpn_vepr12_col",
		"wpn_vepr12_20",
		"wpn_svd_m3",
		"grenade_f1",
		"wpn_pm",
		"wpn_crowbar",
		"wpn_bm16",
		"wpn_fist_m",
		"wpn_kuvalda",
		"wpn_topor",
		"wpn_mp5"
	}
	local i
	-- Ищем неиспользованный ствол
	repeat
		i = math.random(#vzn_stvol)
	until not has_info("vzn_stvol"..tostring(i))
	
	give_info("vzn_stvol"..tostring(i))
	return vzn_stvol[i]
end

function vzn1()			vzn_fill(1) end
function vzn1_done()	vzn_done(1) end
function vzn2() 		vzn_fill(2) end
function vzn2_done()	vzn_done(2) end
function vzn3() 		vzn_fill(3) end
function vzn3_done()	vzn_done(3) end
function vzn4()			vzn_fill(4) end
function vzn4_done()	vzn_done(4) end
function vzn5()			vzn_fill(5) end
function vzn5_done()	vzn_done(5) end
function vzn6()			vzn_fill(6) end
function vzn6_done()	vzn_done(6) end
function vzn7()			vzn_fill(7) end
function vzn7_done()	vzn_done(7) end
function vzn8()			vzn_fill(8) end
function vzn8_done()	vzn_done(8) end
function vzn9()			vzn_fill(9) end
function vzn9_done()	vzn_done(9) end
function vzn10()		vzn_fill(10) end
function vzn10_done()	vzn_done(10) end
function vzn11()		vzn_fill(11) end
function vzn11_done()	vzn_done(11) end
function vzn12()		vzn_fill(12) end
function vzn12_done()	vzn_done(12) end
function vzn13()		vzn_fill(13) end
function vzn13_done()	vzn_done(13) end
function vzn14()		vzn_fill(14) end
function vzn14_done()	vzn_done(14) end
function vzn15()		vzn_fill(15) end
function vzn15_done()	vzn_done(15) end
function vzn16()		vzn_fill(16) end
function vzn16_done()	vzn_done(16) end

function play_tush()
	give_info("sidor_tush")
	amk.start_timer("stop_tush", 18.3, 0)
end
function give_ak_strelka()
	got("wpn_ak104t",1)
end
function play_video_strelok()
  game.start_tutorial("intro_game_2")
end
function play_video_kontrik()
  game.start_tutorial("death_machine_dream_2")
end
function play_video_good_end()
  game.start_tutorial("mov_refuse_osoznanie_2")
end
function actor_vzn_back()
	got_money(5500000)
	play_tush()
	give_info("vzn_reset")
	disable_info("vzn_reset")
end
function gg_monolit()
	db.actor:set_character_community("monolith", 0, 0)
end
-- Взносы end

-- рандомная выдача редких патронов qty раз
function give_ammo(qty)
	local ammo = {
		"ammo_gauss",
		"ammo_minigun",
		"ammo_12x70_kart",
		"ammo_357_ap_mag",
		"ammo_12.7x108",
		"ammo_12.7x55_fmj",
		"ammo_12.7x55_ap",
		"ammo_zhekan_izomorf",
		"ammo_9x39_izomorf",
		"ammo_5.45x39_izomorf"
	}
	for i =1,qty do
		got(ammo[math.random(#ammo)],1)
	end
end

function checking_taken_item63(obj)
	if not (string.sub(obj:section(),1,7)=="tm_docs") then return end 
	
	if has("tm_docs01") and has("tm_docs02") and has("tm_docs03") and has("tm_docs04") and has("tm_docs05") and has("tm_docs06") and has("tm_docs07") and has("tm_docs08") and has("tm_docs09") and has("tm_docs10") and has("tm_docs11") and has("tm_docs12") and has("tm_docs13") then
		if not has_info("tm_find_all") then 
			give_info("tm_find_all")
			sms("%c[255,160,160,160]".."ДРАГУНОВ:".."\\n".."%c[255,255,128,128]Стрелок, пока ты искал записки, я думал над той наводкой, что можно составить из этих слов. У меня получилось следующее:\\nНезыблемое Прекрасное Вечное Озаряет Нас Дарит Покой Счастье Мир Найди Путь Стань Бессмертным\\nОчевидно, что речь идёт об Исполнителе Желаний. Но где там тайник? И ещё: в наводке говорится, что нужно найти путь. Так что, Стрелок, похоже, это не всё. Я вижу новый телепорт в центре Саркофага. Думаю, стоит начать с него.", nil, nil, 30000)
			this.tm_done1()
			spawn_tm_taynik()
			local se_obj = create("tm_teleport_1",xyz(24.6673412323,56.192798614502,-5.0582308769226),5907,2417)
			xr_logic.pstor_store(db.actor, "tm_teleport_1", se_obj.id)		  
			se_obj = create("tm_teleport_2",xyz(23.798603057861,70.392623901367,45.316135406494),5395,2417)
			xr_logic.pstor_store(db.actor, "tm_teleport_2", se_obj.id)		  
			spawn_restrictor.tm_sr1()
		end
	end
end
function tm_spawn1()
	create("z_inventory_box01",xyz(10.472078323364,49.034076690674,-15.613767623901),3388,2417)
	create("z_inventory_box02",xyz(19.680177688599,48.432109832764,-4.1294741630554),4341,2417)
	create("z_inventory_box03",xyz(3.4836528301239,56.036026000977,35.414047241211),2518,2405)
	create("z_inventory_box04",xyz(60.87622833252,53.735683441162,26.076965332031),9266,2417)
	create("z_inventory_box05",xyz(60.85319519043,53.796840667725,21.076036453247),9788,2417)
	create("z_inventory_box06",xyz(61.789813995361,60.531970977783,41.451103210449),9966,2402)
	create("z_inventory_box07",xyz(9.1720209121704,20.386127471924,-11.211741447449),6333,2453)
	create("z_inventory_box08",xyz(44.268180847168,58.320827484131,-24.319999694824),8050,2417)
	create("z_inventory_box09",xyz(-19.819829940796,64.045745849609,-31.615013122559),591,2417)
	create("z_inventory_box10",xyz(80.993240356445,71.973617553711,-40.810508728027),6403,2417)
	create("z_inventory_box11",xyz(42.494750976563,69.035263061523,38.658748626709),4591,2417)
	create("z_inventory_box12",xyz(64.846755981445,67.564109802246,45.584968566895),4591,2417)
	create("z_inventory_box13",xyz(51.092010498047,49.359004974365,-17.654895782471),8798,2416)
end
function tm_done1()
 	amk.remove_item_from_inventory_by_name("tm_docs01",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs02",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs03",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs04",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs05",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs06",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs07",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs08",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs09",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs10",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs11",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs12",db.actor)
 	amk.remove_item_from_inventory_by_name("tm_docs13",db.actor)
end
function checking_taken_item64(obj)
	if obj:section() == "tm_docs14" then
		give_info("tm_find_done")
		this.delete_teleport("tm_teleport_4")
		sms("Найдена информация.", nil, nil, 20000)
		create("z_inventory_box15",xyz(84.50724029541,69.478454589844,-7.1580576896667),6048,2417)
		amk.drop_item(db.actor,obj)
		amk.remove_item(obj)
	end
end
function spawn_tm_taynik()
	create("z_inventory_box14",xyz(23.798603057861,70.392623901367,45.316135406494),5395,2417)
end
function remove_tm_taynik()
	release(snp.object_by_section_offline("z_inventory_box14"))
end

-- универсальная процедура спавна телепортов
function create_teleport(section, pos, lv, gv)
    local se_obj = create(section, pos, lv, gv)
	xr_logic.pstor_store(db.actor, section, se_obj.id)
	return se_obj
end
-- универсальная процедура удаления телепортов
function delete_teleport(section)
	local se_obj = server_object(xr_logic.pstor_retrieve(db.actor, section, -1, true))
	if se_obj then
		release(se_obj, true)
	end
end

function feed_actor()   -- кормим перед сном
	se_obj = create("kolbasa_sleep",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
	amk.start_timer("sleep_feed_actor",0.1,0)
end
function sleep_feed_actor()
	db.actor:eat(db.actor:object("kolbasa_sleep"))
end

-- Proper71 docs
-- Вниманию оптимизаторов: в разделе docs ничего не оптимизировать! Даже не трогать порядок выполнения команд! Из-за использования disable в поршнях и некоторых глюков из-за параллельного выполнения процессов в движке не все работает так, как кажется на первый взгляд. Поэтому ничего здесь не трогайте.
function checking_taken_item61(obj)
	if string.find(obj:section(),"zonedocs") then
		give_info("zonedocs_have"..string.sub(obj:section(),string.find(obj:section(),"_")+1))

		local total = 60
		if     has_info("voronin_docs1_start_as") then
			total = 24
		elseif has_info("voronin_docs1_start_yan") then
			total = 23
		elseif has_info("voronin_docs1_start_dt") then
			total = 22
		elseif has_info("voronin_docs1_start_atp") then
			total = 15
		elseif has_info("voronin_docs1_start_td") then
			total = 30
		elseif has_info("voronin_docs1_start_puzir") then
			total = 6
		elseif has_info("voronin_docs1_start_agro") then
			total = 26
		elseif has_info("voronin_docs1_start_marsh") then
			total = 30
		elseif has_info("voronin_docs1_start_esc") then
			total = 60
		elseif has_info("voronin_docs1_start_garbage") then
			total = 60
		elseif has_info("voronin_docs1_start_bar") then
			total = 60
		end
		
		if     has("zone_docs",total-1) then
			give_info("voronin_docs1_have")
		elseif has("zone_docs",total-3) then
			give_info("voronin_docs1_almost_have")
		end
		
		amk.remove_item_from_inventory(obj,db.actor)
		-- удаляем дубликаты
		if  (obj:section()=="zonedocs_26" and level.name() == "l03u_agr_underground") or 
			(obj:section()=="zonedocs_22" and (level.name() == "l06_rostok" or level.name() == "l05_bar"))
		then
			local sobj
			for i = 1,65534 do
				sobj = server_object(i)
				if sobj then
					if  (sobj:section_name() == "zonedocs_26" and level.name() == "l03u_agr_underground") or 
						(sobj:section_name() == "zonedocs_22" and (level.name() == "l06_rostok" or level.name() == "l05_bar"))
					then
						release(sobj,true)
						break
					end
				end
			end
		end
		
		create("zone_docs",xyz(0,0,0),0,0,0)
	end
end

function zonedocs_buy()
	got("zonedocs_0",1)
	give_info("acv_docs_fail")
end

function voronin_docs1_done()
	lost_all("zone_docs")
	god_docs_off()
	if not has_info("voronin_docs1_have") then -- удаляем ненайденные части
		local sobj
		for i = 1,65534 do
			sobj = server_object(i)
			if sobj and string.find(sobj:name(),"zonedocs") then
				release(sobj,true)
			end
		end
	end
	
	if     has_info("voronin_docs1_start_as") then
		if has_info("voronin_docs1_have") then
			give_info("voronin_docs1_done_as")
		else
			give_info("voronin_docs1_fail_as")
			give_info("acv_docs_fail")
		end
	elseif has_info("voronin_docs1_start_yan") then
		if has_info("voronin_docs1_have") then
			give_info("voronin_docs1_done_yan")
		else
			give_info("voronin_docs1_fail_yan")
			give_info("acv_docs_fail")
		end
	elseif has_info("voronin_docs1_start_dt") then
		if has_info("voronin_docs1_have") then
			give_info("voronin_docs1_done_dt")
		else
			give_info("voronin_docs1_fail_dt")
			give_info("acv_docs_fail")
		end
	elseif has_info("voronin_docs1_start_atp") then
		if has_info("voronin_docs1_have") then
			give_info("voronin_docs1_done_atp")
		else
			give_info("voronin_docs1_fail_atp")
			give_info("acv_docs_fail")
		end
	elseif has_info("voronin_docs1_start_td") then
		if has_info("voronin_docs1_have") then
			give_info("voronin_docs1_done_td")
		else
			give_info("voronin_docs1_fail_td")
			give_info("acv_docs_fail")
		end
	elseif has_info("voronin_docs1_start_puzir") then
		if has_info("voronin_docs1_have") then
			give_info("voronin_docs1_done_puzir")
		else
			give_info("voronin_docs1_fail_puzir")
			give_info("acv_docs_fail")
		end
	elseif has_info("voronin_docs1_start_agro") then
		if has_info("voronin_docs1_have") then
			give_info("voronin_docs1_done_agro")
		else
			give_info("voronin_docs1_fail_agro")
			give_info("acv_docs_fail")
		end
	elseif has_info("voronin_docs1_start_marsh") then
		if has_info("voronin_docs1_have") then
			give_info("voronin_docs1_done_marsh")
		else
			give_info("voronin_docs1_fail_marsh")
			give_info("acv_docs_fail")
		end
	elseif has_info("voronin_docs1_start_esc") then
		if has_info("voronin_docs1_have") then
			give_info("voronin_docs1_done_esc")
		else
			give_info("voronin_docs1_fail_esc")
			give_info("acv_docs_fail")
		end
	elseif has_info("voronin_docs1_start_garbage") then
		if has_info("voronin_docs1_have") then
			give_info("voronin_docs1_done_garbage")
		else
			give_info("voronin_docs1_fail_garbage")
			give_info("acv_docs_fail")
		end
	elseif has_info("voronin_docs1_start_bar") then
		if has_info("voronin_docs1_have") then
			give_info("voronin_docs1_done_bar")
		else
			give_info("voronin_docs1_fail_bar")
			give_info("acv_docs_fail")
		end
	end
	
	if has_info("zonedocs_have0") then
		give_info("acv_docs_fail")
	end
	if has_info("voronin_docs1_have") then
		this.give_ammo(3)
	end
	give_info("voronin_docs1_reset")
end

function voronin_docs1_refuse()
	lost_all("zone_docs")
	god_docs_off()
	if not has_info("voronin_docs1_have") then -- удаляем ненайденные части
		local sobj
		for i = 1,65534 do
			sobj = server_object(i)
			if sobj and string.find(sobj:name(),"zonedocs") then
				release(sobj,true)
			end
		end
	end
	
	give_info("voronin_docs1_done_as")
	give_info("voronin_docs1_done_yan")
	give_info("voronin_docs1_done_dt")
	give_info("voronin_docs1_done_atp")
	give_info("voronin_docs1_done_td")
	give_info("voronin_docs1_done_puzir")
	give_info("voronin_docs1_done_agro")
	give_info("voronin_docs1_done_marsh")
	give_info("voronin_docs1_done_esc")
	give_info("voronin_docs1_done_garbage")
	give_info("voronin_docs1_done_bar")
	give_info("voronin_docs1_end_refuse")
	give_info("acv_docs_fail")
	give_info("voronin_docs1_reset")
end

function t_zonedocs_bar()
	taynik_spawn.t_zonedocs("bar")
end
function t_zonedocs_garbage()
	taynik_spawn.t_zonedocs("garbage")
end
function t_zonedocs_esc()
	taynik_spawn.t_zonedocs("esc")
end
function t_zonedocs_marsh()
	taynik_spawn.t_zonedocs("marsh")
end
function t_zonedocs_agro()
	taynik_spawn.t_zonedocs("agro")
end
function t_zonedocs_puzir()
	taynik_spawn.t_zonedocs("puzir")
end
function t_zonedocs_td()
	taynik_spawn.t_zonedocs("td")
end
function t_zonedocs_atp()
	taynik_spawn.t_zonedocs("atp")
end
function t_zonedocs_dt()
	taynik_spawn.t_zonedocs("dt")
end
function t_zonedocs_yan()
	taynik_spawn.t_zonedocs("yan")
end
function t_zonedocs_as()
	taynik_spawn.t_zonedocs("as")
end

function zonedocs_gg_kill()
	db.actor:kill(db.actor)
end
function zonedocs_gg_reward()
	this.give_ammo(30)
	got("wpn_vitjaz_sn",1)
	got("wpn_pp2000",1)
	got("wpn_kac_pdw",1)
	got("wpn_kedr",1)
	got("wpn_sayga_un",1)
	got("wpn_bren_ten_cr",1)
	got("af_pero",1)
	archievements.acv_docs()
end

function add_docs_spot()
	for i=1,65534 do
		obj = server_object(i)

		if obj and string.find(obj:section_name(), "zonedocs") then
			level.map_add_object_spot_ser(obj.id, "profi", "Документ Воронина")
			db.god.c[5] = db.god.c[5]+1
		end
	end
end

function remove_docs_spot()
	for i=1,65534 do
		obj = server_object(i)

		if obj and string.find(obj:section_name(), "zonedocs") and level.map_has_object_spot(obj.id, "profi") ~= 0 then
			level.map_remove_object_spot(obj.id, "profi")
		end
	end
end

function god_docs_off()
	db.god.u[5] = false
	ui_mm_opt_main.GodHudUpdate()
end

function kostya_biznes1_have_all()
	return
		has("af_buliz",5)
end		
function kostya_biznes1_have()
	if kostya_biznes1_have_all() then
		give_info("kostya_biznes1_have")
		return true
	else
		return false
	end
end
function kostya_biznes1_done()
		lost("af_buliz",5)
	give_info("info_amk_recipt_power_2")
end

function sidor_biznes_over()
	return not (
		has_info("sidor_biznes1_done") and 
		has_info("sidor_biznes2_done") and 
		has_info("sidor_biznes3_done") and 
		has_info("sidor_biznes4_done") and
		has_info("sidor_biznes5_done") and
		has_info("sidor_biznes6_done") and
		has_info("sidor_biznes7_done")
	)
end

function sidor_biznes1_have_all()
	return has_info("sidor_biznes1_start") and
		has("part_bear_paw",2) and
		has("part_winger_liver",2) and
		has("part_nosales_tongue",2) and
		has("part_fang_wolf",2) and
		has("part_spider_gland",2) and
		has("part_rotan_heart",2) and
		has("part_plague_hand",2) and
		has("part_carlic_hand",2) and
		has("part_raptor_kogot",2) and
		has("part_zanoza_leg",2) and
		has("part_flesh_eye",2) and
		has("part_boar_leg",2) and
		has("part_dog_tail",2) and
		has("part_psevdodog_tail",2) and
		has("part_krovosos_jaw",2) and
		has("part_burer_hand",2) and
		has("part_zombie_hand",2) and
		has("part_snork_leg",2) and
		has("part_face_tushkano",2) and
		has("part_hand_kontroler",2) and
		has("part_poltergeist_glas",2) and
		has("part_psevdogigant_hand",2) and
		has("part_tail_cat",2) and
		has("part_chimera_kogot",2) and
		has("part_fracture_hand",2) and
		has("part_deathclaw_antler",2) and
		has("part_digitis_biblio",2) and
		has("part_vypolzen_hrebet",2) and
		has("part_tarakan",2) and
		has("part_tarakan_strong",2) and
		has("part_zombie_teeth",2) and
		has("part_spleen_rat",2) and
		has("part_krovosos_red_jaw",1) and
		has("part_burer_red_hand",1) and
		has("bezoar",2) and
		has("mushroom",2) and
		has("bread_a",2)
end		
function sidor_biznes1_have()
	if sidor_biznes1_have_all() then
		give_info("sidor_biznes1_have")
		return true
	else
		return false
	end
end
function sidor_biznes1_done()
		lost("part_bear_paw",2)
		lost("part_winger_liver",2)
		lost("part_nosales_tongue",2)
		lost("part_fang_wolf",2)
		lost("part_spider_gland",2)
		lost("part_rotan_heart",2)
		lost("part_plague_hand",2)
		lost("part_carlic_hand",2)
		lost("part_raptor_kogot",2)
		lost("part_zanoza_leg",2)
		lost("part_flesh_eye",2)
		lost("part_boar_leg",2)
		lost("part_dog_tail",2)
		lost("part_psevdodog_tail",2)
		lost("part_krovosos_jaw",2)
		lost("part_burer_hand",2)
		lost("part_zombie_hand",2)
		lost("part_snork_leg",2)
		lost("part_face_tushkano",2)
		lost("part_hand_kontroler",2)
		lost("part_poltergeist_glas",2)
		lost("part_psevdogigant_hand",2)
		lost("part_tail_cat",2)
		lost("part_chimera_kogot",2)
		lost("part_fracture_hand",2)
		lost("part_deathclaw_antler",2)
		lost("part_digitis_biblio",2)
		lost("part_vypolzen_hrebet",2)
		lost("part_tarakan",2)
		lost("part_tarakan_strong",2)
		lost("part_zombie_teeth",2)
		lost("part_spleen_rat",2)
		lost("part_krovosos_red_jaw",1)
		lost("part_burer_red_hand",1)
		lost("bezoar",2)
		lost("mushroom",2)
		lost("bread_a",2)
	this.give_ammo(10)
	got("af_power",1)
	got("cube_chip",1)
end

function sidor_biznes2_have_all()
	return has_info("sidor_biznes2_start") and
		has("af_dummy_battery_red",3) and
		has("af_dummy_spring_red",3) and
		has("af_dummy_pellicle_red",3) and
		has("af_caterpillar",4) and
		has("af_simbion",2) and
		has("af_arhara_globus",1) and
		has("bread_a",3)
end
function sidor_biznes2_have()
	if sidor_biznes2_have_all() then
		give_info("sidor_biznes2_have")
		return true
	else
		return false
	end
end
function sidor_biznes2_done()
		lost("af_dummy_battery_red",3)
		lost("af_dummy_spring_red",3)
		lost("af_dummy_pellicle_red",3)
		lost("af_caterpillar",4)
		lost("af_simbion",2)
		lost("af_arhara_globus",1)
		lost("bread_a",3)
	this.give_ammo(5)
	got("cube_chip",1)
	give_info("info_amk_recipt_power_3")
end

function sidor_biznes3_have_all()
	return has_info("sidor_biznes3_start") and
		has("af_buliz",15) and
		has("af_drops",1) and
		has("af_cry_1",1) and
		has("af_cry_2",1) and
		has("af_cry_3",2) and
		has("af_dummy_glassbeads",1) and
		has("af_babka_1",1) and
		has("af_babka_2",1) and
		has("af_babka_3",2) and
		has("af_babka_4",2) and
		has("af_rusty_sea-urchin",1) and
		has("af_dik_1",1) and
		has("af_dik_2",1) and
		has("af_dik_3",2) and
		has("af_dik_4",2) and
		has("af_soul",1) and
		has("af_spirit_1",1) and
		has("af_spirit_2",1) and
		has("af_spirit_3",2) and
		has("af_spirit_4",2) and
		has("af_dummy_pellicle",1) and
		has("af_armor_1",1) and
		has("af_armor_2",1) and
		has("af_armor_3",2) and
		has("af_armor_4",2) and
		has("af_dummy_dummy",1) and
		has("af_pudd_1",1) and
		has("af_pudd_2",1) and
		has("af_pudd_3",2) and
		has("af_pudd_4",2) and
		has("af_fuzz_kolobok",1) and
		has("af_kol_1",1) and
		has("af_kol_2",1) and
		has("af_kol_3",2) and
		has("af_kol_4",2)
end
function sidor_biznes3_have()
	if sidor_biznes3_have_all()	then
		give_info("sidor_biznes3_have")
		return true
	else
		return false
	end
end
function sidor_biznes3_done()
		lost("af_buliz",15)
		lost("af_drops",1)
		lost("af_cry_1",1)
		lost("af_cry_2",1)
		lost("af_cry_3",2)
		lost("af_dummy_glassbeads",1)
		lost("af_babka_1",1)
		lost("af_babka_2",1)
		lost("af_babka_3",2)
		lost("af_babka_4",2)
		lost("af_rusty_sea-urchin",1)
		lost("af_dik_1",1)
		lost("af_dik_2",1)
		lost("af_dik_3",2)
		lost("af_dik_4",2)
		lost("af_soul",1)
		lost("af_spirit_1",1)
		lost("af_spirit_2",1)
		lost("af_spirit_3",2)
		lost("af_spirit_4",2)
		lost("af_dummy_pellicle",1)
		lost("af_armor_1",1)
		lost("af_armor_2",1)
		lost("af_armor_3",2)
		lost("af_armor_4",2)
		lost("af_dummy_dummy",1)
		lost("af_pudd_1",1)
		lost("af_pudd_2",1)
		lost("af_pudd_3",2)
		lost("af_pudd_4",2)
		lost("af_fuzz_kolobok",1)
		lost("af_kol_1",1)
		lost("af_kol_2",1)
		lost("af_kol_3",2)
		lost("af_kol_4",2)
	this.give_ammo(30)
	got("wpn_m_134",1)
	got("wpn_pkm",1)
	got("cube_chip",1)
end

function sidor_biznes4_have_all()
	return has_info("sidor_biznes4_start") and
		has_good("wpn_gauss",6) and
		has("ammo_gauss",10) and
		has("ammo_super_gauss",15) and
		has_good("wpn_rpg7",3) and
		has("ammo_og-7b",30)
end
function sidor_biznes4_have()
	if sidor_biznes4_have_all() then
		give_info("sidor_biznes4_have")
		return true
	else
		return false
	end
end
function sidor_biznes4_done()
		lost_good("wpn_gauss",6)
		lost("ammo_gauss",10)
		lost("ammo_super_gauss",15)
		lost_good("wpn_rpg7",3)
		lost("ammo_og-7b",30)
	this.give_ammo(10)
	got("wpn_m_134",1)
	got("wpn_pkm",1)
	got("scientist_suit_white",1)
	got("cube_chip",1)
end

function sidor_biznes5_have_all()
	return has_info("sidor_biznes5_start") and
		has_good("broken_exoskeleton",2) and
		has_good("voen_exo_outfit",2) and
		has_good("exo_outfit",2) and
		has_good("killer_blue_exoskeleton",2) and
		has_good("monolit_exoskeleton",2) and
		has_good("svoboda_exoskeleton",2) and
		has_good("dolg_black_exoskeleton",2) and
		has_good("nebo_exo_outfit",2) and
		has_good("exo_bandit_outfit",2) and
		has_good("exo_scientist_outfit",2) and
		has_good("nano_outfit",1)
end
function sidor_biznes5_have()
	if sidor_biznes5_have_all() then
		give_info("sidor_biznes5_have")
		return true
	else
		return false
	end
end
function sidor_biznes5_done()
		lost_good("broken_exoskeleton",2)
		lost_good("voen_exo_outfit",2)
		lost_good("exo_outfit",2)
		lost_good("killer_blue_exoskeleton",2)
		lost_good("monolit_exoskeleton",2)
		lost_good("svoboda_exoskeleton",2)
		lost_good("dolg_black_exoskeleton",2)
		lost_good("nebo_exo_outfit",2)
		lost_good("exo_bandit_outfit",2)
		lost_good("exo_scientist_outfit",2)
		lost_good("nano_outfit",1)
	this.give_ammo(10)
	got("wpn_m_134",1)
	got("wpn_vepr12_m1",1)
	got("cube_chip",1)
end

function sidor_biznes6_have_all()
	return has_info("sidor_biznes6_start") and
		has_good("wpn_crossbow",5) and
		has("ammo_arbolt",15) and
		has_good("wpn_awm",5) and
		has("ammo_igl",15) and
		has_good("wpn_svd",2) and
		has_good("wpn_svu",2) and
		has("ammo_7.62x54_7h1",16) and
		has("ammo_7.62x54_7h14",16) and
		has("ammo_7.62x54_ap",16) and
		has_good("wpn_vintorez",5) and
		has("ammo_9x39_sp5",5) and
		has("ammo_9x39_ap",5) and
		has("ammo_9x39_pab9",5)
end
function sidor_biznes6_have()
	if sidor_biznes6_have_all() then
		give_info("sidor_biznes6_have")
		return true
	else
		return false
	end
end
function sidor_biznes6_done()
		lost_good("wpn_crossbow",5)
		lost("ammo_arbolt",15)
		lost_good("wpn_awm",5)
		lost("ammo_igl",15)
		lost_good("wpn_svd",2)
		lost_good("wpn_svu",2)
		lost("ammo_7.62x54_7h1",16)
		lost("ammo_7.62x54_7h14",16)
		lost("ammo_7.62x54_ap",16)
		lost_good("wpn_vintorez",5)
		lost("ammo_9x39_sp5",5)
		lost("ammo_9x39_ap",5)
		lost("ammo_9x39_pab9",5)
	this.give_ammo(10)
	got("wpn_m_134",1)
	got("wpn_aks74_m2",1)
	got("cube_chip",1)
end
function sidor_biznes7_have_all()
	return has_info("sidor_biznes7_start") and
		has("part_bear_paw",5) and
		has("part_winger_liver",5) and
		has("part_nosales_tongue",5) and
		has("part_fang_wolf",5) and
		has("part_spider_gland",5) and
		has("part_rotan_heart",5) and
		has("part_plague_hand",5) and
		has("part_carlic_hand",5) and
		has("part_raptor_kogot",5) and
		has("part_zanoza_leg",5) and
		has("part_boar_leg",10) and
		has("part_dog_tail",10) and
		has("part_psevdodog_tail",20) and
		has("part_krovosos_jaw",10) and
		has("part_zombie_hand",20) and
		has("part_snork_leg",10) and
		has("part_face_tushkano",20) and
		has("part_hand_kontroler",20) and
		has("part_psevdogigant_hand",10) and
		has("part_tail_cat",10) and
		has("part_chimera_kogot",20) and
		has("part_fracture_hand",20) and
		has("part_deathclaw_antler",10) and
		has("part_digitis_biblio",10) and
		has("part_vypolzen_hrebet",10) and
		has("part_tarakan",6) and
		has("part_tarakan_strong",20) and
		has("part_zombie_teeth",10) and
		has("part_rudiment_big",3) and
		has("part_spleen_rat",20) and
		has("mozg",6) and
		has("bezoar",6) and
		has("bread_a",8)
end		
function sidor_biznes7_have()
	if sidor_biznes7_have_all() then
		give_info("sidor_biznes7_have")
		return true
	else
		return false
	end
end
function sidor_biznes7_done()
		lost("part_bear_paw",5)
		lost("part_winger_liver",5)
		lost("part_nosales_tongue",5)
		lost("part_fang_wolf",5)
		lost("part_spider_gland",5)
		lost("part_rotan_heart",5)
		lost("part_plague_hand",5)
		lost("part_carlic_hand",5)
		lost("part_raptor_kogot",5)
		lost("part_zanoza_leg",5)
		lost("part_boar_leg",10)
		lost("part_dog_tail",10)
		lost("part_psevdodog_tail",20)
		lost("part_krovosos_jaw",10)
		lost("part_zombie_hand",20)
		lost("part_snork_leg",10)
		lost("part_face_tushkano",20)
		lost("part_hand_kontroler",20)
		lost("part_psevdogigant_hand",10)
		lost("part_tail_cat",10)
		lost("part_chimera_kogot",20)
		lost("part_fracture_hand",20)
		lost("part_deathclaw_antler",10)
		lost("part_digitis_biblio",10)
		lost("part_vypolzen_hrebet",10)
		lost("part_tarakan",6)
		lost("part_tarakan_strong",20)
		lost("part_zombie_teeth",10)
		lost("part_rudiment_big",3)
		lost("part_spleen_rat",20)
		lost("mozg",6)
		lost("bezoar",6)
		lost("bread_a",8)
	this.give_ammo(25)
	got("vodka",100)
end

function kuznetsov_biznes1_have_all()
	return
		has("wpn_ak47",30) and
		has("ammo_7.62x39_fmj",40) and
		has("ammo_7.62x39_ap",20)
end		
function kuznetsov_biznes1_have()
	if kuznetsov_biznes1_have_all() then
		give_info("kuznetsov_biznes1_have")
		return true
	else
		return false
	end
end
function kuznetsov_biznes1_done()
		lost("wpn_ak47",30)
		lost("ammo_7.62x39_fmj",40)
		lost("ammo_7.62x39_ap",20)
	got("sigaret",100)
	got("cube_chip",1)
end

function adrenalin_biznes1_have_all1()
	return
		has_good("wpn_pkm",7) and
		has_good("wpn_m_134",14) and
		has_good("wpn_mg42",1)
end		
function adrenalin_biznes1_have1()
	if adrenalin_biznes1_have_all1() then
		give_info("adrenalin_biznes1_have1")
		return true
	else
		return false
	end
end
function adrenalin_biznes1_done1()
		lost_good("wpn_pkm",7)
		lost_good("wpn_m_134",14)
		lost_good("wpn_mg42",1)
		this.adrenalin_biznes1_done()
end
function adrenalin_biznes1_have_all2()
	return
		has("ammo_7.62x54r",20) and
		has("ammo_minigun",24) and
		has("ammo_7.62x51box",10)
end		
function adrenalin_biznes1_have2()
	if adrenalin_biznes1_have_all2() then
		give_info("adrenalin_biznes1_have2")
		return true
	else
		return false
	end
end
function adrenalin_biznes1_done2()
		lost("ammo_7.62x54r",20)
		lost("ammo_minigun",24)
		lost("ammo_7.62x51box",10)
		this.adrenalin_biznes1_done()
end
function adrenalin_biznes1_have_all3()
	return	
		has("treasure_item",60) and
		has("zamok",30)
end		
function adrenalin_biznes1_have3()
	if adrenalin_biznes1_have_all3() then
		give_info("adrenalin_biznes1_have3")
		return true
	else
		return false
	end
end
function adrenalin_biznes1_done3()
		lost("treasure_item",60)
		give_info("biznes_remove_special_item")
		lost("zamok",30)
		disable_info("biznes_remove_special_item")
		this.adrenalin_biznes1_done()
end
function adrenalin_biznes1_done()
	if has_info("adrenalin_biznes1_done1") and has_info("adrenalin_biznes1_done2") and has_info("adrenalin_biznes1_done3") then
		got("ammo_12.7x108",30)
		got("ammo_7.62x39_k",10)
		got("ammo_5.56x45_gd",10)
		got("ammo_12x70_kart",30)
		got("ammo_gauss",30)
		got("ammo_super_gauss",30)
		got("ammo_balon",10)
		got("grenade_f1_double",30)
		got("cube_chip",1)
		give_info("adrenalin_biznes1_done")
	end
end

function zahar_biznes1_have_all()
	return
		has("amk_metka",10) and
		has_good("wpn_saiga12c",10) and
		has("ammo_12x70_buck",30) and
		has("ammo_12x76_dart",20) and
		has("ammo_12x76_zhekan",15) and
		has("ammo_12x70_kart",50)
end		
function zahar_biznes1_have()
	if zahar_biznes1_have_all() then
		give_info("zahar_biznes1_have")
		return true
	else
		return false
	end
end
function zahar_biznes1_done()
		give_info("biznes_remove_special_item")
		lost("amk_metka",10)
		disable_info("biznes_remove_special_item")
		lost_good("wpn_saiga12c",10)
		lost("ammo_12x70_buck",30)
		lost("ammo_12x76_dart",20)
		lost("ammo_12x76_zhekan",15)
		lost("ammo_12x70_kart",50)
	this.give_ammo(10)
	got("wpn_m_134",1)
	got("wpn_pkm",1)
	got("cube_chip",1)
end

function barman_biznes1_have_all()
	return
		has("sweetness",20) and
		has("beer_a",20) and
		has("cigara",50) and
		has("sigaret",100) and
		has("vodka",200)
end		
function barman_biznes1_have()
	if barman_biznes1_have_all() then
		give_info("barman_biznes1_have")
		return true
	else
		return false
	end
end
function barman_biznes1_done()
		lost("sweetness",20)
		lost("beer_a",20)
		lost("cigara",50)
		lost("sigaret",100)
		lost("vodka",200)
	give_info("info_amk_recipt_power_1")
	got("cube_chip",1)
end

function kruglov_biznes1_have_all()
	return
		has_good("nebo_scientific_outfit",1) and
		has("af_dik_1",2) and
		has("af_dik_2",2) and
		has("af_dik_3",2) and
		has("af_dik_4",2) and
		has("af_spirit_4",1)
end		
function kruglov_biznes1_have()
	if kruglov_biznes1_have_all() then
		give_info("kruglov_biznes1_have")
		return true
	else
		return false
	end
end
function kruglov_biznes1_done()
		lost_good("nebo_scientific_outfit",1)
		lost("af_dik_1",2)
		lost("af_dik_2",2)
		lost("af_dik_3",2)
		lost("af_dik_4",2)
		lost("af_spirit_4",1)
	got("wpn_m_134",1)
	got("cube_chip",1)
end

function yakut_biznes1_have_all()
	return
		has("af_simbion",6) and
		has("af_armor_4",6) and
		has("antizombie",3)
end		
function yakut_biznes1_have()
	if yakut_biznes1_have_all() then
		give_info("yakut_biznes1_have")
		return true
	else
		return false
	end
end
function yakut_biznes1_done()
		lost("af_simbion",6)
		lost("af_armor_4",6)
		lost("antizombie",3)
	got("wpn_m_134",1)
	got("cube_chip",1)
end

function voron_biznes1_have_all()
	return
		has_good("wpn_peceneg",8) and
		has("ammo_7.62x54r",12) and
		has_good("military_outfit",4) and
		has_good("militaryspec_outfit",4) and
		has("medkit_army",20)
end		
function voron_biznes1_have()
	if voron_biznes1_have_all() then
		give_info("voron_biznes1_have")
		return true
	else
		return false
	end
end
function voron_biznes1_done()
		lost_good("wpn_peceneg",8)
		lost("ammo_7.62x54r",12)
		lost_good("military_outfit",4)
		lost_good("militaryspec_outfit",4)
		lost("medkit_army",20)
	got("wpn_m_134",1)
	got("wpn_rpk47_sk1",1)
	got("cube_chip",1)
end

function lukash_biznes1_have_all()
	return
		has("grenade_f1",20) and
		has("grenade_f1_double",5) and
		has("grenade_rgd5",20) and
		has("grenade_gd-05",20) and
		has("grenade_flash",20) and
		has_good("wpn_rg-6",1) and
		has("ammo_vog-25",20) and
		has("ammo_vog-25p",20) and
		has_good("wpn_groza",4) and
		has("medkit_army",10) and
		has("antirad",10) and
		has("energy_drink",20) and
		has("amk_metka",5) and
		has("treasure_item",5) and
		has("detector_elite",1)
end		
function lukash_biznes1_have()
	if lukash_biznes1_have_all() then
		give_info("lukash_biznes1_have")
		return true
	else
		return false
	end
end
function lukash_biznes1_done()
		lost("grenade_f1",20)
		lost("grenade_f1_double",5)
		lost("grenade_rgd5",20)
		lost("grenade_gd-05",20)
		lost("grenade_flash",20)
		lost_good("wpn_rg-6",1)
		lost("ammo_vog-25",20)
		lost("ammo_vog-25p",20)
		lost_good("wpn_groza",4)
		lost("antirad",10)
		lost("medkit_army",10)
		lost("energy_drink",20)
		lost("treasure_item",5)
		lost("detector_elite",1)

		give_info("biznes_remove_special_item")
		lost("amk_metka",5)
		disable_info("biznes_remove_special_item")

	this.give_ammo(10)
	got("wpn_m_134",1)
	got("cube_chip",1)
end

function sakharov_biznes1_have_all()
	return
		has("caps_mosquito_bald",3) and
		has("caps_gravi",3) and
		has("caps_mincer",3) and
		has("caps_electra",3) and
		has("caps_zharka",3) and
		has("caps_ameba",3) and
		has("caps_ice",3) and
		has("mutant_krovosos_cocoon",1) and
		has("mutant_burer_cocoon",1) and
		has("mutant_zombie_cocoon",1) and
		has("mutant_snork_cocoon",1) and
		has("mutant_flesh_cocoon",1) and
		has("mutant_gigant_cocoon",1) and
		has("mutant_poltergeist_cocoon",1) and
		has("mutant_psevdodog_cocoon",1) and
		has("mutant_dog_cocoon",1) and
		has("mutant_controller_cocoon",1) and
		has("mutant_chimera_cocoon",1) and
		has("mutant_boar_cocoon",1) and
		has("mutant_tushkano_cocoon",1) and
		has("mutant_psydog_cocoon",1) and
		has("mutant_cat_cocoon",1) and
		has("bezoar",5)
end		
function sakharov_biznes1_have()
	if sakharov_biznes1_have_all() then
		give_info("sakharov_biznes1_have")
		return true
	else
		return false
	end
end
function sakharov_biznes1_done()
		lost("caps_mosquito_bald",3)
		lost("caps_gravi",3)
		lost("caps_mincer",3)
		lost("caps_electra",3)
		lost("caps_zharka",3)
		lost("caps_ameba",3)
		lost("caps_ice",3)
		lost("mutant_krovosos_cocoon",1)
		lost("mutant_burer_cocoon",1)
		lost("mutant_zombie_cocoon",1)
		lost("mutant_snork_cocoon",1)
		lost("mutant_flesh_cocoon",1)
		lost("mutant_gigant_cocoon",1)
		lost("mutant_poltergeist_cocoon",1)
		lost("mutant_psevdodog_cocoon",1)
		lost("mutant_dog_cocoon",1)
		lost("mutant_controller_cocoon",1)
		lost("mutant_chimera_cocoon",1)
		lost("mutant_boar_cocoon",1)
		lost("mutant_tushkano_cocoon",1)
		lost("mutant_psydog_cocoon",1)
		lost("mutant_cat_cocoon",1)
		lost("bezoar",5)
	got("af_power",1)
	got("cube_chip",1)
end

function sak_biznes1_have_all()
	return
		has("af_medusa",8) and
		has("af_cristall_flower",6) and
		has("af_night_star",6) and
		has("af_vyvert",7) and
		has("af_gravi",12) and
		has("af_gold_fish",4) and
		has("af_blood",4) and
		has("af_mincer_meat",3) and
		has("af_soul",7) and
		has("af_electra_sparkler",5) and
		has("af_electra_flash",5) and
		has("af_electra_moonlight",6) and
		has("af_rusty_thorn",6) and
		has("af_rusty_kristall",8) and
		has("af_rusty_sea-urchin",4) and
		has("af_ameba_slime",5) and
		has("af_ameba_slug",10) and
		has("af_ameba_mica",8) and
		has("af_drops",9) and
		has("af_fireball",4) and
		has("af_cristall",4) and
		has("af_dummy_glassbeads",6) and
		has("af_dummy_pellicle",5) and
		has("af_dummy_battery",9) and
		has("af_dummy_dummy",6) and
		has("af_dummy_spring",7) and
		has("af_fuzz_kolobok",4) and
		has("af_cry_2",3) and
		has("af_arhara_globus",1) and
		has("arc_art_box_1basic",3) and
		has("arc_art_box_basic",3) and
		has("arc_art_box_8basic",3) and
		has("zamok",1) and
		has("treasure_item",1) and
		has("amk_metka",1)
end		
function sak_biznes1_have()
	if sak_biznes1_have_all() then
		give_info("sak_biznes1_have")
		return true
	else
		return false
	end
end
function sak_biznes1_done()
		lost("af_medusa",8)
		lost("af_cristall_flower",6)
		lost("af_night_star",6)
		lost("af_vyvert",7)
		lost("af_gravi",12)
		lost("af_gold_fish",4)
		lost("af_blood",4)
		lost("af_mincer_meat",3)
		lost("af_soul",7)
		lost("af_electra_sparkler",5)
		lost("af_electra_flash",5)
		lost("af_electra_moonlight",6)
		lost("af_rusty_thorn",6)
		lost("af_rusty_kristall",8)
		lost("af_rusty_sea-urchin",4)
		lost("af_ameba_slime",5)
		lost("af_ameba_slug",10)
		lost("af_ameba_mica",8)
		lost("af_drops",9)
		lost("af_fireball",4)
		lost("af_cristall",4)
		lost("af_dummy_glassbeads",6)
		lost("af_dummy_pellicle",5)
		lost("af_dummy_battery",9)
		lost("af_dummy_dummy",6)
		lost("af_dummy_spring",7)
		lost("af_fuzz_kolobok",4)
		lost("af_cry_2",3)
		lost("af_arhara_globus",1)
		lost("treasure_item",1)

		give_info("biznes_remove_special_item")
		lost("amk_metka",1)
		lost("arc_art_box_1basic",3)
		lost("arc_art_box_basic",3)
		lost("arc_art_box_8basic",3)
		lost("zamok",1)
		disable_info("biznes_remove_special_item")

	this.give_ammo(10)
	got("wpn_m_134",1)
	got("cube_chip",1)
end

function skraga_biznes1_have_all()
	return db.actor:money()>=2000000	
end		
function skraga_biznes1_have()
	if skraga_biznes1_have_all() then
		give_info("skraga_biznes1_have")
		return true
	else
		return false
	end
end
function skraga_biznes1_done()
	got("wpn_m_134",1)
	got("cube_chip",1)
end

function doktor_biznes1_have_all()
	return
		has("medkit",20) and
		has("medkit_army",30) and
		has("medkit_scientic",40) and
		has("bandage",100) and
		has("antirad",50) and
		has("antizombie",10) and
		has("vodka",20) and
		has("suvorotka",5) and
		has("af_life_heart",5) and
		has("maz",15) and
		has("matras",10) and
		has("zamok",10) and
		has("treasure_item",10) and
		has("amk_metka",1)
end		
function doktor_biznes1_have()
	if doktor_biznes1_have_all() then
		give_info("doktor_biznes1_have")
		return true
	else
		return false
	end
end
function doktor_biznes1_done()
		lost("medkit",20)
		lost("medkit_army",30)
		lost("medkit_scientic",40)
		lost("bandage",100)
		lost("antirad",50)
		lost("antizombie",10)
		lost("vodka",20)
		lost("suvorotka",5)
		lost("af_life_heart",5)
		lost("maz",15)
		lost("matras",10)
		lost("treasure_item",10)

		give_info("biznes_remove_special_item")
		lost("amk_metka",1)
		lost("zamok",10)
		disable_info("biznes_remove_special_item")

	this.give_ammo(10)
	got("wpn_m_134",1)
	got("cube_chip",1)
end

function borov_biznes1_have_all()
	return
		has_good("wpn_mp5sd",2) and
		has_good("wpn_mp5",10) and
		has("ammo_9x19_pbp",50) and
		has("medkit",20) and
		has("bandage",30) and
		has("bread",20) and
		has("kolbasa",10) and
		has("conserva",10) and
		has("af_medusa",2) and
		has("af_gravi",3) and
		has("af_drops",3) and
		has("af_blood",5) and
		has("af_fuzz_kolobok",2) and
		has("af_soul",1) and
		has("af_cry_1",2)
end		
function borov_biznes1_have()
	if borov_biznes1_have_all() then
		give_info("borov_biznes1_have")
		return true
	else
		return false
	end
end
function borov_biznes1_done()
		lost_good("wpn_mp5sd",2)
		lost_good("wpn_mp5",10)
		lost("ammo_9x19_pbp",50)
		lost("medkit",20)
		lost("bandage",30)
		lost("bread",20)
		lost("kolbasa",10)
		lost("conserva",10)
		lost("af_medusa",2)
		lost("af_gravi",3)
		lost("af_drops",3)
		lost("af_blood",5)
		lost("af_fuzz_kolobok",2)
		lost("af_soul",1)
		lost("af_cry_1",2)
	this.give_ammo(10)
	got("wpn_m_134",1)
	got("cube_chip",1)
end

function doktor_lekar1_have()
	if not has_info("doktor_lekar1_start") or has_info("acv_lekar2") then return end

	local cnt = amk.load_variable("lekar",0)
	cnt = cnt+1
	
	if cnt == 1 then
		sms("%c[255,160,160,160]".."ДОКТОР:".."\\n".."%c[255,255,128,128]Да, Меченый, именно так и нужно лечить людей - отдавая им аптечку. Носи всегда с собой запасные аптечки, чтобы ты мог помочь не только себе.", nil, nil, 30000)
	elseif cnt == 4 then
		sms("%c[255,160,160,160]".."ДОКТОР:".."\\n".."%c[255,255,128,128]Молодец, Меченый! Приятно видеть, что в Зоне есть добрые люди!", nil, nil, 30000)
	elseif cnt == 7 then
		sms("%c[255,160,160,160]".."ДОКТОР:".."\\n".."%c[255,255,128,128]Продолжай в том же духе, друг мой!", nil, nil, 30000)
	elseif cnt == 10 then
		sms("%c[255,160,160,160]".."ДОКТОР:".."\\n".."%c[255,255,128,128]Меченый, ты справился с моим поручением и показал, что на тебя можно положиться. Жду тебя в гости, есть кое-что интересное.", nil, nil, 30000)
		give_info("doktor_lekar1_have")
	elseif cnt == 20 then
		give_info("acv_lekar")
	elseif cnt == 30 then
		give_info("acv_lekar2")
		amk.del_variable("lekar")
		return
	end
	
	amk.save_variable("lekar",cnt)
end

function doktor_lekar1_money()
	if has_info("acv_lekar2") then
		got_money(math.random(100,200))
	end
end

-- Убийство контролеров в онлайне, чтобы не было зацикливания пения
function kill_online_kontroller()
	local result = false
	for id,obj in pairs(db.creatures) do
		if obj and obj:clsid() == clsid.controller_s and obj:alive() then
			obj:kill(obj)
			result = true
		end
	end
	return result
end

function checking_taken_item62(obj)
  local obj_sect = obj:section()
  if obj_sect=="strelok_taynik_pda1" then
	if has_info("strelok_taynik_pda1_found") then 
	  if not has_info("strelok_taynik_stop") then 
	    give_info("strelok_taynik_pda1_have")
	    if not has_info("strelok_taynik_pda1_xvatit_spawn") then 
		  local se_obj = create("s_inventory_box1_2",xyz(176.28475952148,17.963838577271,40.265209197998),256932,2145)
		  se_obj = create("m_controller_normal",xyz(87.854019165039,-2.5235424041748,86.012077331543),199525,2143) 
		  se_obj = create("m_controller_normal_fat",xyz(87.854019165039,-2.5235424041748,86.012077331543),199525,2143) 
		  se_obj = create("m_controller_old",xyz(160.51348876953,-2.2140634059906,89.546524047852),249284,2177)		
		  se_obj = create("m_controller_old_fat",xyz(160.51348876953,-2.2140634059906,89.546524047852),249284,2177)		
		  xr_effects.play_zvuk3()
		  give_info("strelok_taynik_pda1_xvatit_spawn")
		end
	  end
	else
	  give_info("strelok_taynik_stop")
	end
  elseif obj_sect=="strelok_taynik_pda1_2" then
    if not has_info("strelok_taynik_pda1_done") then 
      sms("%c[255,160,160,160]".."СТРЕЛОК:".."\\n".."%c[255,255,128,128]Ты, наверное, решил, что, найдя мой первый тайник, ты найдёшь тут ещё что-нибудь полезное? Ха-ха-ха! Следующий мой тайник тебе придётся поискать ещё дольше! Единственное, чем я могу помочь тебе, это закинуть тебя обратно на крышу высотки. Для этого пройди по этой крыше дальше до конца.".."\\n".."%c[255,1,255,1]1917-1986. 69 лет Советской власти в Припяти. Ура, товарищи!".."\\n".."%c[255,255,128,128]Гм, о чем это я?", nil, nil, 30000)
	  this.spawn_s_teleport1_2()
	  spawn_restrictor.strelok_taynik_pda1_3_1_sr1()
	end
    amk.drop_item(db.actor,obj)
	amk.remove_item(obj)
  elseif obj_sect=="strelok_taynik_pda1_3" then
    if not has_info("strelok_taynik_pda1_done") then 
      sms("%c[255,160,160,160]".."СТРЕЛОК:".."\\n".."%c[255,255,128,128]А ты настырный. Мне это нравится. Раз ты такой любопытный, даю тебе ещё одну наводку: есть рюкзачок на автовокзале, но с земли его не достать. Думай, Сталкер, думай!", nil, nil, 30000)
	  spawn_restrictor.strelok_taynik_pda1_3_2_sr1()
	end
    amk.drop_item(db.actor,obj)
	amk.remove_item(obj)
  elseif obj_sect=="strelok_taynik_pda1_4" then
    if not has_info("strelok_taynik_pda1_done") then 
      sms("%c[255,160,160,160]".."СТРЕЛОК:".."\\n".."%c[255,255,128,128]Нашёл. Молодец. Хочешь попасть обратно на крышу высотки, откуда ты начал? Найди мой рюкзак на шестом этаже. Для этого сначала запрыгни обратно на крышу дома, с которого ты попал сюда.", nil, nil, 30000)
	  this.spawn_s_teleport1_4()
	  spawn_restrictor.strelok_taynik_pda1_4_sr1()
	end
    amk.drop_item(db.actor,obj)
	amk.remove_item(obj)
  elseif obj_sect=="strelok_taynik_pda1_5" then
    if not has_info("strelok_taynik_pda1_done") then 
      sms("%c[255,160,160,160]".."СТРЕЛОК:".."\\n".."%c[255,255,128,128]Ой, он провалился на пятый этаж! Наверное, очередным выбросом разрушило балкон. А, может, телепорт тоже провалился? Ну-ка, проверь другой край балкона?".."\\n".."И ещё, раз уж ты такой опытный Сталкер, что нашёл все мои тайники в Центральной Припяти, я дам тебе подсказку: мой тайник с артефактами ты найдёшь вместе с одним из тайников, о которых тебе расскажет Доктор. Удачи!", nil, nil, 30000)
	  braad_test.kor_bar_pri()
	  this.delete_teleport("s_teleport1_1")
	  this.delete_teleport("s_teleport1_3_1")
	  this.delete_teleport("s_teleport1_3_2")
	  this.delete_teleport("s_teleport1_4")
	end
    amk.drop_item(db.actor,obj)
	amk.remove_item(obj)
  elseif (obj_sect=="strelok_taynik_pda2_1" and has("strelok_taynik_pda2_2")) or (obj_sect=="strelok_taynik_pda2_2" and has("strelok_taynik_pda2_1")) then
	if not has_info("strelok_taynik_stop") then 
	  give_info("strelok_taynik_pda2_have")
	end
  elseif obj_sect=="strelok_taynik_pda30" then
    if not has_info("strelok_taynik_stop") then 
	  give_info("strelok_taynik_pda30_have")
	end
  elseif obj_sect=="strelok_taynik_pda3" then
	if not has_info("strelok_taynik_stop") then 
	  if not has_info("strelok_taynik_pda3_have") then 
	    local se_obj = create("s_inventory_box3_1",xyz(-99.41,1.37,-171.46),12046,3241)
	    se_obj = create("s_inventory_box3_2",xyz(-155.51449584961,-4.6265954971313,-262.34503173828),5644,3238)
	    this.spawn_s_teleport3_2()
	    give_info("strelok_taynik_pda3_have")
	  end
	end
  elseif (obj_sect=="strelok_taynik_pda3_1" and has("strelok_taynik_pda3_2")) or (obj_sect=="strelok_taynik_pda3_2" and has("strelok_taynik_pda3_1")) then
	if not has_info("strelok_taynik_stop") then 
	  if not has_info("strelok_taynik_pda3_12_have") then 
	    local se_obj = create("s_inventory_box3_3",xyz(73.26683807373,1.484278678894,241.13470458984),29207,1244)
	    give_info("strelok_taynik_pda3_12_have")
	  end
	end
  elseif obj_sect=="strelok_taynik_pda3_3" then
    if not has_info("strelok_taynik_stop") then 
      if not has_info("strelok_taynik_pda3_3_have") then 
	    this.strelok_taynik_pda3_drop()
	    give_info("strelok_taynik_pda3_3_have")
	  end
	end
  elseif obj_sect=="strelok_taynik_pda4" then
	if has_info("strelok_taynik_pda4_found") then 
	  if not has_info("strelok_taynik_stop") then 
	    if not has_info("strelok_taynik_pda4_have") then 
		  this.delete_s_teleport4_1()
	      give_info("strelok_taynik_pda4_have")
		end
	  end
	else
	  give_info("strelok_taynik_stop")
	end
  elseif obj_sect=="strelok_taynik_pda5" then
    if not has_info("strelok_taynik_stop") then 
	  give_info("strelok_taynik_pda5_have")
	end
  elseif obj_sect=="strelok_taynik_pda6" then
    if not has_info("strelok_taynik_stop") then 
	  give_info("strelok_taynik_pda6_have")
	  if not has_info("strelok_taynik_pda6_xvatit_spawn") then 
	    local se_obj = create("bloodsucker_strong",xyz(-194.36819458008,49.02271270752,-535.56390380859),112200,3082)
	    se_obj = create("bloodsucker_normal",xyz(-189.69694519043,47.406341552734,-548.29016113281),117716,3082)
	    se_obj = create("bloodsucker_normal",xyz(-174.30001831055,49.662406921387,-521.21356201172),135088,3089)
	    se_obj = create("bloodsucker_normal",xyz(-170.43768310547,46.646286010742,-550.90631103516),139967,3088)
	    xr_effects.play_zvuk3()
		give_info("strelok_taynik_pda6_xvatit_spawn")
	  end
	end
  elseif obj_sect=="strelok_taynik_pda7" then
    if has_info("strelok_taynik_pda7_found") then 
 	  if not has_info("strelok_taynik_stop") then 
	    sms("%c[255,160,160,160]".."СТРЕЛОК:".."\\n".."%c[255,255,128,128]Уважаемый "..user_name().."! Когда я прятал этот тайник, я совершенно не знал, какую награду сюда можно положить для того, кто найдёт его... Я уверен, что к этому моменту у тебя, "..user_name()..", уже все есть. Ты - Терминатор с самым крутым оружием, имеешь все необходимые артефакты и полную защиту от всех возможных угроз. Ты ленишься наклониться даже за гауссом, не говоря уже об обычных артефактах. Поэтому я оставил тайник пустым. Надеюсь, ты не обиделся...".."\\n".."PS: Кстати, "..user_name()..", а ты уже нашёл мой последний тайник с артефактами? Если нет - то загрузись с сейва перед прыжком сюда и найди сначала его! Он где-то здесь, на антеннах!", nil, nil, 50000)
	    give_info("strelok_taynik_pda7_done")
	  end
	else
	  give_info("strelok_taynik_stop")
	end
    if has_info("strelok_taynik_pda0_done") then 
	  this.delete_s_teleport0_1()
	end
	amk.drop_item(db.actor,obj)
	amk.remove_item(obj)
  elseif obj_sect=="strelok_taynik_pda0" then
 	if not has_info("strelok_taynik_stop") then 
      sms("%c[255,160,160,160]".."СТРЕЛОК:".."\\n".."%c[255,255,128,128]Ну, "..user_name()..", раз ты нашёл этот мой тайник, то все эти призы твои. А чтоб снова не лезть на антенну, спрыгни в дыру на крыше.", nil, nil, 30000)
	  
  	  this.spawn_s_teleport0_1()
  	  give_info("strelok_taynik_pda0_done")
	  create("amk_kanistra",xyz(30.90,7.33,-39.75),210337,1045)
	  spawn_restrictor.stdt1_sr1()
	end
    amk.drop_item(db.actor,obj)
	amk.remove_item(obj)
  elseif obj_sect=="stdt_pda1" then 
    sms("%c[255,160,160,160]".."СТРЕЛОК:".."\\n".."%c[255,255,128,128]Все, "..user_name().."! Теперь уже точно все! Это было последнее, что я для тебя приготовил. Удачи!", nil, nil, 30000)
	
	local se_obj = db.actor:object("stdt_pda1")
	amk.drop_item(db.actor,se_obj)
	amk.remove_item(se_obj)
  end
end

function s_inventory_box1()
  local obj = create("s_inventory_box1",xyz(126.61811828613,15.248512268066,90.880737304688),225170,2143)
  this.create_teleport("s_teleport1_1",xyz(122.58910369873,4.5209398269653,87.757598876953),229491,2143)
  spawn_restrictor.strelok_taynik_pda1_sr1()
end

function s_inventory_box2()
  taynik_spawn.s_new_inventory2_1()
  local obj = create("s_inventory_box2_2",xyz(-77.04369354248,-7.4020524024963,-20.482629776001),90914,892)
end

function s_inventory_box30()
  local obj = create("s_inventory_box30",xyz(73.863845825195,-0.0094784200191498,121.16677093506),29686,1221)
end

function s_inventory_box3()
  local obj = create("s_inventory_box3",xyz(16.393283843994,37.914726257324,2.0604181289673),6342,2453)
end

function s_inventory_box4()
  local obj = create("s_inventory_box4",xyz(596.83740234375,-49.984550476074,-24.092365264893),214270,1899)
  this.spawn_s_teleport4_1()
  spawn_restrictor.strelok_taynik_pda4_sr1()
  obj = create("af_dummy_spring_red",xyz(664.32122802734,-44.515979766846,-37.01086807251),227163,1896)
  obj = create("af_dummy_battery_red",xyz(664.32122802734,-44.515979766846,-37.01086807251),227163,1896)
  obj = create("af_dummy_pellicle_red",xyz(664.32122802734,-44.515979766846,-37.01086807251),227163,1896)
end

function s_inventory_box5()
  local obj = create("s_inventory_box5",xyz(984.81433105469,11.019639015198,245.36875915527),261708,2646)
end

function s_inventory_box6()
  spawn_restrictor.strelok_taynik_pda6_sr1()
  spawn_restrictor.strelok_taynik_pda6_sr2()
  spawn_restrictor.strelok_taynik_pda6_sr3()
end

function s_inventory_box7()
  local obj = create("s_inventory_box7",xyz(-17.708236694336,17.989824295044,-4.267804145813),5646,2026)
  spawn_restrictor.strelok_taynik_pda7_sr1()
  spawn_restrictor.strelok_taynik_pda7_sr2()
end

function strelok_taynik_pda1_have(task, objective)
  if db.actor ~= nil then
    if has_info("strelok_taynik_pda1_found") then 
      return has("strelok_taynik_pda1")
	end
  end
  return false
end
function strelok_taynik_pda1_done(first_speaker, second_speaker)
  lost("strelok_taynik_pda1")
  this.delete_s_teleport1_2()
end

function strelok_taynik_pda2_have(task, objective)
  if db.actor ~= nil then
    return has("strelok_taynik_pda2_1") and has("strelok_taynik_pda2_2")
  end
  return false
end
function strelok_taynik_pda2_done(first_speaker, second_speaker)
  lost("strelok_taynik_pda2_1")
  lost("strelok_taynik_pda2_2")
end

function strelok_taynik_pda30_have(task, objective)
  if db.actor ~= nil then
    return has("strelok_taynik_pda30")
  end
  return false
end
function strelok_taynik_pda30_done(first_speaker, second_speaker)
  lost("strelok_taynik_pda30")
end

function strelok_taynik_pda3_have(task, objective)
  if db.actor ~= nil then
    return has("strelok_taynik_pda3")
  end
  return false
end
function strelok_taynik_pda3_done(first_speaker, second_speaker)
  lost("strelok_taynik_pda3")
end
function strelok_taynik_pda3_drop()
    this.delete_s_teleport3_2()
	local se_obj = db.actor:object("strelok_taynik_pda3_1")
	amk.drop_item(db.actor,se_obj)
	amk.remove_item(se_obj)
	se_obj = db.actor:object("strelok_taynik_pda3_2")
	amk.drop_item(db.actor,se_obj)
	amk.remove_item(se_obj)
	se_obj = db.actor:object("strelok_taynik_pda3_3")
	amk.drop_item(db.actor,se_obj)
	amk.remove_item(se_obj)
end

function strelok_taynik_pda4_have(task, objective)
  if db.actor ~= nil then
    if has_info("strelok_taynik_pda4_found") then 
      return has("strelok_taynik_pda4")
	end
  end
  return false
end
function strelok_taynik_pda4_done(first_speaker, second_speaker)
  lost("strelok_taynik_pda4")
end

function strelok_taynik_pda5_have(task, objective)
  if db.actor ~= nil then
    return has("strelok_taynik_pda5")
  end
  return false
end
function strelok_taynik_pda5_done(first_speaker, second_speaker)
  lost("strelok_taynik_pda5")
end

function strelok_taynik_pda6_have(task, objective)
  if db.actor ~= nil then
    if has_info("strelok_taynik_pda6_found") then 
      return has("strelok_taynik_pda6")
	end
  end
  return false
end
function strelok_taynik_pda6_done(first_speaker, second_speaker)
  lost("strelok_taynik_pda6")
end

function strelok_taynik_pda7_have(task, objective)
  if db.actor ~= nil then
    if has_info("strelok_taynik_pda7_found") then 
      return has("strelok_taynik_pda7")
	end
  end
  return false
end

function spawn_s_teleport1_2()
    local se_obj = create("s_teleport1_2",xyz(207.23626708984,17.963800430298,48.94217300415),260660,2145)
	xr_logic.pstor_store(db.actor, "s_teleport1_2", se_obj.id)		  
end
function delete_s_teleport1_2(story_id)
	local obj_id = xr_logic.pstor_retrieve(db.actor, "s_teleport1_2", -1, true)
	local se_obj = server_object(obj_id)
if se_obj then
  release(se_obj, true)
end
end
function spawn_s_teleport1_3_1()
    local se_obj = create("s_teleport1_3_1",xyz(98.162727355957,28.547431945801,38.083969116211),225595,2143)
	xr_logic.pstor_store(db.actor, "s_teleport1_3_1", se_obj.id)		  
end
function spawn_s_teleport1_3_2()
    local se_obj = create("s_teleport1_3_2",xyz(-17.820304870605,13.85008430481,11.088830947876),81517,2160)
	xr_logic.pstor_store(db.actor, "s_teleport1_3_2", se_obj.id)		  
end
function spawn_s_teleport1_4()
    local se_obj = create("s_teleport1_4",xyz(-90.959411621094,13.623492240906,28.934303283691),7528,2253)
	xr_logic.pstor_store(db.actor, "s_teleport1_4", se_obj.id)		  
end
function spawn_s_teleport1_5()
    local se_obj = create("s_teleport1_5",xyz(43.850486755371,11.828426361084,37.138198852539),155631,2225)
	xr_logic.pstor_store(db.actor, "s_teleport1_5", se_obj.id)		  
end

function spawn_s_teleport3_2()
    local se_obj = create("s_teleport3_2",xyz(-150.38586425781,-5.7839937210083,-278.90524291992),6896,3238)
	xr_logic.pstor_store(db.actor, "s_teleport3_2", se_obj.id)		  
end
function delete_s_teleport3_2(story_id)
	local obj_id = xr_logic.pstor_retrieve(db.actor, "s_teleport3_2", -1, true)
	local se_obj = server_object(obj_id)
if se_obj then
  release(se_obj, true)
end
end

function spawn_s_teleport4_1()
    local se_obj = create("s_teleport4_1",xyz(308.16702270508,-37.625602722168,-21.087753295898),69058,1930)
	xr_logic.pstor_store(db.actor, "s_teleport4_1", se_obj.id)		  
end
function delete_s_teleport4_1(story_id)
	local obj_id = xr_logic.pstor_retrieve(db.actor, "s_teleport4_1", -1, true)
	local se_obj = server_object(obj_id)
if se_obj then
  release(se_obj, true)
end
end

function spawn_s_teleport0_1()
    local se_obj = create("s_teleport0_1",xyz(-1.5840334892273,5.1518805027008,-44.498065948486),10089,1961)
	xr_logic.pstor_store(db.actor, "s_teleport0_1", se_obj.id)		  
end
function delete_s_teleport0_1(story_id)
	local obj_id = xr_logic.pstor_retrieve(db.actor, "s_teleport0_1", -1, true)
	local se_obj = server_object(obj_id)
if se_obj then
  release(se_obj, true)
end
end

function checking_taken_item59(obj)
  local obj_sect = obj:section()
  if string.find(obj_sect,"kostya_taynik_pda1_") then
	give_info("kostya_taynik_pda_have_1_"..string.sub(obj_sect,string.find(obj_sect,"1_")+2))
	if not has_info("kostya_taynik_pda1_tele") then 
	  sms("На полях пометка: Чтобы не забыть - телепорт находится в комнате над гастрономом, в которую нельзя попасть по основной лестнице.", nil, nil, 30000)
	  this.spawn_t_teleport1_1()
	  give_info("kostya_taynik_pda1_tele")
	end
	if obj_sect=="kostya_taynik_pda1_2" then 
	  if not has_info("kostya_taynik_pda1_2_xvatit_spawn") then 
	    sms("Внизу примечание: Тайник на первом этаже - в одном из соседних домов.", nil, nil, 30000)
	    give_info("kostya_taynik_pda1_2_xvatit_spawn")
	  end
	end
    if has_info("kostya_taynik_pda_have_1_1") and has_info("kostya_taynik_pda_have_1_2") and has_info("kostya_taynik_pda_have_1_3") and has_info("kostya_taynik_pda_have_1_4") and has_info("kostya_taynik_pda_have_1_5") then
	  if not has_info("kostya_taynik_pda1_have") then 
	    this.delete_t_teleport1_1()
	    this.spawn_t_teleport1_2()
	    sms("В углу надпись: Телепорт на крышу - на разрушенной лестнице в кинотеатре.", nil, nil, 30000)
        give_info("kostya_taynik_pda1_have")
	  end
	end
  elseif obj_sect=="kostya_taynik_pda4" then 
	if not has_info("kostya_taynik_pda4_xvatit_spawn") then 
	  sms("%c[255,160,160,160]".."СТАРЫЙ ЖИЛ:".."\\n".."%c[255,255,128,128]Чтоб меньше бегать от пещеры к заимке, сделал телепорт возле одного из входов. Нужно прыгнуть с камня в аномалию.", nil, nil, 30000)

	  this.spawn_t_teleport4_1()
	  local se_obj = create("m_controller_normal",xyz(293.54354858398,-6.1697669029236,-306.34655761719),1388412,2903) 
	  se_obj = create("m_controller_normal",xyz(293.54354858398,-6.1697669029236,-306.34655761719),1388412,2903) 
	  se_obj = create("m_controller_old_fat",xyz(343.52505493164,-1.7487429380417,-291.03280639648),1481127,2903)		
	  se_obj = create("m_controller_normal_fat",xyz(343.52505493164,-1.7487429380417,-291.03280639648),1481127,2903)		
	  give_info("kostya_taynik_pda4_xvatit_spawn")
	end
  elseif obj_sect=="kostya_taynik_pda8" then 
	if not has_info("kostya_taynik_pda8_xvatit_spawn") then 
	  local se_obj = create("m_controller_normal",xyz(-245.26629638672,-0.0019612908363342,108.61695098877),11654,1358) 
	  se_obj = create("m_controller_old_fat",xyz(-268.68731689453,-0.0014384984970093,67.68074798584),4443,1410) 
	  se_obj = create("m_controller_old",xyz(-208.81796264648,-0.00040912628173828,164.56384277344),25007,1332)		
	  give_info("kostya_taynik_pda8_xvatit_spawn")
	end
  elseif obj_sect=="ktdt_pda1" then 
	if has_info("ktdt1_found") then 
      give_info("ktdt2")
      sms("Найдена информация.", nil, nil, 20000)
	  local se_obj = create("x_inventory_box2",xyz(-0.79496783018112,1.145513176918,10.266807556152),309442,1582)
      this.spawn_x_teleport2()
	  this.delete_teleport("x_teleport1")
	  se_obj = db.actor:object("ktdt_pda1")
	  amk.drop_item(db.actor,se_obj)
	  amk.remove_item(se_obj)
	end
  elseif obj_sect=="ktdt_pda2" then 
	if has_info("ktdt2_found") then
      got_money(1000000)
      give_info("ktdt3")
      sms("Найдена информация.", nil, nil, 20000)
      this.spawn_x_teleport3()
	  local se_obj = db.actor:object("ktdt_pda2")
	  amk.drop_item(db.actor,se_obj)
	  amk.remove_item(se_obj)
	end
  elseif obj_sect=="ktdt_pda3" then 
	if has_info("ktdt3_found") then
      sms("%c[255,160,160,160]".."СТАРЫЙ ЖИЛ:".."\\n".."%c[255,255,128,128]Ну, "..user_name()..", вот ты и нашёл все мои тайники! Поздравляю!", nil, nil, 30000)
	  local se_obj = db.actor:object("ktdt_pda3")
	  amk.drop_item(db.actor,se_obj)
	  amk.remove_item(se_obj)
	end
  end
end

function t_inventory_box1()
  spawn_restrictor.kostya_taynik_pda1_sr1()
end
function kostya_taynik_pda1_have(task, objective)
    return has_info("kostya_taynik_pda1_have")
end
function kostya_taynik_pda1_done(first_speaker, second_speaker)
  lost("kostya_taynik_pda1_1")
  lost("kostya_taynik_pda1_2")
  lost("kostya_taynik_pda1_3")
  lost("kostya_taynik_pda1_4")
  lost("kostya_taynik_pda1_5")
end

function t_inventory_box21()
  taynik_spawn.t_new_inventory21()
end
function kostya_taynik_pda21_have(task, objective)
	if has("kostya_taynik_pda21",18) then
		give_info("kostya_taynik_pda21_have")
		return true
	else
		return false
	end
end
function kostya_taynik_pda21_done(task, objective)
	lost("kostya_taynik_pda21",18)

	-- спавним порталы и переходы
	local obj, params
	local portals = {
		{eh={x=-95.833763122559,y=-20.12349319458,z=73.946479797363,gv=3838,lv=1098},
		 lc={x=-94.074142456055,y=-18.931434631348,z=73.887977600098,gv=3838,lv=1289},
		 to={x=-5.1342377662659,y=-8.7591800689697,z=-43.163402557373,gv=2694,lv=5035},
		 dir={x=0,y=-1.57,z=0},
		 level="labx8"
		},
		{eh={x=0.057874165475369,y=-9.2725133895874,z=-43.226726531982,gv=2694,lv=5869},
		 lc={x=1.7423397302628,y=-8.0805139541626,z=-43.251842498779,gv=2694,lv=6289},
		 to={x=96.647491455078,y=5.50750207901,z=-15.555990219116,gv=1539,lv=6547},
		 dir={x=0,y=-1.57,z=0},
		 level="l10u_bunker"
		},
		{eh={x=102.00410461426,y=5.56742811203,z=-15.614800453186,gv=1544,lv=6771},
		 lc={x=103.65747070313,y=6.7574377059937,z=-15.629001617432,gv=1544,lv=6820},
		 to={x=8.3273286819458,y=-12.429878234863,z=23.948041915894,gv=1155,lv=3980},
		 dir={x=0,y=-1.57,z=0},
		 level="l08u_brainlab"
		},
		{eh={x=13.632986068726,y=-12.430124282837,z=23.89408493042,gv=1155,lv=4797},
		 lc={x=15.552788734436,y=-11.238062858582,z=23.86653137207,gv=1155,lv=5156},
		 to={x=-87.99201965332,y=-20.119352340698,z=73.813842773438,gv=3838,lv=1899},
		 dir={x=0,y=1.57,z=0},
		 level="l04u_labx18"
		}
	}
	
	for i,a in pairs(portals) do
 		obj = create("event_horisont",xyz(a.eh.x,a.eh.y,a.eh.z),a.eh.lv,a.eh.gv)
		netpacket:modify(obj, 
			"object_flags", -198,		-- 0xffffff3a object_flags
			"visual_flags", 1,			-- 0x1 visual_flags
			"skeleton_name", "idle",
			"skeleton_flags", 1,
			"physic_type", 3,			-- 0x3
			"mass", 100,
			"fixed_bones", "joint1")
		create("zone_event_horisont",xyz(a.eh.x,a.eh.y+1.7,a.eh.z),a.eh.lv,a.eh.gv)

		create_eh_lc(220000+i, vector():set(a.lc.x,a.lc.y,a.lc.z),a.lc.lv,a.lc.gv,
			vector():set(a.to.x,a.to.y,a.to.z),a.to.lv,a.to.gv,
			vector():set(a.dir.x,a.dir.y,a.dir.z),
			a.level,
			0)
	end
end

function create_eh_lc(
	p_story_id,	-- STORY_ID нового level_changer (понадобится нам позже)
	
	p_position,	-- вектор, координаты точки, в которой будет располагаться центр нового level_changer
	p_lvertex_id,	-- level_vertext_id  - идентифицируют уровень, на котором будет создан level_changer
	p_gvertex_id,	-- game_vertext_id   	
 
	p_dest_pos,	-- координаты точки, в которой на новом уровне окажется игрок
	p_dest_lv,	-- level_vertex_id   - идентифицируют уровень, на который level_changer будет перебрасывать игрока 
	p_dest_gv,	-- game_vertex_id
	p_dest_dir,	-- направрение взгляда игрока
	p_dest_level,	-- название уровня, например "L11_Pripyat"
	p_silent	-- следует задать 1, чтобы подавить вопрос о смене уровня (автоматический переход)
)
	local obj = create("level_changer", p_position, p_lvertex_id, p_gvertex_id)
 
	local packet = net_packet()
	obj:STATE_Write(packet)
 
	-- свойства cse_alife_object
	local game_vertex_id 			= packet:r_u16()
	local cse_alife_object__unk1_f32 	= packet:r_float()
	local cse_alife_object__unk2_u32 	= packet:r_u32()
	local level_vertex_id 			= packet:r_u32()
	local object_flags 			= packet:r_u32()
	local custom_data 			= packet:r_stringZ()
	local story_id 				= packet:r_u32()
	local spawn_story_id			= packet:r_u32()
 
	-- свойства cse_shape
	local shape_count 			= packet:r_u8()
	for i=1,shape_count do
		local shape_type 		= packet:r_u8()
		if shape_type == 0 then
			-- sphere
			local center 		= packet:r_vec3(vector())
			local radius 		= packet:r_float()
		else
			-- box
			local axis_x_x = packet:r_float()
			local axis_x_y = packet:r_float()
			local axis_x_z = packet:r_float()
			local axis_y_x = packet:r_float()
			local axis_y_y = packet:r_float()
			local axis_y_z = packet:r_float()
			local axis_z_x = packet:r_float()
			local axis_z_y = packet:r_float()
			local axis_z_z = packet:r_float()
			local offset_x = packet:r_float()
			local offset_y = packet:r_float()
			local offset_z = packet:r_float()
		end
	end
 
	-- свойства cse_alife_space_restrictor
	local restrictor_type 			= packet:r_u8()
 
	-- свойства cse_level_changer
	local dest_game_vertex_id		= packet:r_u16()  
	local dest_level_vertex_id 		= packet:r_u32()  
	local dest_position 			= packet:r_vec3(vector())
	local dest_direction 			= packet:r_vec3(vector())
	local dest_level_name 			= packet:r_stringZ()
	local dest_graph_point 			= packet:r_stringZ()
	local silent_mode 			= packet:r_u8()
 
 
	packet:w_begin(game_vertex_id)			-- game_vertex_id
	packet:w_float(cse_alife_object__unk1_f32)
	packet:w_u32(cse_alife_object__unk2_u32) 
	packet:w_u32(level_vertex_id)			-- level_vertex_id
	packet:w_u32( bit_not(193) )			-- object_flags = -193 = 0xFFFFFF3E
	packet:w_stringZ(custom_data)
	packet:w_u32(p_story_id)			-- story_id
	packet:w_u32(spawn_story_id)
 
	packet:w_u8(1)			-- количество фигур
		packet:w_u8(0)			-- тип фигуры: сфера
		packet:w_vec3(vector():set(0, 0, 0))  -- sphere_center
		packet:w_float(0.5)
--[[
	packet:w_u8(1)			-- тип фигуры: box
	packet:w_float(2)	   -- axis_x_x
	packet:w_float(0)	   -- axis_x_y
	packet:w_float(0)	   -- axis_x_z
	packet:w_float(0)	   -- axis_y_x
	packet:w_float(4)	   -- axis_y_y
	packet:w_float(0)	   -- axis_y_z
	packet:w_float(0)	   -- axis_z_x
	packet:w_float(0)	   -- axis_z_y
	packet:w_float(4)	   -- axis_z_z
	packet:w_float(0)	   -- offset_x
	packet:w_float(0)	   -- offset_y
	packet:w_float(0)          -- offset_z
]]
	packet:w_u8(3)	 	   -- restrictor_type
 
	packet:w_u16(p_dest_gv)			-- destination game_vertex_id
	packet:w_s32(p_dest_lv)			-- destination level_vertex_id
	packet:w_vec3(p_dest_pos)		-- destination position
	packet:w_vec3(p_dest_dir)		-- destination direction (направление взгляда)
	packet:w_stringZ(p_dest_level)		-- destination level name
	packet:w_stringZ("start_actor_02")	-- some string, always const
	packet:w_u8(p_silent)			-- 1 for silent level changing
 
	packet:r_seek(0)
	obj:STATE_Read(packet, packet:w_tell())
end

function t_inventory_box2()
  taynik_spawn.t_new_inventory2()
end
function kostya_taynik_pda2_have(task, objective)
	if has("kostya_taynik_pda2") then
		give_info("kostya_taynik_pda2_have")
		return true
	else
		return false
	end
end
function kostya_taynik_pda2_done(first_speaker, second_speaker)
  lost("kostya_taynik_pda2")
end

function t_inventory_box3()
  taynik_spawn.t_new_inventory3_1()
  taynik_spawn.t_new_inventory3_2()
  local obj = create("t_inventory_box3_3",xyz(4.5460352897644,31.063150405884,67.978546142578),27143,2659)
  obj = create("t_inventory_box3_4",xyz(242.60501098633,73.895149230957,138.61387634277),76288,2573)
end
function kostya_taynik_pda3_have(task, objective)
	if has("kostya_taynik_pda3_1") and has("kostya_taynik_pda3_2") and has("kostya_taynik_pda3_3") and has("kostya_taynik_pda3_4") then
		give_info("kostya_taynik_pda3_have")
		return true
	else
		return false
	end
end
function kostya_taynik_pda3_done(first_speaker, second_speaker)
  lost("kostya_taynik_pda3_1")
  lost("kostya_taynik_pda3_2")
  lost("kostya_taynik_pda3_3")
  lost("kostya_taynik_pda3_4")
end

function t_inventory_box4()
  local obj = create("t_inventory_box4",xyz(316.57379150391,-12.273648262024,-261.89810180664),1431070,2903)
end
function kostya_taynik_pda4_have(task, objective)
	if has("kostya_taynik_pda4") then
		give_info("kostya_taynik_pda4_have")
		return true
	else
		return false
	end
end
function kostya_taynik_pda4_done(first_speaker, second_speaker)
  lost("kostya_taynik_pda4")
end

function t_inventory_box5()
  taynik_spawn.t_new_inventory5()
end
function kostya_taynik_pda5_have(task, objective)
	if has("kostya_taynik_pda5") then
		give_info("kostya_taynik_pda5_have")
		return true
	else
		return false
	end
end
function kostya_taynik_pda5_done(first_speaker, second_speaker)
  lost("kostya_taynik_pda5")
end

function t_inventory_box6()
  taynik_spawn.t_new_inventory6_1()
  taynik_spawn.t_new_inventory6_2()
end
function kostya_taynik_pda6_have(task, objective)
	if has("kostya_taynik_pda6_1") and has("kostya_taynik_pda6_2") then
		give_info("kostya_taynik_pda6_have")
		return true
	else
		return false
	end
end
function kostya_taynik_pda6_done(first_speaker, second_speaker)
  lost("kostya_taynik_pda6_1")
  lost("kostya_taynik_pda6_2")
end

function t_inventory_box7()
  local obj = create("t_inventory_box7",xyz(94.308715820313,14.254689216614,50.491359710693),40199,3336)
end
function kostya_taynik_pda7_have(task, objective)
	if has("kostya_taynik_pda7") then
		give_info("kostya_taynik_pda7_have")
		return true
	else
		return false
	end
end
function kostya_taynik_pda7_done(first_speaker, second_speaker)
  lost("kostya_taynik_pda7")
end

function t_inventory_box8()
  taynik_spawn.t_new_inventory8()
end
function kostya_taynik_pda8_have(task, objective)
	if has("kostya_taynik_pda8") then
		give_info("kostya_taynik_pda8_have")
		return true
	else
		return false
	end
end
function kostya_taynik_pda8_done(first_speaker, second_speaker)
  lost("kostya_taynik_pda8")
end

function t_inventory_box9()
  taynik_spawn.t_new_inventory9_1()
  local obj = create("t_inventory_box9_2",xyz(-108.54,0.61,-244.63),11031,3241)
  taynik_spawn.t_new_inventory9_3()
end
function kostya_taynik_pda9_have(task, objective)
	if has("kostya_taynik_pda9_1") and has("kostya_taynik_pda9_2") and has("kostya_taynik_pda9_3") then
		give_info("kostya_taynik_pda9_have")
		return true
	else
		return false
	end
end
function kostya_taynik_pda9_done(first_speaker, second_speaker)
  lost("kostya_taynik_pda9_1")
  lost("kostya_taynik_pda9_2")
  lost("kostya_taynik_pda9_3")
end

function t_inventory_box10()
  local obj = create("t_inventory_box10_1",xyz(-116.87435913086,4.8685846328735,-149.80033874512),89560,562)
  obj = create("t_inventory_box10_2",xyz(-26.37,-0.58,-25.53),280608,1593)
  obj = create("t_inventory_box10_3",xyz(27.953716278076,20.462240219116,684.33978271484),307284,208)
  obj = create("t_inventory_box10_4",xyz(106.7265625,13.199247360229,153.22033691406),272568,374)
  spawn_restrictor.kostya_taynik_pda10_sr1()
end
function kostya_taynik_pda10_have(task, objective)
	if has("kostya_taynik_pda10_1") and has("kostya_taynik_pda10_2") and has("kostya_taynik_pda10_3") and has("kostya_taynik_pda10_4") then
		give_info("kostya_taynik_pda10_have")
		return true
	else
		return false
	end
end
function kostya_taynik_pda10_done(first_speaker, second_speaker)
  lost("kostya_taynik_pda10_1")
  lost("kostya_taynik_pda10_2")
  lost("kostya_taynik_pda10_3")
  lost("kostya_taynik_pda10_4")
end

function t_inventory_box11()
  local obj = create("t_inventory_box11_1",xyz(192.18560791016,12.331077575684,101.35523986816),260351,2221)
  taynik_spawn.t_new_inventory11_2()
  obj = create("t_inventory_box11_3",xyz(6.5773458480835,8.061222076416,138.07514953613),109702,2147)
end
function kostya_taynik_pda11_have(task, objective)
	if has("kostya_taynik_pda11_1") and has("kostya_taynik_pda11_2") and has("kostya_taynik_pda11_3") then
		give_info("kostya_taynik_pda11_have")
		return true
	else
		return false
	end
end
function kostya_taynik_pda11_done(first_speaker, second_speaker)
  give_info("ktdt1")
  sms("Найдена информация.", nil, nil, 20000)
  this.spawn_x_teleport1()
  lost("kostya_taynik_pda11_1")
  lost("kostya_taynik_pda11_2")
  lost("kostya_taynik_pda11_3")
end

function spawn_t_teleport1_1()
    local se_obj = create("t_teleport1_1",xyz(190.83657836914,2.7860803604126,217.42588806152),260274,2219)
	xr_logic.pstor_store(db.actor, "t_teleport1_1", se_obj.id)		  
end
function delete_t_teleport1_1(story_id)
	local obj_id = xr_logic.pstor_retrieve(db.actor, "t_teleport1_1", -1, true)
	local se_obj = server_object(obj_id)
if se_obj then
  release(se_obj, true)
end
end
function spawn_t_teleport1_2()
    local se_obj = create("t_teleport1_2",xyz(23.953285217285,10.699913024902,162.15838623047),131398,2199)
	xr_logic.pstor_store(db.actor, "t_teleport1_2", se_obj.id)		  
end

function spawn_t_teleport4_1()
    local se_obj = create("t_teleport4_1",xyz(-50.95,-29.72,-139.41),796684,2897)
	xr_logic.pstor_store(db.actor, "t_teleport4_1", se_obj.id)		  
end

function spawn_x_teleport1()
    local se_obj = create("x_teleport1",xyz(9.4039793014526,11.447186470032,90.041458129883),114619,2142)
	xr_logic.pstor_store(db.actor, "x_teleport1", se_obj.id)
	spawn_restrictor.ktdt1_sr1()
end
function spawn_x_teleport2()
    local se_obj = create("x_teleport2",xyz(-15.461825370789,-3.8673331737518,-5.0735273361206),283384,1593)
	xr_logic.pstor_store(db.actor, "x_teleport2", se_obj.id)
	spawn_restrictor.ktdt2_sr1()
end
function spawn_x_teleport3()
    local se_obj = create("x_teleport3",xyz(47.420116424561,-2.4642562866211,-209.0924987793),63669,1469)
	xr_logic.pstor_store(db.actor, "x_teleport3", se_obj.id)
    se_obj = create("x_teleport3_1",xyz(-47.345569610596,0.74647736549377,-160.83731079102),16808,1490)
	xr_logic.pstor_store(db.actor, "x_teleport3_1", se_obj.id)
    se_obj = create("x_teleport3_2",xyz(-25.791805267334,0.7459944486618,-150.2300567627),16808,1490)
	xr_logic.pstor_store(db.actor, "x_teleport3_2", se_obj.id)
    se_obj = create("x_teleport3_3",xyz(-67.088394165039,1.2463047504425,-154.01571655273),15216,1490)
	xr_logic.pstor_store(db.actor, "x_teleport3_3", se_obj.id)
    se_obj = create("x_inventory_box3",xyz(-27.107929229736,0.74637401103973,-160.10646057129),16808,1490)
	spawn_restrictor.ktdt3_sr1()
end


function taynik_kostya2_call()
    if has_info("kostya_sacharov_done") and has_info("sahar_sumka_done") and has_info("kostya_biznes1_done") then 
	  sms("%c[255,160,160,160]".."КОСТЯ:".."\\n".."%c[255,255,128,128]Стрелок! Будешь в наших краях, заходи, есть кое-что интересное.", nil, nil, 30000, nil, [[sms\kostya\taynik_kostya2_call_1]])
	end
end

function esc_pda_have(task, objective)
if db.actor ~= nil then
return has("kostya_pda")
end
return false
end

function esc_pda_done(first_speaker, second_speaker)
lost("kostya_pda")
second_speaker:set_relation(game_object.friend, first_speaker) 
end

function esc_art_have(task, objective)
if db.actor ~= nil then
return has("kostya_af_gold_fish")
end
return false
end

function esc_art_done(first_speaker, second_speaker)
lost("kostya_af_gold_fish")
second_speaker:set_relation(game_object.friend, first_speaker) 
end


function esc_pda2_have(task, objective)
if db.actor ~= nil then
return has("kostya_pda2")
end
return false
end

function esc_pda2_done(first_speaker, second_speaker)
lost("kostya_pda2")
end


function esc_pda3_have(task, objective)
if db.actor ~= nil then
return has("kostya_pda3")
end
return false
end

function esc_pda3_done(first_speaker, second_speaker)
lost("kostya_pda3")
end


function esc_pda4_have(task, objective)
if db.actor ~= nil then
return has("kostya_pda4")
end
return false
end

function esc_pda4_done(first_speaker, second_speaker)
lost("kostya_pda4")
end


function esc_pda5_have(task, objective)
if db.actor ~= nil then
return has("kostya_pda5")
end
return false
end

function esc_pda5_done(first_speaker, second_speaker)
lost("kostya_pda5")
end


function esc_pda6_have(task, objective)
if db.actor ~= nil then
return has("kostya_pda6")
end
return false
end

function esc_pda6_done(first_speaker, second_speaker)
lost("kostya_pda6")
end


function esc_pda7_have(task, objective)
if db.actor ~= nil then
return has("kostya_pda7")
end
return false
end

function esc_pda7_done(first_speaker, second_speaker)
lost("kostya_pda7")
end


function esc_pda8_have(task, objective)
if db.actor ~= nil then
return has("kostya_pda8")
end
return false
end

function esc_pda8_done(first_speaker, second_speaker)
lost("kostya_pda8")
end


function esc_pda9_have(task, objective)
if db.actor ~= nil then
return has("kostya_pda9")
end
return false
end

function esc_pda9_done(first_speaker, second_speaker)
lost("kostya_pda9")
end


function sacharov_pda_have(task, objective)
if db.actor ~= nil then
return has("pda_vasilyev")
end
return false
end

function sacharov_pda_done(first_speaker, second_speaker)
	lost("pda_vasilyev",1)
	sms("Получена информация.", nil, nil, 30000)
end

function kostya_art2_have(task, objective)
if db.actor ~= nil then
return has("af_dummy_battery")
end
return false
end

function kostya_art2_done(first_speaker, second_speaker)
lost("af_dummy_battery")
end

function document_done(first_speaker, second_speaker)
	lost("kostya_documents",1)
end

function kostya_teleport(first_speaker, second_speaker)
got("science_teleport")
end

function kostya_teleport2(first_speaker, second_speaker)
got("science_teleport2")
end

function kostya_teleport3(first_speaker, second_speaker)
got("science_teleport3")
end

function kostya_teleport4(first_speaker, second_speaker)
got("device_teleport")
end

function info_recieved()
	sms("Получена информация", nil, nil, 10000)
end

-- Вероятности появления фраз в диалогах
function probability_05()
	return math.random() <= 0.05
end

function actor_has_money_100000()
  return db.actor:money()>=100000
end
function give_money_100000(t1,t2)
  lost_money(100000)
end

function actor_has_money_40000()
  return db.actor:money()>=40000
end
function give_money_40000(t1,t2)
  lost_money(40000)
end

function actor_has_money_20000()
  return db.actor:money()>=20000
end
function give_money_20000(t1,t2)
  lost_money(20000)
end

function actor_out_money_190000()
	lost_money(190000)
end
function actor_in_money_190000()
	got_money(190000)
end

function actor_has_money_200000()
  return db.actor:money() >= 200000
end
function actor_dont_has_money_200000()
  return db.actor:money() < 200000
end
function give_money_200000(t1,t2)
  lost_money(200000)
end

function actor_has_money_20000()
  return db.actor:money() >= 20000
end
function actor_dont_has_money_20000()
  return db.actor:money() < 20000
end
function give_money_20000(t1,t2)
  lost_money(20000)
end

function actor_has_money_25000()
  return db.actor:money() >= 25000
end
function actor_dont_has_money_25000()
  return db.actor:money() < 25000
end
function give_money_25000(t1,t2)
  lost_money(25000)
end
