--[[
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Intellectual System Suit (ISS) <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Итак, что есть:
Проверяем, находится ли нужный модуль в слоте и одет ли на ГГ костюм. Если костюм и модуль в своих слотах - то придет сообщение, что все норм и вызовется функция, активирующая модуль. Если модуль в слоте, а костюм нет - то:
1) Активации модуля не будет.
2) На экран придет сообщение с ошибкой.
Модуль можно носить только с нанокостюмом. Носить просто так или с другим костюмом - не получится. Активация модуля возможна только при наличии соответствующей капсулы в инвентаре. Одновременно можно использовать только один любой модуль.
]]

-- апдейт раз в секунду
function nano_update()
    nano_speed()               -- МОДУЛЬ "СКОРОСТЬ"
    nano_med()                 -- МОДУЛЬ "ЗДОРОВЬЕ"
    nano_rad()                 -- МОДУЛЬ "РАДИАЦИЯ"
    nano_psi()                 -- МОДУЛЬ "ИЗЛУЧЕНИЕ"
    sidor_ammo()               -- СИДОР ПРИПАСЫ
end

--[[ Объявим все локальные переменные, используемые в файле ]]

local txt = volazar_tbl_text["text"]() -- массив со всеми юзаемыми текстами

local gg = db.actor
local vt = volazar_tbl_text.tips

local fl = false
local fl_1 = false
local bSend_1 = nil -- переменная, хранящая факт выдачи того или иного сообщения
local bSend_2 = nil
local bSend_3 = nil
local bSend_4 = nil

--[[
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Modul #1. Скорость.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
При активации модуля, нанокостюм автоматически, при понижении порога сил до 40%, вводит в кровь наноботы. Наличие капсулы с наноботами в инвентаре - обязательно.
]]

function nano_speed()
local gg = db.actor
local nano_suit = gg:item_in_slot(6)
local nano = gg:item_in_slot(1)
    if nano and nano:section() == "nano_speed" then -- Находится ли нужный модуль в 1 слоте (пистолеты).
        if nano_suit and nano_suit:section() == "nano_suit" then  -- Надет ли на ГГ костюм.
	      nano_speed_1() -- Какой молодец! И модуль нацепил и костюм не забыл одеть.
            if bSend_1 ~= true then
			  vt(txt.a.msg_vse_ok_1, "nano", 20000, "msg_vse_ok_1")
              bSend_1 = true
              bSend_2 = false
              bSend_3 = false
              bSend_4 = false
            end
        elseif bSend_1 ~= false then
              vt(txt.a.msg_vse_ne_ok_1, "nano", 20000, "msg_vse_ne_ok_1") -- А костюм где? Дубина!
              bSend_1 = false
        end
    end
end

function nano_speed_1()
local gg = db.actor
if gg.power > 0.4 then 
fl = false		fl_1 = false
return 
end
if not fl then
vt(txt.a.msg_sp, "nano", 10000, "msg_sp")
fl = true
end
fl = true
local speed = gg:object("nanobot_pow") 
if speed then
gg.power=1.0
fl = false		fl_1 = false
return
elseif not fl_1 then
vt(txt.a.msg_vse_ne_ok_2, "nano", 20000, "msg_vse_ne_ok_2") -- Нет капсулы? Гуляй!
fl_1 = true
end
end

--[[
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Modul #2. Здоровье.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
При активации модуля, нанокостюм автоматически, при понижении порога здоровья до 40%, вводит в кровь наноботы. Наличие капсулы с наноботами в инвентаре - обязательно.
]]

function nano_med()
local gg = db.actor
local nano_suit = gg:item_in_slot(6)
local nano = gg:item_in_slot(1)
    if nano and nano:section() == "nano_med" then
        if nano_suit and nano_suit:section() == "nano_suit" then  -- Надет ли на ГГ костюм.
	      nano_med_1() -- Какой молодец! И модуль нацепил и костюм не забыл одеть.
            if bSend_2 ~= true then
			  vt(txt.a.msg_vse_ok_2, "nano", 20000, "msg_vse_ok_2")
              bSend_1 = false
              bSend_2 = true
              bSend_3 = false
              bSend_4 = false
            end
        elseif bSend_2 ~= false then
              vt(txt.a.msg_vse_ne_ok_1, "nano", 20000, "msg_vse_ne_ok_1") -- А костюм где? Дубина!
              bSend_2 = false
        end
    end
end

function nano_med_1()
local gg = db.actor
local med = gg:object("nanobot_med")
if gg.health > 0.40 then 
fl = false		fl_1 = false
return 
end
if not fl then
vt(txt.a.msg_med, "nano", 10000, "msg_med")
end	
fl = true
if med then
gg.health=1.0
fl = false		fl_1 = false
return
elseif not fl_1 then
vt(txt.a.msg_vse_ne_ok_2, "nano", 20000, "msg_vse_ne_ok_2")
fl_1 = true
 end
end

--[[
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Modul #3. Радиация.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
При активации модуля, нанокостюм автоматически, при превышении порога радиации в 50%, вводит в кровь наноботы. Наличие капсулы с наноботами в инвентаре - обязательно.
]]

function nano_rad()
local gg = db.actor
local nano_suit = gg:item_in_slot(6)
local nano = gg:item_in_slot(1)
    if nano and nano:section() == "nano_rad" then
        if nano_suit and nano_suit:section() == "nano_suit" then  -- Надет ли на ГГ костюм.
	      nano_rad_1() -- Какой молодец! И модуль нацепил и костюм не забыл одеть.
            if bSend_3 ~= true then
              vt(txt.a.msg_vse_ok_3, "nano", 20000, "msg_vse_ok_3")
              bSend_1 = false
              bSend_2 = false
              bSend_3 = true
              bSend_4 = false
            end
        elseif bSend_3 ~= false then
              vt(txt.a.msg_vse_ne_ok_1, "nano", 20000, "msg_vse_ne_ok_1") -- А костюм где? Дубина!
              bSend_3 = false
        end
    end
end

function nano_rad_1()
local gg = db.actor
local radn = gg:object("nanobot_rad")
if gg.radiation < 0.50 then 
fl = false		fl_1 = false
return 
end
if not fl then
vt(txt.a.msg_rad, "nano", 10000, "msg_rad")
end	
fl = true
if radn then
gg.radiation=-1.0
fl = false		fl_1 = false
return
elseif not fl_1 then
vt(txt.a.msg_vse_ne_ok_2, "nano", 20000, "msg_vse_ne_ok_2")
fl_1 = true
 end
end

--[[
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>Modul #4. Излучение.<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
При активации модуля, нанокостюм автоматически, при повышении уровня пси излучения в 50%, вводит наноботы в кровь. Наличие капсулы с наноботами в инвентаре - обязательно.
]]

function nano_psi()
local gg = db.actor
local nano_suit = gg:item_in_slot(6)
local nano = gg:item_in_slot(1)
    if nano and nano:section() == "nano_psi" then
        if nano_suit and nano_suit:section() == "nano_suit" then  -- Надет ли на ГГ костюм.
	      nano_psi_1() -- Какой молодец! И модуль нацепил и костюм не забыл одеть.
            if bSend_4 ~= true then
              vt(txt.a.msg_vse_ok_4, "nano", 20000, "msg_vse_ok_4")
              bSend_1 = false
              bSend_2 = false
              bSend_3 = false
              bSend_4 = true
            end
        elseif bSend_4 ~= false then
              vt(txt.a.msg_vse_ne_ok_1, "nano", 20000, "msg_vse_ne_ok_1") -- А костюм где? Дубина!
              bSend_4 = false
        end
    end
end

function nano_psi_1()
local gg = db.actor
local psi = gg:object("nanobot_psi")
if gg.psy_health > 0.5 then
fl = false		fl_1 = false
return 
end
if not fl then
vt(txt.a.msg_psi, "nano", 10000, "msg_psi")
end	
fl = true
if psi then
gg.psy_health=1.0
fl = false		fl_1 = false
return
elseif not fl_1 then
vt(txt.a.msg_vse_ne_ok_2, "nano", 20000, "msg_vse_ne_ok_2")
fl_1 = true
 end
end

--[[ Остальное... ]]

-- Спавним НПС
function spawn_volazar()        
local obj = volazar_spawn_other.spawn_other(20)
	snp.set_stalker_story_id(obj,19934)
    if obj then
      vt(txt.c.vol_1, "unknown", 30000, "vol_1")
	end
end

-- Удаляем и спавним нового
function spawn_volazar_new()
	local obj = snp.object_by_section_offline("volazar")
    if obj then
	  release(obj, true)
	end
	
	obj = volazar_spawn_other.spawn_other(21)
	snp.set_stalker_story_id(obj,19935)
end

-- Подсказки

-- Военная Лаборатория
function pod_war_1()
    vt(txt.b.war_1, "vol", 30000, "war_1")
end

function pod_war_2()
    vt(txt.b.war_2, "vol", 30000, "war_2")
end

function pod_war_3()
    vt(txt.b.war_3, "vol", 30000, "war_3")
end

function pod_war_4()
    vt(txt.b.war_4, "vol", 30000, "war_4")
end

function pod_war_5()
    vt(txt.b.war_5, "vol", 30000, "war_5")
end

function pod_war_6()
    vt(txt.b.war_6, "vol", 30000, "war_6")
end

function pod_war_7()
    vt(txt.b.war_7, "vol", 30000, "war_7")
end

function pod_war_8()
    vt(txt.b.war_8, "vol", 30000, "war_8")
end

function pod_war_9()
    vt(txt.b.war_9, "vol", 30000, "war_9")
end

function pod_war_10()
    vt(txt.b.war_10, "vol", 30000, "war_10")
end

function pod_war_11()
    vt(txt.b.war_11, "vol", 30000, "war_11")
end

function pod_war_12()
    vt(txt.b.war_12, "vol", 30000, "war_12")
end

function pod_war_13()
    vt(txt.b.war_13, "vol", 30000, "war_13")
end

function pod_war_14()
    vt(txt.b.war_14, "vol", 30000, "war_14")
end

function pod_war_15()
    vt(txt.b.war_15, "vol", 30000, "war_15")
end

-- Х-16
function pod_x16_1()
    vt(txt.e.x16_1, "vol", 30000, "x16_1")
end

function pod_x16_2()
    vt(txt.e.x16_2, "vol", 30000, "x16_2")
end

function pod_x16_3()
    vt(txt.e.x16_3, "vol", 30000, "x16_3")
end

function pod_x16_4()
    vt(txt.e.x16_4, "vol", 30000, "x16_4")
end

function pod_x16_5()
    vt(txt.e.x16_5, "vol", 30000, "x16_5")
end

function pod_x16_6()
    vt(txt.e.x16_6, "vol", 30000, "x16_6")
end

function pod_x16_7()
    vt(txt.e.x16_7, "vol", 30000, "x16_7")
end

-- ЧАЭС 2
function pod_chs_1()
    vt(txt.f.chs_1, nil, 30000, "chs_1")
end

function pod_chs_2()
    vt(txt.f.chs_2, nil, 30000, "chs_2")
end

function pod_chs_3()
    vt(txt.f.chs_3, nil, 30000, "chs_3")
end

function pod_chs_4()
    vt(txt.f.chs_4, nil, 30000, "chs_4")
end

function pod_chs_5()
    vt(txt.f.chs_5, nil, 30000, "chs_5")
end

function pod_chs_6()
    vt(txt.f.chs_6, nil, 30000, "chs_6")
end

function pod_chs_7()
    vt(txt.f.chs_7, nil, 30000, "chs_7")
end

function pod_chs_8()
    vt(txt.f.chs_8, nil, 30000, "chs_8")
end

function pod_chs_9()
    vt(txt.f.chs_9, nil, 30000, "chs_9")
end

function pod_chs_10()
    vt(txt.f.chs_10, nil, 30000, "chs_10")
end

function pod_chs_11()
    vt(txt.f.chs_11, nil, 30000, "chs_11")
end

function pod_chs_12()
    vt(txt.f.chs_12, nil, 30000, "chs_12")
end

function pod_chs_13()
    vt(txt.f.chs_13, nil, 30000, "chs_13")
end

function pod_chs_14()
    vt(txt.f.chs_14, nil, 30000, "chs_14")
end

function pod_chs_15()
    vt(txt.f.chs_15, nil, 30000, "chs_15")
end

function pod_chs_16()
    vt(txt.f.chs_16, nil, 30000, "chs_16")
end

function pod_chs_17()
    vt(txt.f.chs_17, nil, 30000, "chs_17")
end

function pod_chs_18()
    vt(txt.f.chs_18, nil, 30000, "chs_18")
end

function pod_chs_19()
    vt(txt.f.chs_19, nil, 30000, "chs_19")
end

function pod_chs_20()
    vt(txt.f.chs_20, nil, 30000, "chs_20")
end

function pod_chs_21()
    vt(txt.f.chs_21, nil, 30000, "chs_21")
end

function pod_chs_22()
    vt(txt.f.chs_22, nil, 30000, "chs_22")
end

function pod_chs_23()
    vt(txt.f.chs_23, nil, 30000, "chs_23")
end

function pod_chs_24()
    vt(txt.f.chs_24, nil, 30000, "chs_24")
end

function pod_chs_25()
    vt(txt.f.chs_25, nil, 30000, "chs_25")
end

function pod_chs_26()
    vt(txt.f.chs_26, nil, 30000, "chs_26")
end

-- ЧАЭС
function pod_chs1_1()
    vt(txt.g.chs1_1, nil, 30000, "chs1_1")
end

function pod_chs1_2()
    vt(txt.g.chs1_2, nil, 30000, "chs1_2")
end

function pod_chs1_3()
    vt(txt.g.chs1_3, nil, 30000, "chs1_3")
end

function pod_chs1_4()
    vt(txt.g.chs1_4, nil, 30000, "chs1_4")
end

function pod_chs1_5()
    vt(txt.g.chs1_5, nil, 30000, "chs1_5")
end

function pod_chs1_6()
    vt(txt.g.chs1_6, nil, 30000, "chs1_6")
end

function pod_chs1_7()
    vt(txt.g.chs1_7, nil, 30000, "chs1_7")
end

function pod_chs1_8()
    vt(txt.g.chs1_8, nil, 30000, "chs1_8")
end

function pod_chs1_9()
    vt(txt.g.chs1_9, nil, 30000, "chs1_9")
end

function pod_chs1_10()
    vt(txt.g.chs1_10, nil, 30000, "chs1_10")
end

function pod_chs1_11()
    vt(txt.g.chs1_11, nil, 30000, "chs1_11")
end

function pod_chs1_12()
    vt(txt.g.chs1_12, nil, 30000, "chs1_12")
end

-- Лиманск
function pod_lim_1()
    vt(txt.h.lim_1, nil, 30000, "lim_1")
end

function pod_lim_2()
    vt(txt.h.lim_2, nil, 30000, "lim_2")
end

function pod_lim_3()
    vt(txt.h.lim_3, nil, 30000, "lim_3")
end

function pod_lim_4()
    vt(txt.h.lim_4, nil, 30000, "lim_4")
end

function pod_lim_5()
    vt(txt.h.lim_5, nil, 30000, "lim_5")
end

function pod_lim_6()
    vt(txt.h.lim_6, nil, 30000, "lim_6")
end

function pod_lim_7()
    vt(txt.h.lim_7, nil, 30000, "lim_7")
end

function pod_lim_8()
    vt(txt.h.lim_8, nil, 30000, "lim_8")
end

function pod_lim_9()
    vt(txt.h.lim_9, nil, 30000, "lim_9")
end

function pod_lim_10()
    vt(txt.h.lim_10, nil, 30000, "lim_10")
end

function pod_lim_11()
    vt(txt.h.lim_11, nil, 30000, "lim_11")
end

function pod_lim_12()
    vt(txt.h.lim_12, nil, 30000, "lim_12")
end

function pod_lim_13()
    vt(txt.h.lim_13, nil, 30000, "lim_13")
end

function pod_lim_14()
    vt(txt.h.lim_14, nil, 30000, "lim_14")
end

function pod_lim_15()
    vt(txt.h.lim_15, nil, 30000, "lim_15")
end

function pod_lim_16()
    vt(txt.h.lim_16, nil, 30000, "lim_16")
end

function pod_lim_17()
    vt(txt.h.lim_17, nil, 30000, "lim_17")
end

function pod_lim_18()
    vt(txt.h.lim_18, nil, 30000, "lim_18")
end

function pod_lim_19()
    vt(txt.h.lim_19, nil, 30000, "lim_19")
end

function pod_lim_20()
    vt(txt.h.lim_20, nil, 30000, "lim_20")
end

function pod_lim_21()
    vt(txt.h.lim_21, nil, 30000, "lim_21")
end

function pod_lim_22()
    vt(txt.h.lim_22, nil, 30000, "lim_22")
end

function pod_lim_23()
    vt(txt.h.lim_23, nil, 30000, "lim_23")
end

function pod_lim_24()
    vt(txt.h.lim_24, nil, 30000, "lim_24")
end

function pod_lim_25()
    vt(txt.h.lim_25, nil, 30000, "lim_25")
end

function pod_lim_26()
    vt(txt.h.lim_26, nil, 30000, "lim_26")
end

function pod_lim_27()
    vt(txt.h.lim_27, nil, 30000, "lim_27")
end

-- Путепровод
function pod_put_1()
    vt(txt.i.put_1, nil, 30000, "put_1")
end

function pod_put_2()
    vt(txt.i.put_2, nil, 30000, "put_2")
end

function pod_put_3()
    vt(txt.i.put_3, nil, 30000, "put_3")
end

function pod_put_4()
    vt(txt.i.put_4, nil, 30000, "put_4")
end

function pod_put_5()
    vt(txt.i.put_5, nil, 30000, "put_5")
end

function pod_put_6()
    vt(txt.i.put_6, nil, 30000, "put_6")
end

function pod_put_7()
    vt(txt.i.put_7, nil, 30000, "put_7")
end

function pod_put_8()
    vt(txt.i.put_8, nil, 30000, "put_8")
end

function pod_put_9()
    vt(txt.i.put_9, nil, 30000, "put_9")
end

function pod_put_10()
    vt(txt.i.put_10, nil, 30000, "put_10")
end

function pod_put_11()
    vt(txt.i.put_11, nil, 30000, "put_11")
end

function pod_put_12()
    vt(txt.i.put_12, nil, 30000, "put_12")
end

function pod_put_13()
    vt(txt.i.put_13, nil, 30000, "put_13")
end

function pod_put_14()
    vt(txt.i.put_14, nil, 30000, "put_14")
end

function pod_put_15()
    vt(txt.i.put_15, nil, 30000, "put_15")
end

function pod_put_16()
    vt(txt.i.put_16, nil, 30000, "put_16")
end

function pod_put_17()
    vt(txt.i.put_17, nil, 30000, "put_17")
end

function pod_put_18()
    vt(txt.i.put_18, nil, 30000, "put_18")
end

-- Вост. Припять
function pod_pri_1()
    vt(txt.j.pri_1, nil, 30000, "pri_1")
end

function pod_pri_2()
    vt(txt.j.pri_2, nil, 30000, "pri_2")
end

function pod_pri_3()
    vt(txt.j.pri_3, nil, 30000, "pri_3")
end

function pod_pri_4()
    vt(txt.j.pri_4, nil, 30000, "pri_4")
end

function pod_pri_5()
    vt(txt.j.pri_5, nil, 30000, "pri_5")
end

function pod_pri_6()
    vt(txt.j.pri_6, nil, 30000, "pri_6")
end

function pod_pri_7()
    vt(txt.j.pri_7, nil, 30000, "pri_7")
end

function pod_pri_8()
    vt(txt.j.pri_8, nil, 30000, "pri_8")
end

function pod_pri_9()
    vt(txt.j.pri_9, nil, 30000, "pri_9")
end

function pod_pri_10()
    vt(txt.j.pri_10, nil, 30000, "pri_10")
end

function pod_pri_11()
    vt(txt.j.pri_11, nil, 30000, "pri_11")
end

function pod_pri_12()
    vt(txt.j.pri_12, nil, 30000, "pri_12")
end

function pod_pri_13()
    vt(txt.j.pri_13, nil, 30000, "pri_13")
end

-- Х-8
function pod_x8_1()
    vt(txt.k.x8_1, nil, 30000, "x8_1")
end

function pod_x8_2()
    vt(txt.k.x8_2, nil, 30000, "x8_2")
end

function pod_x8_3()
    vt(txt.k.x8_3, nil, 30000, "x8_3")
end

function pod_x8_4()
    vt(txt.k.x8_4, nil, 30000, "x8_4")
end

function pod_x8_5()
    vt(txt.k.x8_5, nil, 30000, "x8_5")
end

-- МГ
function pod_mg_1()
    vt(txt.l.mg_1, nil, 30000, "mg_1")
end

function pod_mg_2()
    vt(txt.l.mg_2, nil, 30000, "mg_2")
end

function pod_mg_3()
    vt(txt.l.mg_3, nil, 30000, "mg_3")
end

function pod_mg_4()
    vt(txt.l.mg_4, nil, 30000, "mg_4")
end

function pod_mg_5()
    vt(txt.l.mg_5, nil, 30000, "mg_5")
end

-- Затон
function pod_zat_1()
    vt(txt.m.zat_1, nil, 30000, "zat_1")
end

function pod_zat_2()
    vt(txt.m.zat_2, nil, 30000, "zat_2")
end

function pod_zat_3()
    vt(txt.m.zat_3, nil, 30000, "zat_3")
end

function pod_zat_4()
    vt(txt.m.zat_4, nil, 30000, "zat_4")
end

function pod_zat_5()
    vt(txt.m.zat_5, nil, 30000, "zat_5")
end

function pod_zat_6()
    vt(txt.m.zat_6, nil, 30000, "zat_6")
end

function pod_zat_7()
    vt(txt.m.zat_7, nil, 30000, "zat_7")
end

function pod_zat_8()
    vt(txt.m.zat_8, nil, 30000, "zat_8")
end

function pod_zat_9()
    vt(txt.m.zat_9, nil, 30000, "zat_9")
end

-- Юпитер
function pod_jup_1()
    vt(txt.o.jup_1, nil, 30000, "jup_1")
end

function pod_jup_2()
    vt(txt.o.jup_2, nil, 30000, "jup_2")
end

function pod_jup_3()
    vt(txt.o.jup_3, nil, 30000, "jup_3")
end

function pod_jup_4()
    vt(txt.o.jup_4, nil, 30000, "jup_4")
end

function pod_jup_5()
    vt(txt.o.jup_5, nil, 30000, "jup_5")
end

function pod_jup_6()
    vt(txt.o.jup_6, nil, 30000, "jup_6")
end

function pod_jup_7()
    vt(txt.o.jup_7, nil, 30000, "jup_7")
end

function pod_jup_8()
    vt(txt.o.jup_8, nil, 30000, "jup_8")
end

function pod_jup_9()
    vt(txt.o.jup_9, nil, 30000, "jup_9")
end

function pod_jup_10()
    vt(txt.o.jup_10, nil, 30000, "jup_10")
end

function pod_jup_11()
    vt(txt.o.jup_11, nil, 30000, "jup_11")
end

function pod_jup_12()
    vt(txt.o.jup_12, nil, 30000, "jup_12")
end

function pod_jup_13()
    vt(txt.o.jup_13, nil, 30000, "jup_13")
end

function pod_jup_14()
    vt(txt.o.jup_14, nil, 30000, "jup_14")
end

function pod_jup_15()
    vt(txt.o.jup_15, nil, 30000, "jup_15")
end

function pod_jup_16()
    vt(txt.o.jup_16, nil, 30000, "jup_16")
end

function pod_jup_17()
    vt(txt.o.jup_17, nil, 30000, "jup_17")
end

function pod_jup_18()
    vt(txt.o.jup_18, nil, 30000, "jup_18")
end

--[[ Квест с Сидором ]]
local txt_str = { txt.n.esc_3, txt.n.esc_24, txt.n.esc_25, txt.n.esc_26 }
local txt_sid = { txt.n.esc_2, txt.n.esc_22, txt.n.esc_23, txt.n.esc_27 }

function sidor_ammo()
    if has_info("actor_fly") and
	   has_info("sidor_delo_start") and
	   not has_info("sidor_delo_have") and
	   not has_info("sidor_delo_fail") and
	   not db.actor:object("ammo_vog-25_fly")
	then
		local str = txt_str[math.random(#txt_str)]
		local sid = txt_sid[math.random(#txt_sid)]
		sms(str, nil, "strelok", 15000)
		sms(sid, math.random(4,6), "sidor", 15000)
	
		local gg = db.actor
        for i=1, 18 do
          create("ammo_vog-25_fly", gg:position(), gg:level_vertex_id (),gg:game_vertex_id (), gg:id())
        end
	end
end

function sidor_sms()
    vt(txt.n.esc_1, "sidor", 20000, "esc_1")
end

function sidor_start()
	voice([[characters_voice\volazar\vse_vyshe_vyshe]]):play(db.actor, 15, sound_object.s2d)
	sms("%c[255,160,160,160]".."СИДОРОВИЧ:".."\\n".."%c[255,255,128,128]Давай, осваивайся пока. Они вот-вот появятся.", 5, nil, 20000)
	snp.invul_on()
	give_info("no_landing")
	give_info("vol_info_temp")
end

function sidor_stop()
	voice([[characters_voice\volazar\vse_vyshe_vyshe]]):stop()
	snp.invul_off()
	invul_4_seconds()
	disable_info("no_autosave")
	disable_info("no_landing")
	disable_info("vol_info_temp")
end

function item_from_sidor() 
	got("anom_egg",1)
	got("wpn_rg-6",1)
	got("ammo_vog-25_fly",12)
	give_info("no_autosave")
end

function sidor_reward() 
	lost("wpn_rg-6",1)
	lost_all("ammo_vog-25_fly")
	got_money(300000)	
end

--[[ Other ]]

function disable_tel()
    disable_info("vol_info")
end

function vol_pridurok()
    vt(txt.c.vol_2, "vol", 30000, "vol_2")
end

function vol_eeeehhaa()
    vt(txt.c.vol_3, "vol", 15000, "vol_3")
end

function vol_sms()
    vt(txt.c.vol_4, "unknown", 30000, "vol_4")
end

function vol_sms_2()
    vt(txt.c.vol_5, nil, 15000, "vol_5")
end

function vol_sms_3()
    vt(txt.c.vol_6, "strelok", 15000, "vol_6")
end

function vol_sms_4()
    vt(txt.c.vol_7, "strelok", 15000, "vol_7")
end

function vol_sms_5()
    vt(txt.c.vol_8, nil, 15000, "vol_8")
end

function vol_sms_6()
    vt(txt.c.vol_9, "strelok", 15000, "vol_9")
end

function vol_sms_7()
    vt(txt.c.vol_10, nil, 20000, "vol_10")
end

function vol_sms_8()
    vt(txt.c.vol_11, "strelok", 15000, "vol_11")
end

function vol_sms_9()
    vt(txt.c.vol_12, nil, 20000, "vol_12")
end

function vol_sms_10()
    vt(txt.c.vol_13, "strelok", 15000, "vol_13")
end

function vol_sms_11()
    vt(txt.c.vol_14, "ozersky", 20000, "vol_14")
end

function vol_sms_12()
    vt(txt.c.vol_15, "ozersky", 20000, "vol_15")
end

function vol_sms_13()
    vt(txt.c.vol_16, "ozersky", 20000, "vol_16")
end

function vol_sms_14()
    vt(txt.c.vol_17, "ozersky", 20000, "vol_17")
end

function vol_sms_15()
    vt(txt.c.vol_18, "strelok", 20000, "vol_18")
end

function vol_sms_16()
    vt(txt.c.vol_19, "ozersky", 30000, "vol_19")
end

function vol_sms_17()
    vt(txt.c.vol_20, "strelok", 20000, "vol_20")
end

function vol_sms_18()
    vt(txt.c.vol_21, "ozersky", 20000, "vol_21")
end

function vol_sms_19()
    vt(txt.c.vol_22, "ozersky", 30000, "vol_22")
end

function vol_sms_20()
    vt(txt.c.vol_23, "strelok", 30000, "vol_23")
end

function vol_sms_21()
    vt(txt.c.vol_24, "ozersky", 30000, "vol_24")
end

-- Спавним уродцев
function spawn_bloodsucker()
create("vol_bloodsucker_1",xyz(-91.472,-0.390,-154.582),567519,3722)
create("vol_bloodsucker_2",xyz(-95.983,-0.389,-152.531),560799,3715)
create("vol_bloodsucker_3",xyz(-97.633,-0.389,-147.813),558483,3722)
create("vol_bloodsucker_4",xyz(-96.003,-0.389,-143.610),560812,3722)
create("vol_bloodsucker_5",xyz(-91.893,-0.389,-141.447),567538,3722)
create("vol_bloodsucker_6",xyz(-86.648,-0.390,-143.053),575907,3722)
create("vol_bloodsucker_7",xyz(-84.511,-0.390,-148.139),579365,3722)
create("vol_bloodsucker_8",xyz(-86.612,-0.390,-152.751),575893,3722)
end

function spawn_snork()
local se_obj = create("vol_snork_1",xyz(-173.388,0.251,-148.941),422788,3715)
netpacket:modify(se_obj, "object_flags", -5)	-- 0xfffffffb
end

function oz_music_good()
say([[characters_voice\volazar\ostanovite_ego]])
end

function oz_music_bad()
say([[characters_voice\volazar\unichtozhte_ego]])
end

function invul_4_seconds()
	snp.invul_on()
	amk.start_timer("run",4,"snp.invul_off()")
end

function remove_ozersky()
	disable_info("ozersky_spawn")
	remove_obj("vol_snork_1")
end

function vol0()
	if has_info("snp_vesker1_done") and has_info("info_chess_dictofon_done") then
		sms("%c[255,160,160,160]".."ВОЛАЗАР:".."\\n".."%c[255,255,128,128]"..user_name().."! Если тебе все ещё не надоело лазить по Зоне, то у меня есть для тебя очень интересный сюрприз. Ищи мой сюрприз на месте украденного Монолита. Ты уже облазил практически всю Зону, и сможешь без труда догадаться, где это место. Это место, в котором ты ещё не побывал, и, более того, даже к нему не приближался.", 5, nil, 60000, nil, [[sms\volazar\vol0]])
		create("v_inventory_box0",xyz(157.90061950684,36.504898071289,107.2147064209),59831,2566)
	end
end

-- Удаление любого онлайнового/оффлайнового обьекта
function remove_obj(name)
local obj
    for a=1,65535 do
	  obj = server_object(a)
		if obj and string.find(obj:name(),name) then
          release(obj, true)
		  return
	  	end
    end
end
