-- oksana579 docs
-- спавним контрика в Старой Деревне
function spawn_morskoi_ezh_hrenovji ()
create ("m_controller_old",xyz(-77.366,10.262,-87.191),575,3324)
end
-- спавним диктофон1 Шахматиста в Пещере 
function spawn_dictofon_1 ()
create ("dictofon_1",xyz(-135.853,0.828,-108.959),7068,2880)
end
-- смска Сидора
function sidor_shlob(first_speaker, second_speaker)
sms("%c[255,160,160,160]".."СИДОРОВИЧ:".."\\n".."%c[255,255,128,128]Меченый, будет время, забеги ко мне! Вся деревня про тебя гудит! Дело есть!", 5, nil, 30000, nil, [[sms\sidor\sidor_shlob]]) 
end
-- проверяем наличие диктофонов для Сидора
function info_chess_dictofon_have()
return has("dictofon_1",1) and
       has("dictofon_2",1) and
       has("dictofon_3",1) and
       has("dictofon_4",1) and
       has("dictofon_5",1) and
       has("dictofon_6",1) and
       has("dictofon_7",1) and
       has("dictofon_8",1) and
       has("dictofon_9",1) and
       has("dictofon_10",1) and
       has("dictofon_11",1) and
       has("dictofon_12",1) and
       has("dictofon_13",1) and
       has("dictofon_14",1) and
       has("dictofon_15",1) and
       has("dictofon_16",1) and
       has("dictofon_17",1) and
       has("dictofon_18",1) and
       has("dictofon_19",1) and
       has("dictofon_20",1)
end
-- отдаем диктофоны Сидору, получаем награду
function info_chess_dictofon_done(first_speaker, second_speaker)
lost("dictofon_1",1)
lost("dictofon_2",1)
lost("dictofon_3",1)
lost("dictofon_4",1)
lost("dictofon_5",1)
lost("dictofon_6",1)
lost("dictofon_7",1)
lost("dictofon_8",1)
lost("dictofon_9",1)
lost("dictofon_10",1)
lost("dictofon_11",1)
lost("dictofon_12",1)
lost("dictofon_13",1)
lost("dictofon_14",1)
lost("dictofon_15",1)
lost("dictofon_16",1)
lost("dictofon_17",1)
lost("dictofon_18",1)
lost("dictofon_19",1)
lost("dictofon_20",1)
got("af_kamen_udachy",1)
got("af_alive_water",1)
got("vodka",1)
second_speaker:set_relation(game_object.friend, first_speaker)
archievements.acv_task()
end
-- проверяем блокнот Шахтера
function narration_oldman_have()
return has("notebook_oldman",1)
end
-- отдаем блокнот Шахтеру, получаем награду
function narration_oldman_done(first_speaker, second_speaker)
lost("notebook_oldman",1)
got("ammo_zhekan_izomorf")
second_speaker:set_relation(game_object.friend, first_speaker)
end
-- проверяем наличие предметов
function set_apocalypse_have()
return has("verevka",1) and
       has("soap",1)
end
-- отдаем компоненты Шадовману, получаем награду
function set_apocalypse_done(first_speaker, second_speaker)
lost("verevka",1)
lost("soap",1)
got("ammo_9x39_izomorf")
second_speaker:set_relation(game_object.friend, first_speaker)
end
-- проверяем наличие стволов для Лентяя
function request_idler_have()
return has_good("wpn_vintorez",1) and
       has_good("wpn_rem870_magnum",1) and
       has("ammo_9x39_ap",3) and
       has("ammo_12x70_buck",3)
end
-- отдаем стволы Лентяю, получаем награду
function request_idler_done(first_speaker, second_speaker)
	lost_good("wpn_vintorez",1)
	lost_good("wpn_rem870_magnum",1)
	lost("ammo_9x39_ap",3)
	lost("ammo_12x70_buck",3)
	got("vodka")
	second_speaker:set_relation(game_object.friend, first_speaker)
end
-- спавним изоморфы
function birth_isomorphs ()
create ("izomorf_plastilin",xyz(11.490,9.00001,-389.712),966311,3678)
create ("kaktus_izomorf",xyz(-72.936,0.623,-169.574),797121,3679)
create ("izom_globus",xyz(-49.974,41.149,-266.239),277323,3105)
create ("izomorf_kompas",xyz(-242.278,-14.140,-14.617),14142,67)
create ("kaktus_izomorf",xyz(203.526,0.001,-81.403),130761,3316)
create ("izomorf_kompas",xyz(20.370,49.035,12.132),4854,2417)
create ("izomorf_plastilin",xyz(-3.461,-34.414,17.548),1699,2481)
create ("izom_globus",xyz(229.261,12.088,-127.971),1108588,3736)
create ("rad_zombied_respawn_1",xyz(-2.662,71.985,-25.502),4946,2417)
create ("yan_zombied_respawn_1",xyz(-42.426,-34.478,21.356),31,2509)
create ("rad_zombied_respawn_3",xyz(19.371,49.032,12.132),4854,2417)
end
-- проверяем наличие изоморфов
function maple_rustles_have()
return has("izom_globus",1) and
       has("kaktus_izomorf",1) and
       has("izomorf_kompas",1) and
       has("izomorf_plastilin",1)
end
-- отдаем изоморфы Кленову, получаем награду
function maple_rustles_done(first_speaker, second_speaker)
lost("izom_globus",1)
lost("kaktus_izomorf",1)
lost("izomorf_kompas",1)
lost("izomorf_plastilin",1)
got("wpn_g36_m1")
end
-- проверяем наличие арта и записки
function sugar_poll_have()
return has("note_5",1) and
       has("af_alive_water",1)
end
-- отдаем записку, получаем награду
function sugar_poll_done(first_speaker, second_speaker)
lost("note_5",1)
got("ammo_9x39_izomorf")
second_speaker:set_relation(game_object.friend, first_speaker)
end
-- проверяем наличие улик
function misunder_countryman_have()
return has("proof_friyets_1",1) and
       has("proof_friyets_2",1) and
       has("proof_friyets_3",1) and
       has("proof_friyets_4",1) and
       has("proof_friyets_5",1) and
       has("proof_friyets_6",1) 
end
-- отбирают улики
function misunder_countryman_done(first_speaker, second_speaker)
lost("proof_friyets_1",1)
lost("proof_friyets_2",1)
lost("proof_friyets_3",1)
lost("proof_friyets_4",1)
lost("proof_friyets_5",1)
lost("proof_friyets_6",1)
end
-- проверяем наличие записок для Кости
function info_chess_notes_have()
return has("note_zone_1",1) and
       has("note_zone_2",1) and
       has("note_zone_3",1) and
       has("note_zone_4",1) and
       has("note_zone_5",1) and
       has("note_zone_6",1) and
       has("note_zone_7",1) and
       has("note_zone_8",1) and
       has("note_zone_9",1) and
       has("note_zone_10",1) and
       has("note_zone_11",1) and
       has("note_zone_12",1) and
       has("note_zone_13",1) and
       has("note_zone_14",1) and
       has("note_zone_15",1) and
       has("note_zone_16",1) and
       has("note_zone_17",1) and
       has("note_zone_18",1) and
       has("note_zone_19",1) and
       has("note_zone_20",1) and
       has("note_zone_21",1) and
       has("note_zone_22",1) and
       has("note_zone_23",1) and
       has("note_zone_24",1) and
       has("note_zone_25",1) and
       has("note_zone_26",1) and
       has("note_zone_27",1) and
       has("note_zone_28",1) and
       has("note_zone_29",1) and
       has("note_zone_30",1) 
end
-- отдаем записки Косте, получаем награду
function info_chess_notes_done(first_speaker, second_speaker)
lost("note_zone_1",1)
lost("note_zone_2",1)
lost("note_zone_3",1)
lost("note_zone_4",1)
lost("note_zone_5",1)
lost("note_zone_6",1)
lost("note_zone_7",1)
lost("note_zone_8",1)
lost("note_zone_9",1)
lost("note_zone_10",1)
lost("note_zone_11",1)
lost("note_zone_12",1)
lost("note_zone_13",1)
lost("note_zone_14",1)
lost("note_zone_15",1)
lost("note_zone_16",1)
lost("note_zone_17",1)
lost("note_zone_18",1)
lost("note_zone_19",1)
lost("note_zone_20",1)
lost("note_zone_21",1)
lost("note_zone_22",1)
lost("note_zone_23",1)
lost("note_zone_24",1)
lost("note_zone_25",1)
lost("note_zone_26",1)
lost("note_zone_27",1)
lost("note_zone_28",1)
lost("note_zone_29",1)
lost("note_zone_30",1)
got("guitar_a")
second_speaker:set_relation(game_object.friend, first_speaker)
end
-- забираем деньги у осведомителя
function close_to_money(first_speaker, second_speaker) 
got_money(50000) 
end
-- отдаем Косте КПК
function document_transferred_1(first_speaker, second_speaker) 
lost("thief_pda") 
end
-- отдаем Косте Лист
function document_transferred_2(first_speaker, second_speaker) 
lost("blank_sheet_1") 
end
-- отдаем записку Сахару
function shadow_note_done(first_speaker, second_speaker) 
lost("blank_sheet_5") 
end
-- проверяем наличие арта
function kamen_udachy_have()
return has("af_kamen_udachy3",1) 
end
-- отдаем арт Бармену
function kamen_udachy_done(first_speaker, second_speaker)
lost("af_kamen_udachy3",1)
second_speaker:set_relation(game_object.friend, first_speaker)
end
-- получаем арт обратно
--[[function kamen_udachy_done1(first_speaker, second_speaker)
  got("af_kamen_udachy3")
end]]
-- получаем записку очкарика
function blank_sheet_done(first_speaker, second_speaker)
got("blank_sheet_4")
end
-- проверяем наличие рисунка монолита
function lonely_monolith_have()
return has("drawing_chess",1) 
end
-- показываем рисунок Косте
function lonely_monolith_done(first_speaker, second_speaker)
lost("drawing_chess",1)
second_speaker:set_relation(game_object.friend, first_speaker)
end
-- получаем подсказку Шахматиста
function gave_help_done(first_speaker, second_speaker)
  got("diary_chess_5")
end
-- проверяем наличие артов живое сердце
function life_heart_have()
return has("af_life_heart",3) 
end
-- отдаем арты холоду
function life_heart_done(first_speaker, second_speaker)
lost("af_life_heart",3)
end
-- проверяем наличие артов глаза ворона
function raven_eyes_have()
return has("af_eye_voron",3) 
end
-- отдаем арты холоду
function raven_eyes_done(first_speaker, second_speaker)
lost("af_eye_voron",3)
end
-- проверяем наличие мухоморов
function cunning_forester_have()
return has("mushroom",10) 
end
-- отдаем мухоморы Леснику
function cunning_forester_done(first_speaker, second_speaker)
lost("mushroom",10)
got("ammo_zhekan_izomorf")
end
-- проверяем наличие переписки
function dock_correspondence_have()
return has("letters_doctor",1) 
end
-- отдаем письма Доку, получаем награду
function dock_correspondence_done(first_speaker, second_speaker)
lost("letters_doctor",1)
got("ammo_9x39_izomorf")
second_speaker:set_relation(game_object.friend, first_speaker)
end
-- проверяем наличие головы и таблеток
function repairman_health_have()
return has("vasya_head",1) and
       has("tabletki_1",1) and
       has("tabletki_2",1) and
       has("tabletki_3",1) 
end
-- отдаем голову и таблетки Васе, получаем награду
function repairman_health_done(first_speaker, second_speaker)
lost("vasya_head",1)
lost("tabletki_1",1)
lost("tabletki_2",1)
lost("tabletki_3",1)
got("ammo_zhekan_izomorf",3)
second_speaker:set_relation(game_object.friend, first_speaker)
end
-- спавним послание Шахматиста
function blank_sheet_2_have ()
 create ("taynik_chess",xyz(448.761,31.1005,-455.823),1427937,3745)
end
-- спавним тайник Дока
function spawn_rookery ()
 create ("taynik_dok",xyz(166.787,-3.478,-140.229),1259387,3688)
 create ("yan_zombied_respawn_3",xyz(165.848,-3.478,-140.519),1259387,3688)
 create ("rad_zombied_respawn_1",xyz(168.455,-3.482,-140.053),1259387,3688)
 create ("rad_zombied_respawn_2",xyz(166.743,1.592,-138.287),1259387,3688)
 create ("yan_zombied_respawn_2",xyz(160.250,-6.978,-141.691),1240395,3688)
 create ("rad_zombied_respawn_1",xyz(159.537,-6.184,-138.818),1239204,3688)
 create ("yan_zombied_respawn_1",xyz(157.277,-6.975,-135.953),1235623,3688)
 create ("rad_zombied_respawn_3",xyz(162.876,-6.975,-135.146),1241606,3688)
end
-- спавним тайник с рисунком
function backpack_drawing ()
 create ("taynik_picture",xyz(-73.638,-2.105,-129.015),3200,801)
 create ("note_3",xyz(-67.025,-6.130,-66.896),3118,717)
end
-- спавним лежбище
function spawn_rookery_1 ()
 create ("telefon",xyz(149.871,-5.896,-139.775),1224670,3688)
 create ("shpriz",xyz(151.921,-6.295,-143.054),1225866,3688)
 create ("trupak",xyz(155.524,-6.550,-139.158),1233170,3688)
 create ("vasya_head",xyz(155.131,-6.214,-142.972),1231922,3688)
 create ("verevka",xyz(152.270,-6.297,-142.864),1227071,3688)
 create ("soap",xyz(150.109,-6.825,-142.046),1224668,3688)
 create ("televizor",xyz(150.073,-5.911,-138.571),1224672,3688)
 create ("kuvalda",xyz(155.792,-6.825,-141.988),1233169,3688)
 create ("pribor",xyz(153.921,-6.824,-139.525),1229478,3688)
 create ("tabletki_1",xyz(155.767,-6.824,-136.974),1231928,3688)
 create ("tabletki_1",xyz(155.467,-6.824,-136.974),1231928,3688)
 create ("tabletki_2",xyz(152.948,-6.824,-139.632),1227074,3688)
 create ("tabletki_2",xyz(152.648,-6.824,-139.632),1227074,3688)
 create ("tabletki_3",xyz(155.248,-6.824,-139.234),1227068,3688)
 create ("tabletki_3",xyz(154.948,-6.824,-139.234),1227068,3688)
 create ("suvorotka",xyz(154.248,-6.824,-139.234),1227068,3688)
 create ("chuchelo_body",xyz(153.664,-6.824,-135.786),1229483,3688)
 create ("box_cigara",xyz(149.702,-5.905,-138.133),1224673,3688)
 create ("antizombie",xyz(149.502,-5.905,-138.133),1224673,3688)
 create ("red_mozg",xyz(152.224,-6.824,-141.595),1225866,3688)
 create ("part_krovosos_red_jaw",xyz(150.194,-6.824,-141.795),1231922,3688)
 create ("part_burer_red_hand",xyz(154.894,-6.224,-143.095),1231922,3688)
 create ("part_digitis_biblio",xyz(149.471,-5.896,-139.775),1224670,3688)
 create ("verevka",xyz(150.426,-6.825,-135.825),1223463,3688)
end
-- спавним живые сердца
function artifact_birth ()
 create ("af_life_heart",xyz(472.807,12.438,437.371),169836,2609)
 create ("af_life_heart",xyz(471.099,12.441,436.002),169836,2609)
 create ("af_life_heart",xyz(473.099,12.438,437.371),169836,2609)
 create ("af_life_heart",xyz(473.807,12.442,437.005),169836,2609)
end
-- спавним мухоморы Леснику
function on_mushrooms ()
 create ("mushroom",xyz(-78.684,2.340,-52.914),15527,3250)
 create ("mushroom",xyz(-80.536,2.283,-33.437),15229,3250)
 create ("mushroom",xyz(-53.366,3.198,-85.253),27142,3258)
 create ("mushroom",xyz(-36.847,3.888,-89.658),36321,3258)
 create ("mushroom",xyz(-70.911,0.404,-149.206),18564,3243)
 create ("mushroom",xyz(-60.118,0.992,-211.581),23930,3245)
 create ("mushroom",xyz(-15.702,-3.995,-233.065),51993,3286)
 create ("mushroom",xyz(-41.317,-0.916,-263.888),35594,3276)
 create ("mushroom",xyz(42.389,-1.294,-276.394),88361,3295)
 create ("mushroom",xyz(47.418,-1.311,-319.567),90011,3297)
 create ("mushroom",xyz(-4.465,-2.352,-267.980),65265,3291)
 create ("mushroom",xyz(2.749,-2.395,-287.980),69709,3291)
 create ("mushroom",xyz(17.775,-0.222,-195.515),76042,3289)
 create ("mushroom",xyz(-80.878,-0.135,-226.048),15317,3245)
 create ("mushroom",xyz(-88.049,0.818,-244.428),14207,3244)
 create ("mushroom",xyz(-75.563,0.210,-246.177),17621,3244)
 create ("mushroom",xyz(-42.042,-0.867,-264.177),34344,3276)
 create ("mushroom",xyz(79.607,-1.242,-303.612),98832,3299)
 create ("mushroom",xyz(72.747,-0.415,-264.371),98763,3298)
 create ("mushroom",xyz(9.447,2.432,-164.768),70962,3293)
end
-- убираем Холода с базы
function del_marsh_barman() 
local se_obj = server_object("marsh_barman") 
if se_obj then 
release(se_obj, true) 
end
end
-- спавним Холода на хуторе
function cold_dead () 
local obj= create ("agr_nebo_chromov1",xyz(-26.551,17.711,266.766),128979,3411)
netpacket:modify(obj, "story_id", 22007)
end
-- убираем Василия из будки
--[[function repairman_out() 
local se_obj = server_object("marsh_remont") 
if se_obj then 
release(se_obj, true) 
end
end]]
-- спавним Васю в тубзике
--[[function repairman_in () 
create ("marsh_remont",xyz(-120.325,1.556,-289.538),83576,3381)
end]]
-- спавним на небе зомби
function note_sky () 
create ("yan_zombied_respawn_3",xyz(-181.265,5.672,-282.698),50164,3364)
create ("rad_zombied_respawn_1",xyz(-155.341,4.211,-233.107),67047,3372)
create ("rad_zombied_respawn_2",xyz(-151.081,3.405,-235.694),69878,3372)
create ("yan_zombied_respawn_2",xyz(-144.225,3.240,-238.721),73614,3372)
create ("rad_zombied_respawn_1",xyz(-146.839,0.288,-352.537),72092,3381)
create ("yan_zombied_respawn_1",xyz(-139.014,0.432,-352.945),76082,3381)
create ("rad_zombied_respawn_3",xyz(-152.276,0.359,-346.679),72460,3381)
create ("yan_zombied_respawn_3",xyz(-181.765,5.672,-282.698),50164,3364)
create ("rad_zombied_respawn_1",xyz(-155.841,4.211,-233.107),67047,3372)
create ("rad_zombied_respawn_2",xyz(-151.581,3.405,-235.694),69878,3372)
create ("yan_zombied_respawn_2",xyz(-144.725,3.240,-238.721),73614,3372)
create ("rad_zombied_respawn_1",xyz(-146.339,0.288,-352.537),72092,3381)
create ("yan_zombied_respawn_1",xyz(-139.514,0.432,-352.945),76082,3381)
create ("rad_zombied_respawn_3",xyz(-152.776,0.359,-346.679),72460,3381)
end
-- спавним бандитов в рыбацкой деревне
function gang_fishermen () 
create ("ds_bandit_respawn_1",xyz(14.457,3.354,-248.012),145795,3423)
create ("ds_bandit_respawn_2",xyz(11.752,3.068,-246.254),144305,3423)
create ("ds_bandit_respawn_3",xyz(4.921,1.933,-242.706),141057,3423)
create ("esc_bandit_respawn_1",xyz(22.072,3.062,-217.744),150136,3433)
create ("esc_bandit_respawn_2",xyz(16.266,2.908,-255.119),146578,3433)
create ("cit_bandit_respawn_1",xyz(19.442,3.208,-215.705),148512,3433)
create ("cit_bandit_respawn_2",xyz(13.357,3.354,-248.015),145795,3423)
end
-- убираем Лысого из бара
function bald_killed() 
local se_obj = story_object(607) 
if se_obj then 
release(se_obj, true) 
end 
end
-- спавним труп Лысого
function trupik_bald() 
local obj= create("dohlji_ljsji",xyz(115.096,-0.004,35.263),33625,1254) 
netpacket:modify(obj, "story_id", 22001)
obj:on_death() 
end
-- спавним кошмарную пирушку
function dreadful_junket () 
create ("yan_zombied_respawn_3",xyz(-62.443,0.341,302.224),106624,3402) 
create ("televizor",xyz(-65.024,1.028,306.925),104965,3402) 
create ("vodka",xyz(-65.301,0.254,304.662),104963,3402) 
create ("kolbasa",xyz(-65.412,0.261,304.480),104963,3402) 
create ("yan_zombied_respawn_1",xyz(-65.735,0.261,304.499),104589,3402) 
create ("bread",xyz(-65.632,0.255,304.656),104589,3402) 
create ("vodka",xyz(-65.272,0.250,304.782),104963,3402) 
create ("yan_zombied_respawn_1",xyz(-64.838,0.250,304.840),104963,3402) 
create ("vodka",xyz(-64.539,0.243,304.893),105359,3402) 
create ("oceanic815",xyz(-65.190,0.261,304.473),104963,3402) 
create ("yan_zombied_respawn_1",xyz(-62.522,0.320,303.278),106625,3402) 
create ("guitar_a",xyz(-65.295,0.195,303.556),104962,3402) 
create ("bread",xyz(-65.920,0.210,305.931),104591,3402) 
create ("yan_zombied_respawn_2",xyz(-63.959,0.195,306.283),105766,3402) 
create ("vodka",xyz(-63.976,0.290,306.679),105763,3402) 
create ("sandwich",xyz(-65.270,0.387,302.344),104960,3402) 
create ("note_2",xyz(-64.780,0.222,305.549),104965,3402) 
create ("sigaret",xyz(-64.021,0.248,304.793),105764,3402) 
create ("yan_zombied_respawn_1",xyz(-62.299,0.423,299.840),106620,3402) 
create ("vodka",xyz(-67.968,0.255,304.636),103608,3402) 
create ("conserva",xyz(-65.301,0.285,303.744),104962,3402) 
create ("yan_zombied_respawn_3",xyz(-64.854,0.255,304.544),104968,3402) 
create ("energy_drink",xyz(-64.561,0.263,304.424),105358,3402) 
create ("kolbasa",xyz(-62.376,0.380,301.060),106622,3402) 
create ("yan_zombied_respawn_2",xyz(-62.543,0.341,302.224),106624,3402) 
create ("blank_sheet_15",xyz(-42.226,-0.653,266.410),118300,3402) 
create ("oceanic815",xyz(-63.424,0.297,303.795),105763,3402)
create ("zone_fog_cigarette",xyz(-66.424,0.297,303.795),105763,3402)
create ("rad_zombied_respawn_1",xyz(-67.077,0.272,304.142),103921,3402)
create ("rad_zombied_respawn_2",xyz(-67.123,0.229,305.443),103923,3402)
create ("rad_zombied_respawn_3",xyz(-63.151,0.237,305.121),106193,3402)
end
-- спавним зомби в саркофаге
function zombie_sarcophagus ()
create ("rad_zombied_respawn_1",xyz(69.483,67.249,-16.713),6321,2417)
create ("rad_zombied_respawn_2",xyz(65.962,67.249,-15.652),6321,2417)
create ("rad_zombied_respawn_3",xyz(64.532,67.249,-11.295),6321,2417)
end
-- спавним записку в кинотеатре и монолит
function cinema_diary ()
create ("diary_chess_3",xyz(12.142,4.477,204.247),113860,2198)
create ("pri_monolith_respawn_1",xyz(-7.545,2.778,197.015),92463,2198)
create ("pri_monolith_respawn_2",xyz(-1.965,3.228,195.865),96693,2198)
create ("pri_monolith_respawn_1",xyz(2.311,3.666,197.928),104827,2198)
create ("pri_monolith_respawn_3",xyz(2.772,3.673,205.452),106445,2198)
create ("pri_monolith_respawn_3",xyz(-1.103,3.316,208.998),100579,2198)
create ("pri_monolith_respawn_2",xyz(-7.126,2.779,205.824),93429,2198)
end
-- спавним блокнот шахтера и зомби
function notebook_coalminer ()
create ("notebook_oldman",xyz(49.620,33.439,492.524),160355,2982)
create ("rad_zombied_respawn_1",xyz(49.120,33.439,492.524),160355,2982)
create ("rad_zombied_respawn_2",xyz(48.720,33.439,491.524),160355,2982)
create ("rad_zombied_respawn_3",xyz(50.120,33.439,492.224),160355,2982)
end
-- спавним записки и монолит
function sports_sniper ()
create ("blank_sheet_16",xyz(68.433,0.987,341.615),180468,2157)
create ("diary_chess_4",xyz(-3.386,-3.061,187.814),97943,2195)
create ("tank_spawn_zasada",xyz(65.339,8.456,277.120),177070,2263)
create ("tank_spawn_zasada1",xyz(-2.669,8.456,277.976),98896,2261)
create ("tank_spawn_zasada2",xyz(90.451,8.457,423.394),201880,2265)
create ("tank_spawn_zasada3",xyz(59.322,8.458,424.992),171901,2265)
create ("tank_spawn_zasada4",xyz(17.420,8.456,424.643),123642,2266)
create ("tank_spawn_zasada5",xyz(-21.630,8.457,424.372),77659,2266)
create ("tank_spawn_zasada6",xyz(42.594,8.458,277.168),154334,2263)
create ("tank_spawn_zasada1",xyz(33.120,8.467,277.570),143481,2263)
end
-- спавним черную метку
function black_tag ()
create ("taynik_black",xyz(15.940,-5.863,-330.913),193071,841)
end
-- убираем Тень Монолита
--[[function out_labirint_shade() 
local se_obj = server_object("labirint_shade_monolit") 
if se_obj then 
release(se_obj, true) 
end
end]]
-- спавним Тень смертного
function shade_dead () 
local obj= create ("labirint_shade_monolit1",xyz(-322.691,62.234,196.914),32818,2987)
netpacket:modify(obj, "story_id", 22006)
end
-- смска Сахара
function sugar_causes(first_speaker, second_speaker)
sms("%c[255,160,160,160]".."САХАРОВ:".."\\n".."%c[255,255,128,128]Меченый, я вас давно жду! Не испытывайте моё любопытство и терпение. И Круглов куда-то пропал... Послал его в Х-16 замеры делать, а он второй день отсутствует. Идите ко мне. Мне нужна ваша помощь. Конец связи!", 5, nil, 30000, nil, [[sms\saharov\sugar_causes]]) 
end
 -- проверяем наличие инфы
function shadow_kill_have()
return has("blank_sheet_5",1) 
end
-- получаем награду
function shadow_kill_done(first_speaker, second_speaker)
got("ammo_zhekan_izomorf")
end
-- убираем Круглова из бункера
function round_loss() 
local se_obj = server_object("yan_scientist_help") 
if se_obj then 
release(se_obj, true) 
end
end
-- спавним сумасшедшего и зомби
function mad_scientist () 
mad_scientist_spawn()
create ("yan_zombied_respawn_3",xyz(-36.241,-4.123,-17.210),3061,1534)
create ("rad_zombied_respawn_1",xyz(-50.193,3.468,-18.413),2070,1535)
create ("rad_zombied_respawn_2",xyz(-46.450,3.468,-4.466),2990,1532)
create ("yan_zombied_respawn_2",xyz(-24.603,11.563,-8.902),3683,1532)
create ("rad_zombied_respawn_1",xyz(-63.139,11.564,-17.655),1353,1530)
create ("yan_zombied_respawn_1",xyz(-52.517,19.179,1.848),1993,1530)
create ("rad_zombied_respawn_3",xyz(-53.517,19.179,1.848),1993,1530)
end
function mad_scientist_1 ()
create ("yan_zombied_respawn_3",xyz(-255.799,-18.422,-43.058),46,1458)
create ("rad_zombied_respawn_1",xyz(-247.805,-18.828,-41.839),108,1458)
create ("yan_zombied_respawn_2",xyz(-235.769,-18.893,-41.727),208,1458)
end
function mad_scientist_spawn() 
local obj= create ("yan_ecolog_help1",xyz(34.370,5.650,-13.821),4788,1538)
netpacket:modify(obj, "story_id", 22008)
end
-- спавним Живую Воду
function water_life () 
create ("shadow_secret",xyz(-179.709,1.058,40.225),53505,674)
end
-- спавним сельпо
function general_note () 
create ("diary_chess_6",xyz(-42.132,3.191,-7.610),4291,3326)
end
-- спавним рюкзак био
function backpack_bio_1 () 
create ("secret_biorobot_1",xyz(59.117,45.870,-259.745),402534,3114)
create ("tank_spawn_zasada",xyz(58.127,40.874,-264.361),404147,3114)
create ("tank_spawn_zasada1",xyz(63.618,35.013,-261.541),410868,3114)
create ("tank_spawn_zasada2",xyz(66.458,30.975,-268.517),414143,3114)
create ("tank_spawn_zasada3",xyz(61.340,34.983,-262.904),408352,3114)
create ("tank_spawn_zasada4",xyz(69.206,34.678,-261.853),417381,3114)
create ("tank_spawn_zasada5",xyz(59.436,34.787,-268.674),405823,3114)
create ("tank_spawn_zasada6",xyz(57.436,34.787,-268.674),405823,3114)
end
-- спавним госпиталь
function damned_hospital () 
create ("pri_monolith_respawn_1",xyz(-89.741,25.045,750.880),2717,3043)
create ("tank_spawn_zasada5",xyz(-85.788,28.690,755.260),3792,3052)
create ("explosive_mobiltank",xyz(-87.461,31.999,736.321),3334,3052)
create ("pri_monolith_respawn_2",xyz(-84.710,31.959,735.292),4005,3052)
create ("explosive_mobiltank",xyz(-90.340,31.958,737.482),2485,3052)
create ("tank_spawn_zasada",xyz(-86.888,31.959,734.231),3535,3052)
create ("explosive_mobiltank",xyz(-86.185,32.015,748.048),3790,3052)
create ("pri_monolith_respawn_3",xyz(-75.811,32.196,683.510),6323,3061)
create ("explosive_mobiltank",xyz(-77.583,32.386,683.953),6323,3061)
create ("tank_spawn_zasada",xyz(-86.965,31.927,773.140),3351,3048)
create ("explosive_mobiltank",xyz(-92.845,31.960,724.863),1489,3034)
create ("explosive_mobiltank",xyz(-91.943,31.958,722.423),2098,3034)
end
function damned_hospital_1 ()
create ("dreadful_hospital",xyz(-92.796,25.242,560.987),2519,3060) 
create ("tank_spawn_zasada6",xyz(-74.087,31.958,656.989),7364,3063)
create ("tank_spawn_zasada",xyz(-76.876,31.962,662.426),6626,3064)
create ("tank_spawn_zasada1",xyz(-85.831,31.960,678.044),3739,3055)
create ("tank_spawn_zasada2",xyz(-93.601,31.961,677.993),1226,3033)
create ("tank_spawn_zasada3",xyz(-97.960,31.959,657.509),566,3032)
create ("tank_spawn_zasada4",xyz(-96.704,31.959,643.878),744,3030)
create ("tank_spawn_zasada5",xyz(-76.449,31.960,632.961),6785,3066)
create ("tank_spawn_zasada6",xyz(-78.649,31.960,632.960),6785,3066)
end
function damned_hospital_2 () 
create ("tank_spawn_zasada6",xyz(-84.937,26.780,750.993),4258,3043) 
create ("explosive_mobiltank",xyz(-84.780,26.774,750.987),4258,3043) 
create ("explosive_fuelcan",xyz(-86.101,32.243,747.207),3786,3052) 
create ("tank_spawn_zasada",xyz(-87.501,32.125,743.412),3340,3052) 
create ("explosive_barrel",xyz(-85.179,31.958,743.440),4016,3052) 
create ("tank_spawn_zasada5",xyz(-85.989,32.001,743.339),3781,3052) 
create ("explosive_fuelcan",xyz(-85.354,31.959,744.422),4017,3052) 
create ("tank_spawn_zasada3",xyz(-86.128,31.959,744.856),3783,3052) 
create ("explosive_barrel",xyz(-85.110,31.959,744.771),4018,3052) 
create ("explosive_mobiltank",xyz(-86.593,31.958,745.731),3548,3052) 
create ("tank_spawn_zasada4",xyz(-86.091,31.958,3052),3785,3052) 
create ("tank_spawn_zasada6",xyz(-86.9002,31.959,744.406),3546,3052) 
create ("explosive_barrel",xyz(-85.157,31.962,682.189),3971,3061) 
create ("explosive_mobiltank",xyz(-82.554,31.960,680.997),4834,3061) 
create ("explosive_fuelcan",xyz(-81.321,31.958,681.672),5221,3061) 
create ("tank_spawn_zasada3",xyz(-94.076,31.960,648.486),1185,3032) 
create ("explosive_barrel",xyz(-81.777,31.962,648.424),5020,3063) 
create ("explosive_mobiltank",xyz(-75.883,31.961,676.742),7097,3067) 
create ("explosive_fuelcan",xyz(-78.858,31.960,677.418),6068,3067) 
create ("tank_spawn_zasada6",xyz(-75.849,31.959,678.297),7098,3067) 
create ("tank_spawn_zasada2",xyz(-76.701,31.960,675.517),6647,3067) 
create ("explosive_barrel",xyz(-74.022,32.217,727.391),7370,3068) 
create ("tank_spawn_zasada6",xyz(-79.532,32.291,736.002),5874,3052) 
create ("explosive_barrel",xyz(-81.640,32.293,737.870),5079,3052) 
create ("tank_spawn_zasada",xyz(-98.495,32.216,727.342),543,3034) 
create ("explosive_barrel",xyz(-98.401,25.220,732.182),544,3035) 
create ("tank_spawn_zasada1",xyz(-77.743,25.222,731.688),6491,3069)
create ("explosive_barrel",xyz(-73.990,25.220,732.185),7371,3069)
create ("tank_spawn_zasada2",xyz(-86.195,32.217,681.633),3496,3047)
create ("explosive_barrel",xyz(-70.158,32.216,669.553),7735,3064)
create ("tank_spawn_zasada3",xyz(-102.418,32.217,669.530),235,3033)
create ("explosive_barrel",xyz(-102.373,32.216,631.530),256,3030)
create ("tank_spawn_zasada5",xyz(-70.155,32.216,631.726),7733,3066)
end
-- спавним Батю
function envoy_hell () 
create ("yantar_baty",xyz(12.145,-3.373,-205.187),48807,1469)
end
-- делаем ГГ врагом в Военной Лаборатории
function enemyactor(community1, community2) 
relation_registry.set_community_goodwill ("freedom", "actor", -5000) 
end
-- смска Сахарова
function call_maniac(first_speaker, second_speaker)
sms("%c[255,160,160,160]".."САХАРОВ:".."\\n".."%c[255,255,128,128]Коллега, артефакт у меня. Выходите на место договорённости! Конец связи!", 5, nil, 30000, nil, [[sms\saharov\call_maniac]]) 
end
-- смска Шахматиста2
function cunning_chess_1(first_speaker, second_speaker)
sms("%c[255,160,160,160]".."ШАХМАТИСТ:".."\\n".."%c[255,255,128,128]Молодец! Я уже близок к созданию своего Зомби. Кто знает? Может им станешь именно ты? А может Клык или Призрак? Я ещё не решил. А пока ищи тайники и готовься к нашей встрече без галстуков, но в костюмах из кожи... Ха-ха-ха!", 5, nil, 30000, nil, "chess_voice\\cunning_chess_1") 
end
-- спавним труп Бати
function trupik_father() 
local obj= create("yantar_baty1",xyz(-161.752,46.066,-544.650),149446,3088) 
netpacket:modify(obj, "story_id", 22002)
obj:on_death() 
end
 -- проверяем наличие арта
function freight_transfer_have()
return has("af_alive_water",1) 
end
-- отдаем арт Бате
function freight_transfer(first_speaker, second_speaker) 
lost("af_alive_water") 
end
 -- проверяем наличие объекта
function glitch_object_have()
return has("af_rusty_sea-urchin1",1) 
end
-- отдаем объект Колмогору, получаем награду
function glitch_object_done(first_speaker, second_speaker)
lost("af_rusty_sea-urchin1",1)
got("ammo_9x39_izomorf")
end
-- проверяем наличные у ГГ
function inspection_nal() 
return db.actor:money()>=500000 
end
-- забираем деньги
function take_away(actor, npc) 
lost_money(500000)
end
-- спавним записки на Затоне
function notes_backwater ()
 create ("note_6",xyz(-177.244,7.994,145.749),585541,3670)
 create ("note_7",xyz(214.088,17.005,1.852),1331276,3684)
 create ("note_8",xyz(432.141,38.048,-192.507),1672074,3693)
 create ("blank_sheet_20",xyz(121.307,-7.346,175.762),1175692,3686)
 create ("yan_zombied_respawn_3",xyz(224.803,6.977,-33.324),1347942,3688)
 create ("rad_zombied_respawn_1",xyz(230.356,6.977,-36.647),1357938,3688)
 create ("rad_zombied_respawn_2",xyz(238.531,8.092,-6.348),1373227,3684)
 create ("yan_zombied_respawn_2",xyz(237.424,8.092,-2.718),1370631,3684)
 create ("rad_zombied_respawn_1",xyz(192.145,6.580,-27.742),1292832,3688)
 create ("yan_zombied_respawn_1",xyz(193.186,6.582,3.155),1295136,3684)
 create ("rad_zombied_respawn_3",xyz(342.864,8.091,-6.706),1365443,3684)
 create ("ds_bandit_respawn_1",xyz(-163.781,7.894,105.230),613909,3670)
 create ("ds_bandit_respawn_2",xyz(-170.936,7.543,117.618),599556,3670)
 create ("ds_bandit_respawn_3",xyz(-183.011,8.290,105.010),576278,3670)
 create ("esc_bandit_respawn_1",xyz(-182.187,8.952,92.748),578910,3670)
 create ("esc_bandit_respawn_2",xyz(-180.101,9.412,77.411),581562,3670)
 create ("cit_bandit_respawn_1",xyz(-164.486,8.951,75.645),612450,3670)
 create ("cit_bandit_respawn_2",xyz(-163.027,8.452,88.428),615310,3670)
 create ("killer_boevik6",xyz(430.046,33.235,-275.924),1670825,3693)
 create ("killer_boevik5",xyz(429.926,33.257,-2265.305),1670825,3693)
 create ("killer_boevik4",xyz(429.250,33.257,-253.910),1670825,3693)
 create ("killer_boevik3",xyz(430.148,33.255,-240.460),1670825,3693)
 create ("killer_boevik2",xyz(430.612,33.251,-230.161),1672074,3693)
 create ("killer_boevik1",xyz(426.052,33.471,-167.784),1670825,3693)
 create ("mill_sniper_harris",xyz(6.427,4.552,37.493),956742,3677)
 create ("mill_sniper_nick",xyz(107.399,1.361,179.640),1151768,3686)
 create ("mill_sniper_croker",xyz(-2.589,4.603,36.416),938433,3677)
 create ("mill_sniper_jonn",xyz(116.025,2.259,183.358),1165999,3686)
end
-- получаем контракт от Сахара
function contract_work(first_speaker, second_speaker)
got("ticket_cinema_1")
end
-- отдаем контракт Лентяю
function contract_work_1(first_speaker, second_speaker) 
lost("ticket_cinema_1") 
end
-- получаем подписанный контракт от Лентяя
function contract_work_2(first_speaker, second_speaker)
got("ticket_cinema_2")
end
-- проверяем наличие подписанного контракта
function sugar_contract_have()
return has("ticket_cinema_2",1)
end
-- отдаем контракт, получаем награду
function sugar_contract_done(first_speaker, second_speaker)
lost("ticket_cinema_2",1)
got("wpn_beretta_m1")
second_speaker:set_relation(game_object.friend, first_speaker)
sms("%c[255,160,160,160]".."ЛЕНТЯЙ:".."\\n".."%c[255,255,128,128]Меченый, будь другом, подойди ко мне, дело есть!", 5, nil, 30000, nil, [[sms\lentiy\sugar_contract_done_1]])  
end
-- убираем Лентяя с Военной Лаборатории
function del_idler_wons() 
local se_obj = server_object("warlab_sekret_ekolog1") 
if se_obj then 
release(se_obj, true) 
end
end
-- спавним Лентяя на Янтаре
function del_idler_in () 
create ("warlab_sekret_ekolog2",xyz(41.664,-11.893,-275.241),60062,1480)
end
-- спавним засаду
function ambush_laboratory ()
create ("tank_spawn_zasada1",xyz(-46.209,3.468,-4.697),2287,1532)
create ("tank_spawn_zasada2",xyz(-27.397,3.467,-5.074),3575,1532)
create ("tank_spawn_zasada3",xyz(-33.969,11.563,2.415),3203,1532)
create ("explosive_barrel",xyz(-58.351,19.178,-17.532),1703,1530)
create ("tank_spawn_zasada5",xyz(-49.108,19.179,2.317),2149,1530)
create ("explosive_barrel",xyz(-75.102,21.679,-15.143),998,1530)
end
-- спавним засаду
function ambush_laboratory_one ()
create ("tank_spawn_zasada1",xyz(-46.209,3.468,-4.697),2287,1532)
create ("tank_spawn_zasada2",xyz(-27.397,3.467,-5.074),3575,1532)
create ("tank_spawn_zasada3",xyz(-33.969,11.563,2.415),3203,1532)
create ("explosive_barrel",xyz(-58.751,19.178,-17.532),1703,1530)
create ("tank_spawn_zasada5",xyz(-49.108,19.179,2.317),2149,1530)
create ("explosive_barrel",xyz(-75.502,21.679,-15.143),998,1530)
end
-- делаем ГГ врагом на Янтаре
function enemyactor_1(community1, community2) 
relation_registry.set_community_goodwill ("ecolog", "actor", -5000) 
end
-- и наоборот
function enemyactor_2(community1, community2) 
relation_registry.set_community_goodwill ("ecolog", "actor", 5000) 
end
-- спавним монстров и записку в тоннеле
function tunnel_burer()
create("blank_sheet_14",xyz(-154.617,3.078,-28.294),6161,3240)
create("burer_strong",xyz(-140.743,-6.193,-63.734),7291,3240)
create("m_poltergeist_dd",xyz(-114.929,-6.110,-57.747),9849,3240)
create("zombie_strong",xyz(-168.607,2.178,-23.621),4323,3240)
create("zombie_strong",xyz(-151.868,2.256,-17.591),6447,3240)
create("zombie_immortal",xyz(-162.979,2.179,-24.693),4984,3240)
create("zombie_babka_weak",xyz(-152.558,2.268,0.742),6338,3240)
create("zombie_babka_normal",xyz(-150.110,2.254,15.889),6825,3240)
create("zombie_babka_strong",xyz(-189.472,2.231,13.596),2190,3240)
end
-- спавним биотайник2
function bio_proofs_2 ()
create ("secret_biorobot_2",xyz(-37.330,11.703,19.516),301655,3634)
end
-- спавним биотайник3
function bio_proofs_3 ()
create ("secret_biorobot_3",xyz(-34.719,10.465,-31.789),3051,1534)
create ("tank_spawn_zasada1",xyz(-46.209,3.468,-4.697),2287,1532)
create ("tank_spawn_zasada2",xyz(-27.397,3.467,-5.074),3575,1532)
create ("tank_spawn_zasada3",xyz(-33.969,11.563,2.415),3203,1532)
create ("explosive_barrel",xyz(-58.851,19.178,-17.532),1703,1530)
create ("tank_spawn_zasada5",xyz(-49.108,19.179,2.317),2149,1530)
create ("explosive_barrel",xyz(-75.602,21.679,-15.143),998,1530)
end
-- спавним биотайник4
function bio_proofs_4 ()
create ("secret_biorobot_4",xyz(-1.496,-17.174,45.445),5431,2753)
create ("tank_spawn_zasada1",xyz(-20.138,-8.990,6.347),3474,2674)
create ("tank_spawn_zasada2",xyz(20.913,-8.994,19.804),8710,2686)
create ("tank_spawn_zasada3",xyz(-13.806,-8.991,7.230),3965,2782)
create ("tank_spawn_zasada4",xyz(7.363,-23.522,6.904),7687,2703)
create ("tank_spawn_zasada5",xyz(-22.259,-23.521,-9.777),3028,2784)
create ("tank_spawn_zasada6",xyz(-37.149,-21.831,56.731),1704,2738)
end
-- удаляем Калугина
function del_dar_corpse()  
local se_obj = story_object(450) 
if se_obj then 
release(se_obj, true) 
end 
end
-- спавним труп Калугина
function kalugin_corpse() 
local obj= create("dar_corpse_kalugin1",xyz(23.737,4.189,17.257),6332,1120) 
netpacket:modify(obj, "story_id", 22003)
obj:on_death() 
end
-- спавним засаду
function bio_proofs_one ()
create ("tank_spawn_zasada6",xyz(-34.719,10.465,-31.789),3051,1534)
create ("tank_spawn_zasada1",xyz(-46.209,3.468,-4.697),2287,1532)
create ("tank_spawn_zasada2",xyz(-27.397,3.467,-5.074),3575,1532)
create ("tank_spawn_zasada3",xyz(-33.969,11.563,2.415),3203,1532)
create ("explosive_barrel",xyz(-58.851,19.178,-17.532),1703,1530)
create ("tank_spawn_zasada5",xyz(-49.108,19.179,2.317),2149,1530)
create ("explosive_barrel",xyz(-75.602,21.679,-15.143),998,1530)
end
-- спавним засаду
function bio_proofs_two ()
create ("tank_spawn_zasada6",xyz(-1.496,-17.174,45.445),5431,2753)
create ("tank_spawn_zasada1",xyz(-20.138,-8.990,6.347),3474,2674)
create ("tank_spawn_zasada2",xyz(20.913,-8.994,19.804),8710,2686)
create ("tank_spawn_zasada3",xyz(-13.806,-8.991,7.230),3965,2782)
create ("tank_spawn_zasada4",xyz(7.363,-23.522,6.904),7687,2703)
create ("tank_spawn_zasada5",xyz(-22.259,-23.521,-9.777),3028,2784)
create ("tank_spawn_zasada6",xyz(-37.149,-21.831,56.731),1704,2738)
end
-- спавним засаду в Х-18
function bioambush_1 ()
create ("tank_spawn_zasada",xyz(30.434,4.189,11.450),6991,1119)
create ("tank_spawn_zasada1",xyz(-15.816,4.188,8.247),1108,1126)
create ("tank_spawn_zasada2",xyz(-7.952,4.206,-0.753),1842,1112)
create ("tank_spawn_zasada3",xyz(18.833,4.189,-13.096),5641,1117)
create ("tank_spawn_zasada4",xyz(-8.103,9.174,0.292),1790,1110)
create ("tank_spawn_zasada5",xyz(-5.161,4.190,7.480),2138,1125)
create ("tank_spawn_zasada6",xyz(6.282,4.187,-0.0106),3641,1116)
end
-- спавним биотайник6
function bio_proofs_6 ()
create ("secret_biorobot_6",xyz(-12.018,30.283,175.316),81747,2196)
create ("blank_sheet_6",xyz(10.273,1.245,102.586),117924,2142)
create ("blank_sheet_7",xyz(-55.285,15.426,129.052),45373,2126)
create ("blank_sheet_8",xyz(-53.412,15.452,149.211),47016,2212)
create ("blank_sheet_9",xyz(-34.449,12.232,165.088),77998,2190)
create ("blank_sheet_10",xyz(-14.954,19.181,179.197),84745,2190)
create ("blank_sheet_11",xyz(-17.596,27.814,175.408),81747,2196)
end
-- спавним засаду монстров в Х-18
function monsters_attack()
create("snork_normal",xyz(22.166,-14.817,77.371),6182,1163)
create("snork_normal",xyz(29.900,-6.620,-13.385),6819,1140)
create("burer_strong",xyz(38.806,-8.650,-13.007),7330,1141)
create("snork_normal",xyz(34.023,-10.815,4.239),7201,1136)
create("snork_stronger",xyz(-32.485,-10.813,-20.422),460,1152)
create("snork_normal",xyz(-41.174,-10.815,4.756),193,1147)
create("burer_strong",xyz(-2.877,-10.815,27.385),2379,1145)
create("snork_jumper",xyz(16.193,-12.429,17.355),5256,1155)
create("snork_normal",xyz(-24.676,-10.783,-4.139),762,1149)
create("m_controller_act",xyz(-43.913,-13.006,-20.373),125,1153)
create("snork_normal",xyz(-25.342,-10.814,-4.076),742,1149)
create("snork_stronger",xyz(6.276,-12.431,8.287),4080,1156)
create("snork_normal",xyz(10.033,4.189,6.420),4196,1123)
create("snork_normal",xyz(24.427,4.188,16.212),6423,1120)
create("m_poltergeist_dd",xyz(-5.161,4.190,7.480),2138,1125)
create("snork_normal",xyz(-10.137,4.189,-5.015),1669,1166)
create("snork_normal",xyz(3.513,4.198,-17.012),3266,1115)
create("snork_jumper",xyz(18.885,4.188,-13.273),5641,1117)
create("snork_normal",xyz(10.621,-16.347,55.015),4359,1161)
create("snork_normal",xyz(29.012,-13.534,39.853),6519,1161)
create("snork_stronger",xyz(14.250,-16.094,32.304),4926,1159)
create("snork_normal",xyz(8.965,-16.099,32.289),4110,1159)
create("m_controller_act",xyz(-3.248,-16.344,41.625),2465,1162)
create("snork_normal",xyz(28.205,-10.814,4.562),6788,1137)
create("scelet_strong",xyz(40.671,-10.815,-7.052),7473,1136)
create("scelet_strong",xyz(40.437,-6.285,-17.860),7465,1141)
create("scelet_strong",xyz(18.649,-6.620,-18.381),5762,1140)
create("snork_normal",xyz(-1.773,-16.345,68.848),2498,1164)
create("snork_normal",xyz(1.0204,-14.182,29.610),2919,1157)
create("m_poltergeist_dd",xyz(28.605,-10.814,4.562),6788,1137)
create("snork_normal",xyz(1.223,-14.182,29.633),3022,1157)
create("scelet_strong",xyz(-11.045,4.184,-8.953),1725,1166)
create("scelet_strong",xyz(40.937,-6.285,-17.860),7465,1141)
create("scelet_strong",xyz(16.649,-6.620,-18.381),5762,1140)
end
-- спавним Фрица
function monolith_attack ()
create ("pri_monolith_ambush_exo1",xyz(-7.860,9.312,-6.816),1822,1110)
create ("tank_spawn_zasada",xyz(-0.898,4.353,-11.138),2669,1127)
create ("tank_spawn_zasada1",xyz(30.434,4.189,11.450),6991,1119)
create ("tank_spawn_zasada2",xyz(-15.816,4.188,8.247),1108,1126)
create ("tank_spawn_zasada3",xyz(-7.952,4.206,-0.753),1842,1112)
create ("tank_spawn_zasada4",xyz(18.833,4.189,-13.096),5641,1117)
create ("tank_spawn_zasada5",xyz(-1.779,9.321,-3.807),2410,1109)
create ("tank_spawn_zasada6",xyz(-1.022,9.312,0.931),2795,1109)
create ("tank_spawn_zasada",xyz(-8.103,9.174,0.292),1790,1110)
create ("tank_spawn_zasada1",xyz(6.282,4.187,-0.0106),3641,1116)
create ("tank_spawn_zasada2",xyz(-6.590,1.691,-14.101),1931,1128)
create ("tank_spawn_zasada3",xyz(-6.657,-3.305,-12.349),1938,1130)
create ("tank_spawn_zasada4",xyz(-6.734,-8.307,-12.448),1937,1132)
create ("tank_spawn_zasada5",xyz(-40.616,-13.007,-20.590),202,1153)
create ("tank_spawn_zasada6",xyz(40.343,-6.359,-32.094),7445,1142)
create ("tank_spawn_zasada",xyz(-0.392,9.318,-11.162),2678,1109)
say([[chess_voice\aes2_mooze_predator_add_r]])
end
-- спавним засаду
function monolith_attack_two ()
create ("tank_spawn_zasada6",xyz(-7.860,9.312,-6.816),1822,1110)
create ("tank_spawn_zasada",xyz(-0.898,4.353,-11.138),2669,1127)
create ("tank_spawn_zasada1",xyz(30.434,4.189,11.450),6991,1119)
create ("tank_spawn_zasada2",xyz(-15.816,4.188,8.247),1108,1126)
create ("tank_spawn_zasada3",xyz(-7.952,4.206,-0.753),1842,1112)
create ("tank_spawn_zasada4",xyz(18.833,4.189,-13.096),5641,1117)
create ("tank_spawn_zasada5",xyz(-1.779,9.321,-3.807),2410,1109)
create ("tank_spawn_zasada6",xyz(-1.022,9.312,0.931),2795,1109)
create ("tank_spawn_zasada",xyz(-8.103,9.174,0.292),1790,1110)
create ("tank_spawn_zasada1",xyz(6.282,4.187,-0.0106),3641,1116)
create ("tank_spawn_zasada2",xyz(-6.590,1.691,-14.101),1931,1128)
create ("tank_spawn_zasada3",xyz(-6.657,-3.305,-12.349),1938,1130)
create ("tank_spawn_zasada4",xyz(-6.734,-8.307,-12.448),1937,1132)
create ("tank_spawn_zasada5",xyz(-40.616,-13.007,-20.590),202,1153)
create ("tank_spawn_zasada6",xyz(40.343,-6.359,-32.094),7445,1142)
create ("tank_spawn_zasada",xyz(-0.392,9.318,-11.162),2678,1109)
end
-- убираем Витамина
function del_warlab_vitamin() 
local se_obj = server_object("warlab_vitamin") 
if se_obj then 
release(se_obj, true) 
end
end
-- спавним Витамина2
function warlab_vitamin_in () 
create ("warlab_vitamin1",xyz(4.146,-7.3103,10.747),5137,3197)
end
-- смска от Витамина
function cunning_vitamin(first_speaker, second_speaker)
sms("%c[255,160,160,160]".."ВИТАМИН:".."\\n".."%c[255,255,128,128]Меченый, закончишь с Фрицем, загляни в Военную Лабораторию, есть серьёзный разговор!", 5, nil, 30000) 
end
-- спавним тайник Химеры
function hiding_chimera ()
create ("document_chimera",xyz(145.0805,-3.9204,-310.189),1121536,2900)
create ("land_arhara_sniper_sp_7",xyz(144.722,-1.845,-311.203),1119157,2900)
create ("land_arhara_sniper_sp_8",xyz(138.786,-4.007,-309.152),1110704,2900)
create ("land_arhara_sniper_sp_1",xyz(134.358,-4.057,-304.935),1103233,2900)
create ("land_arhara_sniper_sp_2",xyz(130.929,-4.548,-296.006),1097231,2900)
create ("land_arhara_sniper_sp_3",xyz(138.994,-3.997,-309.521),1111936,2900)
create ("land_arhara_sniper_sp_4",xyz(142.205,-4.088,-301.743),1116794,2900)
create ("land_arhara_sniper_sp_5",xyz(135.156,-4.371,-300.742),1104506,2900)
create ("land_arhara_sniper_sp_6",xyz(151.047,-3.639,-308.905),1132539,2900)
create ("land_arhara_sniper_sp_7",xyz(143.722,-1.845,-311.203),1119157,2900)
create ("land_arhara_sniper_sp_8",xyz(140.569,-4.395,-297.558),1114388,2900)
end
-- убираем Химеру
function del_land_chimaera() 
local se_obj = story_object(9997) 
if se_obj then 
release(se_obj, true) 
end 
end
-- спавним труп Химеры
function trupik_chimaera() 
local obj= create("land_sniper_chimaera1",xyz(143.722,-1.845,-311.203),1119157,2900) 
netpacket:modify(obj, "story_id", 22004)
obj:on_death() 
end
-- отдаем дневник Циклопу
function document_diary(first_speaker, second_speaker) 
lost("diary_chess_2") 
end
-- получаем дненик обратно
function document_diary_in(first_speaker, second_speaker)
got("diary_chess_2")
end
-- проверяем наличие письма
function letter_object_have()
return has("ticket_cinema_3",1) 
end
-- отдаем письмо Циклопу, получаем награду
function letter_object_done(first_speaker, second_speaker)
lost("ticket_cinema_3",1)
got("ammo_9x39_izomorf")
end
-- убираем Отца с Кордона
function del_esc_father() 
local se_obj = server_object("esc_father_pant") 
if se_obj then 
release(se_obj, true) 
end
end
-- спавним Отца и зомби
function chess_ending_1 () 
create ("esc_father_pant",xyz(-129.207,21.564,-30.498),11,1529)
create ("yan_zombied_respawn_3",xyz(-46.209,3.468,-4.697),2287,1532)
create ("rad_zombied_respawn_1",xyz(-50.193,3.468,-18.413),2070,1535)
create ("rad_zombied_respawn_2",xyz(-46.450,3.468,-4.466),2990,1532)
create ("yan_zombied_respawn_2",xyz(-24.603,11.563,-8.902),3683,1532)
create ("rad_zombied_respawn_1",xyz(-63.139,11.564,-17.655),1353,1530)
create ("yan_zombied_respawn_1",xyz(-52.517,19.179,1.848),1993,1530)
create ("rad_zombied_respawn_3",xyz(-53.517,19.179,1.848),1993,1530)
create ("yan_zombied_respawn_3",xyz(-36.241,-4.123,-17.210),3061,1534)
create ("rad_zombied_respawn_1",xyz(-53.193,3.468,-18.413),2070,1535)
create ("rad_zombied_respawn_2",xyz(-45.450,3.468,-4.466),2990,1532)
create ("yan_zombied_respawn_2",xyz(-23.603,11.563,-8.902),3683,1532)
create ("rad_zombied_respawn_1",xyz(-62.139,11.564,-17.655),1353,1530)
create ("explosive_fuelcan",xyz(-111.282,21.564,-26.858),266,1529)
create ("explosive_barrel",xyz(-111.837,21.563,-28.206),266,1529)
create ("explosive_barrel",xyz(-129.7707,20.783,-23.341),18,1529)
create ("explosive_barrel",xyz(-129.121,21.6908,-27.474),27,1529)
create ("explosive_barrel",xyz(-129.171,21.662,-33.565),8,1529)
create ("explosive_barrel",xyz(-123.905,21.564,-28.0107),102,1529)
create ("explosive_fuelcan",xyz(-131.268,21.522,-22.633),2,1529)
create ("explosive_barrel",xyz(-130.147,21.563,-32.686),3,1529)
create ("explosive_barrel",xyz(-129.138,21.563,-34.449),19,1529)
create ("explosive_fuelcan",xyz(-123.131,21.564,-33.079),115,1529)
create ("explosive_fuelcan",xyz(-124.662,21.562,-34.187),94,1529)
create ("explosive_barrel",xyz(-117.938,21.563,-32.792),189,1529)
create ("explosive_barrel",xyz(-117.161,21.563,-26.692),202,1529)
create ("explosive_barrel",xyz(-117.966,21.563,-28.606),195,1529)
create ("explosive_barrel",xyz(-117.287,21.563,-34.451),189,1529)
create ("explosive_barrel",xyz(-111.068,21.563,-34.482),268,1529)
create ("explosive_fuelcan",xyz(-111.101,21.680,-33.118),270,1529)
create ("explosive_fuelcan",xyz(-107.269,21.563,-31.553),339,1529)
create ("explosive_fuelcan",xyz(-99.163,21.561,-26.746),502,1529)
create ("explosive_fuelcan",xyz(-99.400,21.563,-28.298),500,1529)
create ("explosive_barrel",xyz(-97.878,21.588,-35.872),529,1529)
create ("explosive_fuelcan",xyz(-97.701,21.615,-33.768),529,1529)
create ("explosive_barrel",xyz(-130.390,20.789,-23.692),7,1529)
create ("explosive_barrel",xyz(-123.025,21.562,-25.809),121,1529)
create ("explosive_fuelcan",xyz(-123.070,21.564,-34.023),113,1529)
create ("explosive_fuelcan",xyz(-128.968,21.563,-28.789),25,1529)
create ("explosive_fuelcan",xyz(-99.111,21.564,-31.907),494,1529)
create ("explosive_fuelcan",xyz(-130.792,23.215,-30.503),11,1529)
create ("explosive_fuelcan",xyz(-130.0508,21.562,-24.9909),7,1529)
end
-- спавним зомби в Х-16
function chess_ending_2 ()
create ("yan_zombied_respawn_1",xyz(-42.274,11.564,-19.919),2587,1530)
create ("yan_zombied_respawn_2",xyz(-62.517,-4.123,-13.379),1423,1531) 
create ("yan_zombied_respawn_1",xyz(-63.173,11.561,-11.667),1319,1530)
create ("yan_zombied_respawn_3",xyz(-28.033,11.563,-6.037),3470,1532)
create ("rad_zombied_respawn_1",xyz(-52.484,3.467,-12.378),1979,1535)
create ("rad_zombied_respawn_2",xyz(-54.577,-4.123,-13.461),1864,1531)
create ("yan_zombied_respawn_2",xyz(-40.231,-4.120,-21.153),2763,1534)
create ("rad_zombied_respawn_1",xyz(-29.515,-4.119,-4.776),3369,1536)
create ("yan_zombied_respawn_1",xyz(-10.942,1.120,-9.751),3868,1536)
create ("rad_zombied_respawn_3",xyz(-4.838,3.364,4.498),4269,1536)
create ("yan_zombied_respawn_3",xyz(0.429,5.590,16.151),4352,1537)
create ("rad_zombied_respawn_1",xyz(22.463,5.585,14.101),4573,1537)
create ("snork_normal",xyz(52.833,5.584,9.920),5569,1537)
create ("snork_stronger",xyz(48.375,5.581,9.006),5434,1537)
create ("rad_zombied_respawn_1",xyz(52.876,5.584,16.915),5591,1537)
create ("yan_zombied_respawn_1",xyz(34.894,5.636,-14.094),4819,1538)
create ("rad_zombied_respawn_3",xyz(47.221,5.584,-11.608),5341,1538)
create ("explosive_barrel",xyz(50.480,5.584,11.972),5518,1537)
create ("explosive_fuelcan",xyz(46.230,5.584,11.604),5331,1537)
create ("rad_zombied_respawn_1",xyz(73.812,5.573,-13.306),5732,1539)
create ("yan_zombied_respawn_2",xyz(97.375,5.620,-27.246),6563,1544)
create ("rad_zombied_respawn_3",xyz(96.874,10.175,-10.507),6555,1544)
create ("rad_zombied_respawn_1",xyz(93.001,10.176,-19.709),6406,1544)
create ("yan_zombied_respawn_2",xyz(88.116,5.572,-18.976),6226,1539)
create ("rad_zombied_respawn_3",xyz(88.723,5.570,-7.333),6265,1539)
create ("explosive_fuelcan",xyz(109.113,5.559,-12.877),6983,1544)
create ("explosive_barrel",xyz(108.774,5.751,-17.322),6976,1544)
create ("explosive_fuelcan",xyz(109.052,5.557,-18.503),6992,1544)
create ("explosive_barrel",xyz(110.992,4.749,-13.446),7023,1544)
create ("explosive_barrel",xyz(110.586,4.956,-15.913),7007,1544)
create ("explosive_fuelcan",xyz(112.312,4.749,-17.236),7029,1544)
create ("explosive_fuelcan",xyz(111.726,4.902,-12.324),7035,1544)
create ("explosive_barrel",xyz(111.303,4.750,-14.137),7022,1544)
create ("explosive_barrel",xyz(-130.713,18.800,-22.616),2,1529)
create ("explosive_fuelcan",xyz(-129.807,18.788,-22.012),7,1529)
create ("explosive_fuelcan",xyz(-130.273,18.898,-21.374),54,1529)
create ("explosive_barrel",xyz(-128.863,18.883,-22.611),54,1529)
end
-- спавним подставу
function chess_ending_3()
create ("yan_zombied_respawn_1",xyz(-94.801,21.836,-31.139),595,1529)
create ("yan_zombied_respawn_2",xyz(-92.938,21.739,-29.590),628,1529)
create ("yan_zombied_respawn_3",xyz(-90.674,21.575,-16.007),752,1530)
create ("explosive_fuelcan",xyz(-92.127,21.645,-29.336),663,1529)
create ("explosive_barrel",xyz(-92.623,21.616,-27.774),665,1529)
create ("explosive_fuelcan",xyz(-98.706,21.563,-31.517),514,1529)
create ("explosive_fuelcan",xyz(-99.969,21.563,-30.247),484,1529)
create ("explosive_barrel",xyz(-103.392,21.563,-30.415),411,1529)
create ("explosive_fuelcan",xyz(-107.499,21.563,-30.496),332,1529)
create("snork_normal",xyz(-92.938,21.739,-29.590),628,1529)
create("explosive_barrel",xyz(-123.298,20.782,-36.573),112,1529)
create("snork_stronger",xyz(-123.191,20.802,-23.166),121,1529)
create("explosive_barrel",xyz(-117.496,20.803,-36.724),189,1529)
create("snork_normal",xyz(-117.542,20.804,-23.242),202,1529)
create("explosive_barrel",xyz(-111.955,20.798,-36.721),257,1529)
create("snork_stronger",xyz(-105.593,20.804,-36.931),402,1529)
create("explosive_barrel",xyz(-105.592,20.772,-23.223),372,1529)
create("snork_normal",xyz(-98.298,21.563,-22.681),541,1529)
create("explosive_barrel",xyz(-97.876,21.563,-39.536),529,1529)
create("snork_stronger",xyz(-101.856,21.563,-20.821),463,1529)
create ("explosive_fuelcan",xyz(-95.832,21.564,-31.250),584,1529)
create ("explosive_barrel",xyz(-94.801,21.836,-31.139),595,1529)
create ("explosive_fuelcan",xyz(-93.705,21.695,-31.151),599,1529)
create ("explosive_fuelcan",xyz(-97.628,21.564,-31.151),547,1529)
create ("explosive_barrel",xyz(-97.085,21.564,-28.9409),551,1529)
create ("explosive_fuelcan",xyz(-96.0305,21.564,-30.553),585,1529)
create ("explosive_barrel",xyz(-112.612,21.564,-30.690),252,1529)
create ("explosive_barrel",xyz(-118.049,21.564,-30.620),192,1529)
create ("explosive_barrel",xyz(-97.359,21.564,-31.175),547,1529)
create ("explosive_barrel",xyz(-102.255,21.563,-21.861),463,1529)
create ("explosive_fuelcan",xyz(-103.706,21.563,-25.026),417,1529)
end
--удаляем Фрица с Генераторов
function delete_frits_2() 
local obj
for a=1,65535,1 do 
obj=server_object(a) 
if obj and string.find(obj:name(),"gen_fritz3") then 
release(obj,true)
return
end 
end 
end
-- спавним Фрица на Генераторах
function frits_2_in ()
create ("frits_3",xyz(156.109,30.651,-493.482),516469,3131)
end
-- oksana579 biorobot
function frits_dialog()
sms("%c[255,160,160,160]".."ФРИЦ:".."\\n".."%c[255,255,128,128]"..game.translate_string("sms_exchange_1"), 10, nil, 20000, nil, [[sms\fric\frits_dialog_1]])
sms("%c[255,160,160,160]".."СТРЕЛОК:".."\\n".."%c[255,255,128,128]"..game.translate_string("sms_exchange_2"), 20, nil, 20000)
sms("%c[255,160,160,160]".."ФРИЦ:".."\\n".."%c[255,255,128,128]"..game.translate_string("sms_exchange_3"), 35, nil, 35000, nil, [[sms\fric\frits_dialog_3]])
sms("%c[255,160,160,160]".."СТРЕЛОК:".."\\n".."%c[255,255,128,128]"..game.translate_string("sms_exchange_4"), 50, nil, 35000)
sms("%c[255,160,160,160]".."ФРИЦ:".."\\n".."%c[255,255,128,128]"..game.translate_string("sms_exchange_5"), 70, nil, 10000, nil, [[sms\fric\frits_dialog_5]])
sms("%c[255,160,160,160]".."ШАХМАТИСТ:".."\\n".."%c[255,255,128,128]"..game.translate_string("sms_exchange_6"), 80, nil, 30000, nil, "chess_voice\\sms_exchange_6")
give_info("info_frits_dialog_done")
end
-- смска Шадовмана 
function shadowman_causes(first_speaker, second_speaker)
sms("%c[255,160,160,160]".."ШЕДОУМЕН:".."\\n".."%c[255,255,128,128]Меченый, если будет по пути, забеги ко мне в Красный Лес. Есть очень серьёзный разговор.", 5, nil, 35000) 
end
----- смерть Холода -- скриптование музыки -----
function postscoring_1() 
say([[chess_voice\guitar_12]]) 
end
-- смерть Круглова
function postscoring_2() 
say([[chess_voice\amblostvil_r]]) 
end
-- Фриц смсобмен
function postscoring_3() 
say([[chess_voice\08_the_thing_r]]) 
end
-- информатор о Лысом
function postscoring_4() 
say([[chess_voice\amb08_r]]) 
end
-- Шахтер о Шахматисте
function postscoring_5() 
say([[chess_voice\ambradar_r]]) 
end
-- Костя
function postscoring_6() 
say([[chess_voice\shadows_music_2_r]]) 
end
-- Костя4
function postscoring_7() 
say([[chess_voice\guitar_13]]) 
end
-- Костя2
function postscoring_8() 
say([[chess_voice\shadows_music_11_r]]) 
end
-- Костя3
function postscoring_9() 
say([[chess_voice\shadows_music_1_r]]) 
end
-- Вася о Холоде
function postscoring_10() 
say([[chess_voice\credits_r]]) 
end
-- Ворон 
function postscoring_11() 
say([[chess_voice\ambx10_r]]) 
end
-- Холод 
function postscoring_12() 
say([[chess_voice\shadows_music_7_r]]) 
end
-- Колмогор 
function postscoring_13() 
say([[chess_voice\shadows_music_10_r]]) 
end
-- Вася
function postscoring_14() 
say([[chess_voice\guitar_14]]) 
end
-- Шахтер о Брате 
function postscoring_15() 
say([[chess_voice\shadows_music_4_r]]) 
end
-- Сахар о Круглове 
function postscoring_16() 
say([[chess_voice\invisible_dangers_pt2_r]]) 
end
-- Майор Батя
function postscoring_17() 
say([[chess_voice\shadows_music_9_r]]) 
end
-- Лаборатории
function postscoring_18() 
say([[chess_voice\09_dead_cities_pt_r]]) 
end
function postscoring_19() 
say([[chess_voice\amb0010_r]]) 
end
function postscoring_20() 
say([[chess_voice\agr_synergistic_perceptions_r]]) 
end
-- Плач
function postscoring_21() 
say([[chess_voice\monolith_call_7]]) 
end
-- Смерть Фрица
function postscoring_22() 
say([[chess_voice\monolith_call_5]]) 
end
-- Пирушка
function postscoring_23() 
say([[chess_voice\amblimansk_r]]) 
end
-- Финал
function postscoring_24() 
say([[chess_voice\megafon_music_33]]) 
end
-- бар мегафон
function postscoring_25() 
say([[chess_voice\announcement_bars]]) 
end
-- Финальная речь
function postscoring_26() 
say([[chess_voice\credits_r]])
end
-- спавним бандитов перед рыбацкой деревней
function gang_fishermen_two () 
create ("ds_bandit_respawn_1",xyz(149.896,1.261,-151.265),224092,3478)
create ("ds_bandit_respawn_2",xyz(149.737,0.928,-144.155),224102,3479)
create ("ds_bandit_respawn_3",xyz(143.441,1.060,-152.474),221013,3478)
create ("esc_bandit_respawn_1",xyz(135.875,0.968,-154.772),216124,3478)
create ("esc_bandit_respawn_2",xyz(123.399,0.914,-137.944),209509,3465)
create ("cit_bandit_respawn_1",xyz(125.541,1.005,-147.968),210700,3465)
create ("cit_bandit_respawn_2",xyz(123.359,0.910,-152.415),209488,3465)
create ("ds_bandit_respawn_1",xyz(120.575,0.539,-157.512),207673,3465)
create ("ds_bandit_respawn_2",xyz(126.549,0.817,-167.536),211418,3468)
create ("ds_bandit_respawn_3",xyz(115.187,8.414,-148.363),204444,3465)
create ("esc_bandit_respawn_1",xyz(114.161,16.094,-149.598),203534,3465)
create ("esc_bandit_respawn_2",xyz(105.036,0.773,-154.567),197020,3465)
create ("cit_bandit_respawn_1",xyz(107.685,0.507,-159.477),198868,3465)
create ("cit_bandit_respawn_2",xyz(13.357,3.354,-248.015),145795,3423)
end
-- спавним крутую засаду
function ambush_laboratory_cool ()
create ("tank_spawn_zasada1",xyz(-46.209,3.468,-4.697),2287,1532)
create ("tank_spawn_zasada2",xyz(-27.397,3.467,-5.074),3575,1532)
create ("tank_spawn_zasada3",xyz(-33.969,11.563,2.415),3203,1532)
create ("explosive_barrel",xyz(-58.351,19.178,-17.532),1703,1530)
create ("tank_spawn_zasada5",xyz(-49.108,19.179,2.317),2149,1530)
create ("explosive_barrel",xyz(-75.602,21.679,-15.143),998,1530)
create ("tank_spawn_zasada3",xyz(-34.719,10.465,-31.789),3051,1534)
create ("tank_spawn_zasada1",xyz(-46.709,3.468,-4.697),2287,1532)
create ("tank_spawn_zasada2",xyz(-27.397,3.467,-5.074),3575,1532)
create ("tank_spawn_zasada3",xyz(-33.969,11.563,2.415),3203,1532)
create ("explosive_barrel",xyz(-58.851,19.178,-17.532),1703,1530)
create ("tank_spawn_zasada5",xyz(-49.108,19.179,2.317),2149,1530)
create ("explosive_barrel",xyz(-75.102,21.679,-15.143),998,1530)
create ("tank_spawn_zasada3",xyz(-1.496,-17.174,45.445),5431,2753)
create ("tank_spawn_zasada1",xyz(-20.138,-8.990,6.347),3474,2674)
create ("tank_spawn_zasada2",xyz(20.913,-8.994,19.804),8710,2686)
create ("tank_spawn_zasada3",xyz(-13.806,-8.991,7.230),3965,2782)
create ("tank_spawn_zasada4",xyz(7.363,-23.522,6.904),7687,2703)
create ("tank_spawn_zasada5",xyz(-22.259,-23.521,-9.777),3028,2784)
create ("tank_spawn_zasada6",xyz(-37.149,-21.831,56.731),1704,2738)
create ("tank_spawn_zasada",xyz(30.434,4.189,11.450),6991,1119)
create ("tank_spawn_zasada1",xyz(-15.816,4.188,8.247),1108,1126)
create ("tank_spawn_zasada2",xyz(-7.952,4.206,-0.753),1842,1112)
create ("tank_spawn_zasada3",xyz(18.833,4.189,-13.096),5641,1117)
create ("tank_spawn_zasada4",xyz(-8.103,9.174,0.292),1790,1110)
create ("tank_spawn_zasada5",xyz(-5.161,4.190,7.480),2138,1125)
create ("tank_spawn_zasada6",xyz(6.282,4.187,-0.0106),3641,1116)
end
-- смска Сахара2 
function death_idler(first_speaker, second_speaker)
sms("%c[255,160,160,160]".."САХАРОВ:".."\\n".."%c[255,255,128,128]Меченый, я получил информацию, что Лентяй погиб! Я его послал на замеры, а от этого олуха ни слуху, ни духу! Если будет по пути, подтвердите или опровергните эту информацию!", 5, nil, 30000, nil, [[sms\saharov\death_idler]]) 
end
-- спавним ЧН раненых
function soldier_wound () 
create ("agr_nebo_zoneguard1",xyz(-145.715,0.611,-291.176),72852,3376)
create ("agr_nebo_zoneguard1",xyz(-149.151,0.566,-290.272),70993,3376)
create ("agr_nebo_zoneguard1",xyz(-194.461,0.258,-291.626),44007,3362)
create ("agr_nebo_zoneguard1",xyz(-172.3004,0.249,-294.404),56061,3362)
create ("agr_nebo_zoneguard1",xyz(-141.910,1.121,-318.162),75333,3374)
create ("agr_nebo_zoneguard1",xyz(-158.470,0.612,-312.451),65067,3374)
create ("rad_zombied_respawn_1",xyz(-121.763,1.172,-289.466),83328,3381)
create ("agr_nebo_zoneguard1",xyz(-142.523,1.334,-276.683),74291,3377)
create ("agr_nebo_zoneguard1",xyz(-144.443,1.335,-277.586),73573,3377)
create ("agr_nebo_zoneguard1",xyz(-147.630,0.580,-294.317),71756,3376)
create ("rad_zombied_respawn_2",xyz(-191.409,0.125,-290.942),45691,3362)
end
-- смска Шахматиста-Фрица
function message_upward(first_speaker, second_speaker)
sms("%c[255,160,160,160]".."ШАХМАТИСТ:".."\\n".."%c[255,255,128,128]Молодец! А теперь поднимайся наверх, Рембо!", 5, nil, 30000, nil, "chess_voice\\message_upward") 
end
-- спавним бочки
function ending_secure ()
create ("explosive_barrel",xyz(-67.014,19.528,-13.623),1107,1530)
create ("explosive_barrel",xyz(-70.968,21.581,-13.873),1058,1530)
create ("explosive_barrel",xyz(-76.303,21.578,-14.013),991,1530)
create ("explosive_barrel",xyz(-66.827,19.327,-13.109),1138,1530)
create ("explosive_barrel",xyz(-66.644,19.342,-15.307),1129,1530)
create ("explosive_barrel",xyz(-66.564,19.328,-14.509),1132,1530)
create ("explosive_barrel",xyz(-62.076,19.180,-9.172),1436,1530)
end

-- финальные титры
function final_credits(first_speaker, second_speaker)
sms("%c[255,0,255,0]".."oksana579:".."\\n".."%c[255,255,255,0]Сценарий, диалоги, квесты, сюжетные идеи, лёгкие скрипты, скриптование и подбор музыки, спавн.", 10, "shax", 30000)
sms("%c[255,0,255,0]".."azrael1325:".."\\n".."%c[255,255,255,0]Скриптовая функция Диктофона, сложные скрипты, ПДА, скриптовые эффекты, текстуры.", 25, "shax", 30000)
sms("%c[255,0,255,0]".."Zizon:".."\\n".."%c[255,255,255,0]Игровые моменты, сюжетные идеи.", 45, "shax", 30000)
sms("%c[255,0,255,0]".."frankenshtayn, Fagot:".."\\n".."%c[255,255,255,0]Консультации, логика НПС.", 70, "shax", 20000)
sms("%c[255,0,255,0]".."Andewil, groks:".."\\n".."%c[255,255,255,0]Тестирование, идеи, замечания, здоровая критика.", 85, "shax", 20000)
sms("%c[255,0,255,0]".."Руслан Мурзов:".."\\n".."%c[255,255,255,0]Озвучка Шахматиста. Продолжение следует...", 95, "shax", 30000)
end

-- спавним монолит на трубе
function setup_mockery ()
create ("chess_teleport_5",xyz(440.404,12.615,164.082),146735,2599)
create ("chaes_mono_1",xyz(180.704,149.167,105.944),73076,2573)
create ("chaes_mono_2",xyz(180.204,149.167,105.944),73076,2573)
create ("chaes_mono_3",xyz(181.704,149.167,105.944),73076,2573)
create ("dcity_lastday_respawn_1",xyz(36.135,4.999,108.884),41084,2528)
create ("dcity_lastday_respawn_2",xyz(33.873,4.979,122.788),39972,2528)
create ("dcity_lastday_respawn_1",xyz(37.528,5.0002,109.190),41391,2528)
create ("dcity_lastday_respawn_2",xyz(66.212,4.968,110.265),53290,2536)
create ("dcity_lastday_respawn_1",xyz(62.324,8.512,125.319),52162,2536)
create ("dcity_lastday_respawn_2",xyz(46.634,4.758,160.608),45823,2527)
create ("dcity_lastday_respawn_1",xyz(34.274,4.929,150.975),40271,2527)
end

-- спавним монстров
function hiding_bartender ()
create ("bloodsucker_weak",xyz(-144.325,14.487,-162.193),638609,3672)
create ("bloodsucker_strong",xyz(-144.354,15.318,-157.274),638612,3672)
create ("bloodsucker_hell",xyz(-149.701,16.693,-157.873),638612,3672)
create ("bloodsucker_strong",xyz(-149.662,16.874,-162.647),642855,3672)
end
-- спавним тайник бармена
function hiding_bartender_1 ()
create ("bartender_cache",xyz(-149.489,16.763,-160.448),638609,3672)
end
-- спавним монстров в деревне на глюк
function sudden_ambush_1 ()
create ("snork_normal",xyz(-0.302,9.189,-70.447),13575,3329)
create ("snork_stronger",xyz(6.144,9.188,-66.472),15278,3329)
create ("snork_normal",xyz(8.142,9.189,-67.849),15656,3329)
create ("bloodsucker_strong",xyz(8.089,9.189,-73.646),15823,3329)
create ("bloodsucker_mil",xyz(12.621,8.889,-66.640),17016,3329)
end
function sudden_ambush_2 ()
create ("snork_normal",xyz(-84.548,2.711,-13.631),3761,3326)
create ("snork_jumper",xyz(-65.217,2.568,6.231),3779,3326)
create ("snork_normal",xyz(-73.025,2.526,9.240),3779,3326)
create ("snork_jumper",xyz(-94.026,2.614,40.385),3779,3326)
create ("snork_normal",xyz(-63.995,2.493,32.866),3779,3326)
create ("snork_stronger",xyz(-47.780,2.495,28.618),3779,3326)
create ("snork_normal",xyz(-83.783,2.711,-20.590),3761,3326)
create ("m_controller_old_fat",xyz(-51.145,2.494,28.988),3780,3326)
end
function sudden_ambush_3 ()
create ("note_15",xyz(11.822,10.259,-71.582),16398,3329)
create ("note_16",xyz(-56.310,0.791,16.810),3779,3326)
create ("af_rusty_sea-urchin1",xyz(-51.214,1.793,25.446),3779,3326)
create ("af_rusty_sea-urchin",xyz(-89.048,3.535,6.375),3779,3326)
create ("af_rusty_sea-urchin",xyz(-54.096,2.427,-2.361),3775,3326)
create ("af_rusty_sea-urchin",xyz(-53.907,2.605,-10.976),3762,3326)
create ("af_rusty_sea-urchin",xyz(-68.620,3.230,-17.671),3761,3326)
create ("af_rusty_sea-urchin",xyz(-45.432,2.8007,-29.263),3863,3326)
create ("af_rusty_sea-urchin",xyz(-57.722,2.323,-27.659),3761,3326)
create ("af_rusty_sea-urchin",xyz(-60.567,2.693,-19.140),3761,3326)
create ("af_rusty_sea-urchin",xyz(-80.373,2.626,-14.866),3761,3326)
create ("af_rusty_sea-urchin",xyz(-69.415,2.011,12.998),3779,3326)
create ("af_rusty_sea-urchin",xyz(-58.079,1.629,8.857),3779,3326)
create ("af_rusty_sea-urchin",xyz(-73.587,2.670,-33.450),3761,3326)
create ("af_rusty_sea-urchin",xyz(-63.005,2.537,-33.975),3761,3326)
create ("af_rusty_sea-urchin",xyz(-49.659,2.688,-31.018),3761,3326)
create ("af_rusty_sea-urchin",xyz(-68.451,3.230,-9.028),3765,3326)
create ("af_rusty_sea-urchin",xyz(-73.177,2.695,-3.376),3773,3326)
end
-- телепорты в деревне
function teleport_ezh_1()
  local obj = create("chess_teleport_6",xyz(127.044,9.552,-18.516),49064,3336)
  xr_logic.pstor_store(db.actor, "chess_teleport_6", obj.id)
end
function teleport_ezh_2()
  local obj = create("chess_teleport_7",xyz(-95.494,3.192,54.844),3779,3326)
  xr_logic.pstor_store(db.actor, "chess_teleport_7", obj.id)
end

function del_teleport_ezh()
  local obj_id = xr_logic.pstor_retrieve(db.actor, "chess_teleport_6", -1, true)
  local obj = server_object(obj_id) 
  if obj then 
    release(obj, true) 
  end
  obj_id = xr_logic.pstor_retrieve(db.actor, "chess_teleport_7", -1, true)
  obj = server_object(obj_id) 
  if obj then 
    release(obj, true) 
  end
end

function akim_panic()
if shax_start() then
	sms("%c[255,160,160,160]".."АКИМ:".."\\n".."%c[255,255,128,128]Меченый, ноги в руки и мелкими перебежками через огороды ко мне! Весь Кордон на измене! Кто-то у меня на КПП нейтралов порезал и оставил записку: Привет от Шахматиста!", 5, nil, 30000)
end
end
function shax_start()
	return has_info("tel_dcity_kanaliy") and has_info("volna_day4_done")
end
