--[[
	snp.invul_on()
	give_info("vol_info_temp")
	give_info("sar_monolith_destroy")
	give_info("bar_deactivate_radar_done")
	give_info("arhara_shaxter_start")
	give_info("esc_serious_talk")
	give_info("dimak_doki_start")
	give_info("doki_dimak_done")
	give_info("tutorial_end")
	got("teleportator",1)
	got("anom_egg",100)
	for	i=1, 64 do
		lost_all("arhara_obman"..tostring(i))
		give_info("arhara_obman"..tostring(i))
	end
	give_info("dimak_toolkit_done")
	give_info("fli_have_3")
	got("wpn_ognemet",1)
	got("wpn_gravigun",1)
	got("wpn_rg6_m2",1)
	got("wpn_kastet",1)
	got("ammo_vog-25he",5)
	got("ammo_vog-25fb",5)
	got("ammo_vog-25sg",5)
	got("ammo_vog-25sn",5)
	got("wpn_mp153",1)
	got("bioradar2",1)
	got("det_artefact_super",1)
	got("detector_elite_john",1)
	got("runner_tele",1)
	got("ammo_12x70_kart",30)
	got("ammo_balon",5)
	got("medkit",10)
	got("af_power_3",3)
	got("matras",1)
	got("kolbasa",10)
	got_money(4000000)	
--]]

--[[
	snp.invul_on()
	give_info("vol_info_temp")
	got("anom_egg",20)
	got("medkit",10)
	got("runner_tele",1)
	got("wpn_ks23",1)
	got("ammo_23x76_shrap",10)
	got("af_power_3",1)
	got_money(2000000)	
--]]

--	_G.death_manager = nil
--	buusty_dialog.voyaki_zasada_krot()
--	create("mil_monolit_rush_respawn_1",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
--	create("af_medusa",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
--	create("af_medusa",xyz(147.86102294922,-0.0037327408790588,59.646175384521),39663,1228)
--	create(3730)
--	snp_parad.parad_start()
--	sms(tostring(db.actor:object("bandit_veteran_outfit_m1") ~= nil))
--	akill.bottle_spawn()
	
--	disable_info("acv_zoolog")
--	give_info("esc_bridge_vodka_done")
--	give_info("acv_avstriez")
--	disable_info("doki_dimak_done")
--	disable_info("sar_monolith_destroy")
--	give_info("bar_dolg_bunker_pass")
--	give_info("bar_dolg_community_leader")
--	give_info("bar_svoboda_rg6_done")
--	give_info("doki_dimak_done")
--	give_info("agroprom_military_case_done")
--	give_info("bar_darklab_document_done")
--	give_info("sidor_chip")
--	give_info("snp_parad_start")
--	give_info("vol_info_temp")
--	give_info("sidor_delo_done")
--	game.start_tutorial("dream_trailer12")

--	_G.Treasure = nil _G.treasure = nil _G.Treasure = treasure.CTreasure()
--	treasure.give()

--	release(server_object("escape_trader"))
--	create(ai:spawn_id(3))
--	_G.cycle_task = nil _G.Cycle_Task = nil	_G.Cycle_Task = cycle_task.CCycleTask()
--	_G.Cycle_Task:stats()
--	got("part_boar_leg",1)

--[[
	_G.descriptors = nil
	lost("wpn_ognemet")
	got("wpn_ognemet")
--]]

--	log(device().fov)
--	log(tostring(has_info("paused_on_load")))
--	console:execute("load ~~~ "..xr_gulag.getGulagState(3070))
--	console:execute("load ~~~ "..task_desc.name..task_desc.target..task_desc.target_count)
--	db.actor:set_actor_position(server_object("mil_dolg_stalker0006").position)
--	db.actor:set_character_rank(6000)

--	release(story_object(9501))
--	create(ai:spawn_id(9501))
--	disable_info("sak_repair_box_done")
--	sms(tostring(has_info("sak_repair_box_done")), nil, nil, 10000)
--	sms(tostring(has_info("sak_reward_outfit_done")), nil, nil, 10000)
--	sms(tostring(db.actor.radiation), nil, nil, 10000)
--	db.actor:set_actor_direction(0)
--	lost("ballast")
--	got("part_psevdodog_tail",1)
--	got("wpn_fn2000_paratrooper",1)
--	got("anom_egg",3)
--	got("repair_item_weapon",3)
--	got("repair_item_outfit",3)
--	got("wpn_m_134",1)
--	got("wpn_m134",1)
--	got("kolbasa",10)
--	got("det_artefact_super",1)
--	got("scientist_suit_white",1)
--	got("wpn_spas12_m1",1)
--	got("ammo_9x18_fmj",2)
--	got("detektor_amorf",1)
--	got("wpn_spas23",1)
--	got("af_dummy_battery",1)
--	got("wpn_mp40",1)
--	got("acumm",1)
--	got("wpn_elf",1)
--	got("wpn_pmm",2)
--	got("bandage",5)
--	got("nano_suit",1)
--	got("amk_transmutator",1)
--	got("wpn_shmel",1)
--	got("part_burer_hand",1)
--	got("wpn_gravigun",1)
--	got("wpn_svd_m3",1)
--	got("tolik_shtany",3)
--	lost("teleportator")
--	snp.invul_off()
--	snp.invul_on()
--	db.actor:kill(db.actor)
--	news_manager.send_tip(tostring(has_good("wpn_ak74",3)), nil, nil, 10000)
--	lost_good("wpn_ak74",3)
--	smart_terrain.stat()
--	got_treasure("atp_arhara_secret_3")
--	_G.Treasure:check()

--[[ Спавн изношенного оружия
	local obj
	for i=1,1 do
		obj = create("wpn_knife", db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
		level.client_spawn_manager():add(obj.id, 0, 
			function (cond, id, obj)
				level_object(id):set_condition(cond)
			end
		, math.random()+0.3)
	end
--]]

--	sms(server_object("cave_scelety_zastenoi").id)

--[[ -- поиск объекта
	local obj
	local actor_level = object_level(db.actor)
	local cnt=0
	for i=1,65534 do
		obj = server_object(i)
--		if obj then
--		obj = level_object(i)
--		if obj then
--		if obj and obj:clsid() == clsid.inventory_box and obj:section_name() == "val_taynik_4" then
--		if obj and obj:clsid() == clsid.level_changer then
--		if obj and obj:clsid() == clsid.smart_terrain then
--		if obj and obj:section_name() == "mutant_crow" and obj.parent_id == 65535 then
--		if obj and obj:name() == "esc_provodnik" then
--		if obj and obj:section_name() == "inventory_box" and obj.position.y == -300 then
--		if obj and string.find(obj:section_name(), "sakbuzz") and object_level(obj) == actor_level then
--		if obj and boxes[obj.parent_id] then
--		if obj and string.find(obj:name(),"af_") and obj:parent() == nil 
--			and object_level(obj) == actor_level
--		then
--		if obj and db.actor:position():distance_to(obj.position) < 3 then
--		if obj and IAmAStalker[obj:clsid()] and object_level(obj) == actor_level then
		if obj and obj:name() == "dshor_middle_base_bibliofriend" then
--		if obj and obj.smart_terrain_id and obj:smart_terrain_id() == 33365 then
--		if obj and (IAmAStalker[obj:clsid()] or IAmAMonster[obj:clsid()]) then
--			level.map_add_object_spot_ser(obj.id, "blue_location", obj:name())
--			release(obj)
--			db.actor:set_actor_position(obj.position)
--			local txt = tostring(IAmAStalker[obj:clsid()])
--			sms(txt, nil, nil, 10000)
--			cnt=cnt+1
--			console:execute("load ~~~ item: ".. obj:section_name().." parent: "..obj.parent_id)
--			console:execute("load ~~~ item: ".. obj:section().." y: "..obj:position().y)
--			console:execute("load ~~~ spot: ".. tostring(level.map_has_object_spot(obj:id(), "level_changer")))
--			obj:clear_smart_terrain()
--[-=[
			console:execute("load ~~~ name: ".. tostring(obj:name()))
--			console:execute("load ~~~ online: ".. tostring(obj.online))
			console:execute("load ~~~ level: ".. tostring(object_level_name(obj)))
			console:execute("load ~~~ smart_terrain_id: ".. tostring(obj:smart_terrain_id()))
--			console:execute("load ~~~ smart_terrain: ".. tostring(server_object(obj:smart_terrain_id()):clsid()==clsid.smart_terrain))
			console:execute("load ~~~ smart_terrain_name: ".. server_object(obj:smart_terrain_id()):name())
--]=]
			break
		end
	end
--	console:execute("load ~~~ cnt: "..cnt)
--]]

--[[ очистка всех монстров\сталкеров в офлайне
	local obj
	for i=1,65534 do
		obj = server_object(i)
--		obj = level_object(i)
--		if obj and IAmAMonster[obj:clsid()] and obj:section() ~= "boar_child" and obj:section() ~= "boar_mother" and obj:section() ~= "boar_children" then
			if obj and (IAmAMonster[obj:clsid()] or IAmAStalker[obj:clsid()]) then
--			if obj and IAmAMonster[obj:clsid()] then
--			if obj and IAmAStalker[obj:clsid()] then
--			if obj and obj:section() == "snp_kordon1" and obj:alive() then
--			obj:kill(db.actor)
			release(server_object(i))
		end
	end
--]]

--[[
--snp.release_all_online("vehicle_btr")
--amk_mod.spawn_military_btr()
--amk_mod.spawn_military_tech_pack(create("vehicle_btr",xyz(255.91418457031,5.349621295929,21.442276000977),1404424,3684),"vehicle_btr", "scripts\\ohota\\volna_btr.ltx")
--amk_mod.spawn_military_tech_pack( create("vehicle_btr",xyz(238.92939758301,6.8748126029968,40.994895935059),1373280,3684), "vehicle_btr", "scripts\\snp\\btr_monsters.ltx")
--amk_mod.spawn_military_tech_pack( create("vehicle_btr",xyz(234.36315917969,8.2055072784424,96.457916259766),1365572,3684), "vehicle_btr", "scripts\\snp\\btr_monsters.ltx")
--amk_mod.spawn_military_tech_pack( create("vehicle_btr",xyz(226.72500610352,7.5734214782715,21.378383636475),1351721,3684), "vehicle_btr", "scripts\\snp\\btr_monsters.ltx")
--snp_parad.create_btr(xyz(173.02828979492,27.631801605225,-188.02941894531),1010191,3735, snp_parad.tm_btr_logic())
--]]

--[[ ускорение времени
	if tf then
		level.set_time_factor(config:r_float("alife","time_factor")*1000)
		tf = false
	else
		level.set_time_factor(config:r_float("alife","time_factor"))
		tf = true
	end
--]]

--[[ тест позиции
	if prev_art then
		release(prev_art)
		prev_art = nil
	end
	if prev_art2 then
		release(prev_art2)
		prev_art2 = nil
	end

--[=[
	local b = {
	} local a = b[1] 
	
	if a then
		prev_art = create("m_inventory_box", xyz(a.position.x,a.position.y,a.position.z), a.lv, a.gv)
	else
		prev_art = create("koster", xyz(32.0455589294434,15.798966217041,664.038208007813), 313133, 207)
	end

--	db.actor:set_actor_position(xyz(a.position.x,a.position.y,a.position.z))
--]=]

--	prev_art = amk_anoms.spawn_rand_anom(vector():set(110.00815582275,0.8815416097641,350.41976928711),234,411827)
--	sms(prev_art:section_name(), nil, nil, 5000)
--	prev_art = create("car7",xyz(476.4153137207,27.045625686646,-444.02090454102),1467869,3745)
--	prev_art = create("trofim_npc",xyz(82.861618041992,0.054342240095139,-9.3183221817017),275941,989)

--]]

--[[ чтение LTX
	local ini = ini_file("misc\\treasure.ltx")

	if ini:section_exist("main") then
		local n = ini:line_count("main")
		for i=0,n-1 do
			result, section, value = ini:r_line("main",i,"","")
			console:execute("load ~~~ visual: "..rx_utils.read_from_ini(nil, section, "visual", "", 1))
		end
	end
--]]
	
--[[ хит актору
	sms(tostring(db.actor.health), nil, nil, 10000)
	local h = hit()
	h.draftsman = db.actor
	h.type = hit.fire_wound
	h.direction = db.actor:position()
	h:bone("bip01_spine")
	h.power = 1
	h.impulse = 10
	db.actor:hit(h)
	sms(tostring(db.actor.health), nil, nil, 10000)
--]]

--	Восстановление отношений
--	kostya_dialog.obj_by_name("labirint_shade_monolit"):set_relation(game_object.neutral,db.actor)
--	relation_registry.change_community_goodwill ("monolith", db.actor:id(), 5500)
--  db.actor:set_character_community("monolith", 0, 0)

--[[ переспавн объекта из алспаун
	local obj = server_object("trader_door")
	if obj then
--		console:execute("load ~~~ id: "..tostring(obj.id))
--		console:execute("load ~~~ logic: "..tostring(obj:spawn_ini():section_exist("logic")))
--		console:execute("load ~~~ scheme: "..tostring(db.storage[obj.id]))
		release(obj)
--		ai:set_switch_online(obj.id, true)
--		ai:set_switch_offline(obj.id, true)
	end
	create(3048)
--		ai:set_switch_online(obj.id, true)
--		ai:set_switch_offline(obj.id, true)
--]]

--[[ отношения в Волне
	local obj2 = level_object(server_object("buusty_zaton").id)
	local obj1 = snp.object_by_section("proper70_zaton")
--	obj1:set_goodwill(100,obj2)
	sms(tostring(obj1:goodwill(obj2)), nil, nil, 10000)
--]]

--[[ Письма тест
	for i = 1,44 do
		give_info(("letter_"..i))
	end
--]]

--[[ тест новостей
local news_uniq={
--"Мародёры зажали, выручайте!\\n%c[255,160,160,160]Потап\\n%c[default]Координаты-то приложи, умник.",

}
for i=1,#news_uniq do
	local uniq=news_uniq[i]
	local name,sname = amk_names_lists.get_strings()
	amk.send_tip(uniq,name.." "..sname,nil,30,"uniq")
end
--]]

--	_G.news_manager = nil
--[=[
local mod_news={
--"%c[255,160,160,160]Витязь\\n%c[default]Коршун, я Витязь. Как слышишь? Прием.\\n%c[255,160,160,160]Коршун\\n%c[default]Витязь, я Коршун. Стоим у объекта. Какие-то странные помехи. Аппаратура полностью вышла из строя. Полчаса назад отбили нападение монстров. Совсем неизвестных монстров и... Остальное потом. Есть потери. Запрашиваю срочную эвакуацию. Прием...",

}
for i=1,#mod_news do
	local mod_news = mod_news[i]
	-- попробуем подобрать иконку
	local x,y, pos
	pos = string.find(mod_news,"[default]",1,true)
	if pos then
		x,y = news_manager.get_sender_icon(string.sub(mod_news,1,pos-5)..":")
	else
		x,y = 498,47
	end

	db.actor:give_game_news(mod_news, "ui\\ui_iconsTotal", Frect():set(x,y,83,47), 0, string.len(mod_news)/8*1000)
	say([[device\pda\pda_tip]])
end
--]=]

--[[Отладка zonedocs
		local se_obj = create("zone_docs",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
		if     has("zone_docs",3) then
			give_info("voronin_docs1_have")
		elseif has("zone_docs",1) then
			give_info("voronin_docs1_almost_have")
		end
--]]
--		local se_obj = create("zone_docs",xyz(-97.878524780273,15.606694221497,127.96105957031),109975,2881)

--[=[
	local p = "upd.w"
	local t = {}
	t.upd = {}
	if string.find(p,".") then
		local i = p:explode(".")
		t[i[1]][i[2]] = 1
	else
		t[p] = 1
	end
	t[p] = 1
	sms(t.upd.w)
--]=]

--	local obj = create("bibliotekar",xyz(-52.541351318359,2.2499685287476,102.57232666016),176274,9180)
--	netpacket:modify(obj, "visual_name", "monsters\\bibliotekar\\bibliotekar_black", "story_id", 1990026)

--[[ Спавн раненого
		local obj = create("atp_brigada_respawn_3",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
--		local obj = create("gar_bandit_respawn_1",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())

		netpacket:modify(obj, "health", 0.1, "upd.health", 0.05)
		got("medkit",1)
--]]
		
--[[	спавн летающего острова
	__y1 = 17
	
	if not __y2 then
		__y2 = 0
	end

--	__lv = db.actor:level_vertex_id() __gv = db.actor:game_vertex_id() __pos = db.actor:position() __y2 = 0
	__pos = vector():set(__pos.x,__pos.y+__y1-__y2,__pos.z)
	__y2 = __y1
	console:execute("fli:") console:execute("{position={x="..__pos.x..",y="..__pos.y..",z="..__pos.z.."},gv="..__gv..",lv="..__lv.."},") console:execute("vector():set("..__pos.x..","..__pos.y..","..__pos.z.."),"..__lv..","..__gv..")")
--
	if prev_art then
		release(prev_art)
	end
	if prev_art2 then
		release(prev_art2)
	end

	prev_art = create("fly_island",__pos,__lv,__gv)
	netpacket:modify(prev_art, 
		"object_flags", -198,		-- 0xffffff3a object_flags
		"visual_flags", 1,			-- 0x1 visual_flags
		"skeleton_name", "idle",
		"skeleton_flags", 1,
		"physic_type", 3,			-- 0x3
		"mass", 100,
		"fixed_bones", "link")
	prev_art2 = create("zone_fly_island",__pos,__lv,__gv)
]]

--[[ респавн островов
	local obj, section
	for i=1,65534 do
		obj = server_object(i)
		if obj then
			section = obj:section_name()
			
			if (section == "fly_island" or section == "zone_fly_island" or section == "zone_tuman3") then
--			if string.find(section,"fenrir_jupiter") then
				release(obj, true)
			end
		end
	end

	fly_island.create_fly_island(xyz(-246.46073913574,3.1428375244141,-21.434331893921),9980,67)
]]

--[[ Туман над болотами
	if prev_art3 then
		release(prev_art3)
	end
	prev_art3 = create("zone_tuman3",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
]]
